### ISSUE TITLE
webdriver的域名或ip

### ISSUE THREAD

**Issue by llxiao** [alibaba/uirecorder#1]
测试初始化过程中的webdriver的域名或ip填的是什么？

**Comment by gleams** [comment]
这是: selenium的服务地址么？
先启动服务  http://selenium-release.storage.googleapis.com/index.html

**Comment by yaniswang** [comment]
http://jwebdriver.com/

可以参考下面Selenium server的部署教程。

或者也可以使用Selenium Grid

当然，我们更建议使用F2etest的WebDriver云服务：https://github.com/alibaba/f2etest

**Comment by llxiao** [comment]
多谢，问题已经解决了
