### ISSUE TITLE
可否将 Chrome 插件中的 z-index 值设置的大一些？

### ISSUE THREAD

**Issue by fuxiao126** [alibaba/uirecorder#10]
感谢提供如此好用的测试工具！
可否将 Chrome 插件中的 z-index 值设置的大一些？9999999 的 z-index 有时会小于某些 JS 弹层插件的 z-index 值，此时操作面板和 uirecorder 弹出的层就被其他 div 盖住了。
不知可不可以写一个最大的极限值？

**Comment by yaniswang** [comment]
好的，下一个版本设置为：2147483647

**Comment by fuxiao126** [comment]
@yaniswang 感谢！
