### ISSUE TITLE
变量功能不支持中文？

### ISSUE THREAD

**Issue by HeartIsBeat** [alibaba/uirecorder#101]
![image](https://cloud.githubusercontent.com/assets/20472976/26778421/c1201b4e-4a13-11e7-93b7-781e288b795e.png)

![image](https://cloud.githubusercontent.com/assets/20472976/26778446/d205332c-4a13-11e7-9a5a-41086ceb0d7e.png)
去掉中文，就能回放了，能支持中文内容变量么？
另外config.json中注释符号是咋？# //都不是哦

**Comment by yaniswang** [comment]
可以用中文的啊，变量你可以在录制过程中动态的添加，添加的变量会在录制结束时回写回config.json

你的问题肯定是自己手写json文件时，不小心写错了某个语法

**Comment by HeartIsBeat** [comment]
@yaniswang 多谢啊啊啊 ，确实写错了。囧
