### ISSUE TITLE
uirecorder didn't recognize ios native popups like "Send notification"

### ISSUE THREAD

**Issue by msmirzazadeh** [alibaba/uirecorder#104]

**Comment by yaniswang** [comment]
Show screenshot

**Comment by msmirzazadeh** [comment]
<img width="421" alt="screen shot 2017-06-07 at 12 09 47 pm" src="https://user-images.githubusercontent.com/26924125/26867351-43031e7e-4b7a-11e7-8cf6-ab661dc7a7c8.png">
