### ISSUE TITLE
录制上传upload图片功能，回放失败

### ISSUE THREAD

**Issue by HeartIsBeat** [alibaba/uirecorder#106]
![image](https://user-images.githubusercontent.com/20472976/26867816-6aaae1ea-4b99-11e7-87d1-3585d29aa883.png)
![image](https://user-images.githubusercontent.com/20472976/26867822-70630a72-4b99-11e7-940a-dddd13b1d415.png)
![image](https://user-images.githubusercontent.com/20472976/26867826-7311fabc-4b99-11e7-82fb-0cffacdd683a.png)
按限制，button按钮已经加上role="upload"，上传的图片也已经放到uploadfiles了，但是就是回放失败呀.....
咋原因呢？我该从哪里入手解决这个问题？
it('uploadFile: #html5_1bhua9lgg35ph8e1subr1frqb4, 2.jpg', async function(){
        await driver.sleep(300).wait('#html5_1bhua9lgg35ph8e1subr1frqb4', {timeout: 30000, displayed: false})
               .sleep(300).uploadFile(rootPath+'/uploadfiles/2.jpg');
    });

哦，input上传按钮倒是录制回放成功了。

**Comment by yaniswang** [comment]
![image](https://user-images.githubusercontent.com/970390/26868944-42b86334-4b9d-11e7-8aa7-0d0ab67d448f.png)
问题出在id是个随机值，你要在属性值黑名单上加个正则，对于这个情况可以配：
/html5-\w+/

**Comment by HeartIsBeat** [comment]
灰常感谢啊，可以了！

**Comment by HeartIsBeat** [comment]
@yaniswang 大神，灰常感谢啊，可以了！
