### ISSUE TITLE
使用ie11回放几乎每次都会出现windows index overflow错误

### ISSUE THREAD

**Issue by Kaleym** [alibaba/uirecorder#107]
switchWindow: 1 Code524 ms
Error: the string "Window index overflow" was thrown, throw an Error :)

另外，想问一下大神黑名单属性值是怎么回事，谷歌无果

**Comment by yaniswang** [comment]
属性黑名单是指为了跳过那些不稳定的属性，例如某些id或name值是随机的，我们就要避免使用这些属性。

**Comment by Kaleym** [comment]
多谢

**Comment by zhangjianpinghik** [comment]
@Kaleym  @yaniswang  怎么去判断哪些属性会导致报错Window index overflow,从而把这些数据行加入黑名单呢?

**Comment by yaniswang** [comment]
Window index overflow是因为不该关闭的窗口被关闭了，所以导致指定的窗口编号定位不到了
