### ISSUE TITLE
执行录制脚本报错 macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by yxxx5** [alibaba/uirecorder#109]
[mochawesome] Generating report files...

  sample/test.spec : chrome
    1) "before all" hook
    2) "after all" hook

  0 passing (31ms)
  2 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

  2) sample/test.spec : chrome "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

[mochawesome] Report saved to reports/index.html
[mochawesome] Report saved to reports/index.xml

(node:3698) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3698) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3698) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "sample/test.spec.js"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yaniswang** [comment]
4444端口连接失败，你没有把macaca启动在4444端口号

**Comment by bingxueDU** [comment]
@yaniswang 大神 上周还能录制回放，这周回放的时候报错。然后去启动webdriver server报错，总是启动不了~
> uirecorderTest@1.0.0 server C:\Users\uc
> selenium-standalone start

Error: Invalid or corrupt jarfile C:\Users\uc\node_modules\_selenium-standalone@
6.8.0@selenium-standalone\.selenium\selenium-server\3.5.2-server.jar
C:\Users\uc\node_modules\_selenium-standalone@6.8.0@selenium-standalone\bin\sele
nium-standalone:79
        throw err;
        ^

Error: Selenium server did not start.
Another Selenium process may already be running or your java version may be out
of date.
Be sure to check the official Selenium release notes for minimum required java v
ersion: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGE
LOG

    at ChildProcess.errorIfNeverStarted (C:\Users\uc\node_modules\_selenium-stan
dalone@6.8.0@selenium-standalone\lib\start.js:158:10)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 server: `selenium-standalone start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\uc\AppData\Roaming\npm-cache\_logs\2017-09-01T08_27_28_870
Z-debug.log

**Comment by yaniswang** [comment]
你之前的进程还启动在那里吧？kill掉，或者重启下机器
