### ISSUE TITLE
IEDriverServer启动不成功

### ISSUE THREAD

**Issue by guozhen168** [alibaba/uirecorder#11]
我的环境如下：
操作系统：win7_64
浏览器：ie8
selenium-server-standalone-2.53.1
IEDriverServer_x64_2.53.1

服务执行命令为：java -jar selenium-server-standalone-2.53.1.jar -Dwebdriver.ie.driver=IEDriverServer.exe

测试用户运行报错：
  test.spec : ie 8
    1) "before all" hook

  0 passing (20s)
  1 failing

  1) test.spec : ie 8 "before all" hook:
     Error: done() invoked with non-Error: {"message":null,"suppressed":[],"loca
lizedMessage":null,"cause":null,"class":"java.util.concurrent.TimeoutException",
"hCode":477370813,"stackTrace":[{"fileName":null,"class":"java.lang.StackTraceEl
ement","lineNumber":-1,"className":"java.util.concurrent.FutureTask","nativeMeth
od":false,"methodName":"get","hCode":413889654},{"fileName":"SimpleTimeLimiter.j
ava","class":"java.lang.StackTraceElement","lineNumber":130,"className":"com.goo
gle.common.util.concurrent.SimpleTimeLimiter","nativeMethod":false,"methodName":
"callWithTimeout","hCode":-2004172171},{"fileName":"UrlChecker.java","class":"ja
va.lang.StackTraceElement","lineNumber":80,"className":"org.openqa.selenium.net.
UrlChecker","nativeMethod":false,"methodName":"waitUntilAvailable","hCode":-7423
18711},{"fileName":"DriverService.java","class":"java.lang.StackTraceElement","l
ineNumber":175,"className":"org.openqa.selenium.remote.service.DriverService","n
ativeMethod":false,"methodName":"waitUntilAvailable","hCode":-451304678},{"fileN
ame":"DriverService.java","class":"java.lang.StackTraceElement","lineNumber":166
,"className":"org.openqa.selenium.remote.service.DriverService","nativeMethod":f
alse,"methodName":"start","hCode":-1827402477},{"fileName":"DriverCommandExecuto
r.java","class":"java.lang.StackTraceElement","lineNumber":78,"className":"org.o
penqa.selenium.remote.service.DriverCommandExecutor","nativeMethod":false,"metho
dName":"execute","hCode":-633333586},{"fileName":"RemoteWebDriver.java","class":
"java.lang.StackTraceElement","lineNumber":644,"className":"org.openqa.selenium.
remote.RemoteWebDriver","nativeMethod":false,"methodName":"execute","hCode":1767
885131},{"fileName":"RemoteWebDriver.java","class":"java.lang.StackTraceElement"
,"lineNumber":249,"className":"org.openqa.selenium.remote.RemoteWebDriver","nati
veMethod":false,"methodName":"startSession","hCode":-1182648225},{"fileName":"Re
moteWebDriver.java","class":"java.lang.StackTraceElement","lineNumber":234,"clas
sName":"org.openqa.selenium.remote.RemoteWebDriver","nativeMethod":false,"method
Name":"startSession","hCode":-1182648240},{"fileName":"InternetExplorerDriver.ja
va","class":"java.lang.StackTraceElement","lineNumber":182,"className":"org.open
qa.selenium.ie.InternetExplorerDriver","nativeMethod":false,"methodName":"run","
hCode":-1132542939},{"fileName":"InternetExplorerDriver.java","class":"java.lang
.StackTraceElement","lineNumber":174,"className":"org.openqa.selenium.ie.Interne
tExplorerDriver","nativeMethod":false,"methodName":"<init>","hCode":-2098680252}
,{"fileName":"InternetExplorerDriver.java","class":"java.lang.StackTraceElement"
,"lineNumber":150,"className":"org.openqa.selenium.ie.InternetExplorerDriver","n
ativeMethod":false,"methodName":"<init>","hCode":-2098680276},{"fileName":null,"
class":"java.lang.StackTraceElement","lineNumber":-2,"className":"sun.reflect.Na
tiveConstructorAccessorImpl","nativeMethod":true,"methodName":"newInstance0","hC
ode":513928194},{"fileName":null,"class":"java.lang.StackTraceElement","lineNumb
er":-1,"className":"sun.reflect.NativeConstructorAccessorImpl","nativeMethod":fa
lse,"methodName":"newInstance","hCode":-432498851},{"fileName":null,"class":"jav
a.lang.StackTraceElement","lineNumber":-1,"className":"sun.reflect.DelegatingCon
structorAccessorImpl","nativeMethod":false,"methodName":"newInstance","hCode":-2
147429624},{"fileName":null,"class":"java.lang.StackTraceElement","lineNumber":-
1,"className":"java.lang.reflect.Constructor","nativeMethod":false,"methodName":
"newInstance","hCode":-1851634561},{"fileName":"DefaultDriverProvider.java","cla
ss":"java.lang.StackTraceElement","lineNumber":103,"className":"org.openqa.selen
ium.remote.server.DefaultDriverProvider","nativeMethod":false,"methodName":"call
Constructor","hCode":-2096353668},{"fileName":"DefaultDriverProvider.java","clas
s":"java.lang.StackTraceElement","lineNumber":97,"className":"org.openqa.seleniu
m.remote.server.DefaultDriverProvider","nativeMethod":false,"methodName":"newIns
tance","hCode":1201680335},{"fileName":"DefaultDriverFactory.java","class":"java
.lang.StackTraceElement","lineNumber":60,"className":"org.openqa.selenium.remote
.server.DefaultDriverFactory","nativeMethod":false,"methodName":"newInstance","h
Code":-1365021416},{"fileName":"DefaultSession.java","class":"java.lang.StackTra
ceElement","lineNumber":222,"className":"org.openqa.selenium.remote.server.Defau
ltSession$BrowserCreator","nativeMethod":false,"methodName":"call","hCode":20561
68471},{"fileName":"DefaultSession.java","class":"java.lang.StackTraceElement","
lineNumber":1,"className":"org.openqa.selenium.remote.server.DefaultSession$Brow
serCreator","nativeMethod":false,"methodName":"call","hCode":2056168250},{"fileN
ame":null,"class":"java.lang.StackTraceElement","lineNumber":-1,"className":"jav
a.util.concurrent.FutureTask","nativeMethod":false,"methodName":"run","hCode":42
4519275},{"fileName":"DefaultSession.java","class":"java.lang.StackTraceElement"
,"lineNumber":176,"className":"org.openqa.selenium.remote.server.DefaultSession$
1","nativeMethod":false,"methodName":"run","hCode":-255143467},{"fileName":null,
"class":"java.lang.StackTraceElement","lineNumber":-1,"className":"java.util.con
current.ThreadPoolExecutor","nativeMethod":false,"methodName":"runWorker","hCode
":-1208971944},{"fileName":null,"class":"java.lang.StackTraceElement","lineNumbe
r":-1,"className":"java.util.concurrent.ThreadPoolExecutor$Worker","nativeMethod
":false,"methodName":"run","hCode":-166011880},{"fileName":null,"class":"java.la
ng.StackTraceElement","lineNumber":-1,"className":"java.lang.Thread","nativeMeth
od":false,"methodName":"run","hCode":1432591020}],"screen":null}
      at C:\Users\Administrator\AppData\Roaming\npm\node_modules\mocha\lib\runna
ble.js:363:23
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by yaniswang** [comment]
IEDriver所在的路径有没有添加到环境变量PATH中？

**Comment by guozhen168** [comment]
服务执行命令改为：
set varI=%CD%\IEDriver
set PATH=%PATH%;%varI%;
java -jar selenium-server-standalone-2.53.1.jar -Dwebdriver.ie.driver=IEDriverServer.exe

也不行

**Comment by yaniswang** [comment]
系统的配置里，将路径加到PATH中

![image](https://cloud.githubusercontent.com/assets/970390/18296197/53761486-74da-11e6-9c77-342afb2a4a35.png)

**Comment by guozhen168** [comment]
这个也加过，结果一样

**Comment by yaniswang** [comment]
别的浏览器都正常，就IE 8有问题吗？

**Comment by guozhen168** [comment]
是的，为了方便调试，我本地ie版本只有ie8而已

**Comment by yaniswang** [comment]
WebDriver的部署你网上再找找文档，从你的信息中，我也没办法判断出原因。
