### ISSUE TITLE
如何利用uirecorder测试移动端页面？

### ISSUE THREAD

**Issue by sadk** [alibaba/uirecorder#110]
能否利用uirecorder 录制 android系统下的chrome 运行过程？

**Comment by yaniswang** [comment]
webview里的页面目前没办法录制，不过你可以把它当作pc网站来录制，前提是你的m站页面能支持click事件

**Comment by ZhuangWeiMian** [comment]
请问现在支持了吗？测试的时候需要webview页面去调用客户端的方法，没办法当作pc网站来录制

**Comment by ZhuangWeiMian** [comment]
> webview里的页面目前没办法录制，不过你可以把它当作pc网站来录制，前提是你的m站页面能支持click事件
请问现在支持了吗？测试的时候需要webview页面去调用客户端的方法，没办法当作pc网站来录制

**Comment by ZhuangWeiMian** [comment]
请问现在支持了吗？测试的时候需要webview页面去调用客户端的方法，没办法当作pc网站来录制@yaniswang
