### ISSUE TITLE
如何录制手机屏幕上的操作的动作

### ISSUE THREAD

**Issue by itoolx** [alibaba/uirecorder#111]
目前支持在手机端操作之后的动作的录制功能么？

**Comment by yaniswang** [comment]
就是说不依赖app的录制？我们做自动化，都是为了在执行机环境也能自动化的运行。
如果不依赖app，如何在执行机上跑起来？

**Comment by itoolx** [comment]
依赖和不依赖app到不是想问的重点，目前不知道uirecorder能不能进行手在手机上的操作也会记录下来，然后能回放

目前能看到的uirecorder 能录制在浏览器中操作手机app的步骤，但直接操作手机的动作，好像没有被记录，状态好像也没有同步

**Comment by yaniswang** [comment]
原理上目前没办法在手机端录制，手机端录制就要侵入手机了，要实现android和ios全平台兼容，就非常困难了

**Comment by itoolx** [comment]
日志什么的非入侵手机的方式也不可行么？

比如点击某个地方之后，应该会在手机端产生一些日志，这种方式有尝试过么？

**Comment by yaniswang** [comment]
关键是，在PC来操作，目前这种模式有什么缺陷吗？

**Comment by itoolx** [comment]
手机比较直观，并且手势丰富

**Comment by yaniswang** [comment]
目前只能在PC端录制，没办法实现在手机上录制。

**Comment by itoolx** [comment]
好的，了解了
