### ISSUE TITLE
希望支持自动探测已安装的谷歌浏览器并安装对应版本的chromedriver

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#112]
目前UI Recorder安装的chromedriver版本好像是固定的，而某个版本的chromedriver只支持指定的几个谷歌浏览器版本。正好新版chrome的安装会自动覆盖旧版，因此我们为了使用UI Recorder而不得不更换自己电脑上一直在使用的谷歌浏览器。

**希望UI Recorder能够支持自动探测已安装的谷歌浏览器并安装对应版本的chromedriver**，让用户能够使用现有的谷歌浏览器，无痛入手。

**Comment by yaniswang** [comment]
这个可能有点难度，目前我们只能通过不断的升级uirecorder的依赖来解决这个问题。

然后通过uirecorder的提示升级，来解决随时保持最新版的问题。

**Comment by stevobm** [comment]
如果目前不能做自动识别，能不能提供某种方法，能够安装兼容指定浏览器版本的chromdriver呢？毕竟一直换浏览器也挺麻烦的。

**Comment by yaniswang** [comment]
你目前碰到的情况是什么？chrome浏览器一般情况都会自动更新的啊

**Comment by stevobm** [comment]
我们没有VPN，chrome无法自动升级，所以大家各自浏览器版本也都不同。

**Comment by yaniswang** [comment]
这个我考虑下，如何支持可以选择chromedriver的版本

**Comment by xudafeng** [comment]
@yaniswang 用这个模块https://github.com/macacajs/macaca-chromedriver#custom-binaries-url

方便统一维护

**Comment by yaniswang** [comment]
@stevobm 

实际上chromedriver官方组件也支持这个功能

`CHROMEDRIVER_VERSION=2.28 npm i uirecorder -g`

这样就可以安装自己指定的版本了

**Comment by xudafeng** [comment]
@yaniswang 那是我们给加的，建议切换的macaca的版本，方便维护

**Comment by stevobm** [comment]
你好，我安装了macaca-chromedriver，但是准备指定Chrome版本的时候，发现这条命令貌似无法在CMD下执行：
CHROMEDRIVER_VERSION=2.25 npm i macaca-chromedriver -g
执行后提示：“'CHROMEDRIVER_VERSION' 不是内部或外部命令，也不是可运行的程序
或批处理文件。”
请问需要怎么改一下才可以呢？或者说，目前这个工具是否支持Windows命令行环境？

**Comment by stevobm** [comment]
我在Windows环境下，上面那个命令行用不了，不过我用下面的命令行升级成功了：
npm i uirecorder -g --chromedriver_version=2.25
——仍旧表示感谢！O(∩_∩)O~

**Comment by yaniswang** [comment]
windows下，要用set CHROMEDRIVER_VERSION=2.28

**Comment by stevobm** [comment]
我发现npm i uirecorder -g --chromedriver_version=2.25这种方法只能控制录制时候的Chrome版本，不能控制run.bat启动用到的Chromedriver。请问如何指定run.bat的那个chromedriver的版本呢？

**Comment by Cayla-Xiong** [comment]
我的Chrome版本号是79.0.3945.88，ChromeDriver版本号是79.0.3945.36，但是在使用UI Recorder执行录制命令:uirecorder  start，提示我
Chrome init failed!
session not created: This version of ChromeDriver only supports Chrome version 77
  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Mac OS X 10.14.6 x86_64)
Chrome init failed!
{ Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) code: 'ECONNRESET' }
