### ISSUE TITLE
希望支持在录制过程中对测试步骤的显示与管理

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#113]
目前的测试用例是在结束录制后一次性生成的，中间有些误操作被录制进去了，没有办法在第一时间调整（比如删除），感觉有些不方便。

希望UI Recorder能够提供一个界面，**在录制过程中显示录制步骤并且支持对录制步骤的管理（比如修改、删除、调整顺序等等）**，这样就不用等到录制完之后再去调整，变得非常好用了。

**Comment by yaniswang** [comment]
这个功能就需要依赖开发一个gui界面了，将来可以考虑，短期暂时没有资源

**Comment by stevobm** [comment]
好的，依旧表示期待。。
