### ISSUE TITLE
使用firefox执行录制脚本报错

### ISSUE THREAD

**Issue by loginXin** [alibaba/uirecorder#114]
uirecorder版本：2.5.5
nodejs版本：8.0.0
selenium-server：3.3.1
geckodriver和firefox都是最新的版本，录制脚本部分如下：
`    it('url: http://www.baidu.com', async function(){
        await driver.url(_(`http://www.baidu.com`));
    });

    it('waitBody: ', async function(){
        await driver.sleep(500).wait('body', 30000).html().then(function(code){
            isPageError(code).should.be.false;
        });
    });

    it('sendKeys: ui recorder', async function(){
        await driver.sendKeys('ui recorder');`

报错内容：
![image](https://user-images.githubusercontent.com/29697328/27523357-3cb7d066-5a5f-11e7-898d-c0f15556cb47.png)
selenium-sever：
![image](https://user-images.githubusercontent.com/29697328/27523390-7a662d86-5a5f-11e7-8adc-5d51b7691fcb.png)
看起来是脚本不兼容firefox？

**Comment by Molunerfinn** [comment]
+1，同样的情况，chrome可以，firefox进行不下去就报错了

**Comment by zhugehui9527** [comment]
录制回放的时候，可以选择Firefox 之类的浏览器，我想问，录制的时候能选择Firefox或者ie么？在使用chrome浏览器录制的时候，有些情况无法录制，比如选择弹窗，输入框在选择某一个值会出现弹窗进行选择填充，但是chrome并不支持，这个时候能换成Firefox进行录制么？

**Comment by yaniswang** [comment]
geckodriver问题还非常多，不建议使用。
目前我们这边还是在使用旧版的驱动，旧版驱动最新只支持v46.0

**Comment by suuzee** [comment]
@yaniswang 旧版驱动是指哪一版呢?
