### ISSUE TITLE
Bug：UI Recorder 在模态框打开情况下所有输入框都无法输入

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#115]
示例网址：http://v3.bootcss.com/javascript/#modals

问题描述：当打开该页面中的模态框示例时，uirecorder的所有悬浮窗口（包括工具栏、断言对话框等）中的输入框都无法进行输入。

目前只在UI Recorder2.4.6中发现，最新的2.5系列还未测试。

**Comment by yaniswang** [comment]
应该都有这个问题，问题出在页面里所有的js事件，都被网页自己的逻辑屏蔽了，对于这种场景，目前暂时还没想到解决方案。

关键还是要找到一个方法监听更底层的事件，绕开网页自己的屏蔽

**Comment by yaniswang** [comment]
我打开你的网址，测试了下录制，并没有出现你说的无法输入的问题。

我要怎么重现？

**Comment by stevobm** [comment]
首先，点击页面按钮，如图所示：
![20170628185225](https://user-images.githubusercontent.com/5198256/27675319-1667676c-5cdc-11e7-9a65-b6a972ff7c86.jpg)
点击后模态框弹出，此时添加断言，发现输入框的内容都无法修改，如图所示：
![20170628185135](https://user-images.githubusercontent.com/5198256/27675324-1bd23a6a-5cdc-11e7-86aa-359ece584a1f.jpg)

**Comment by yaniswang** [comment]
重现了，这个问题暂时无解了……

焦点被页面里的逻辑强制抢走了

**Comment by yaniswang** [comment]
这个问题暂时无力回天了，技术上解决不了

**Comment by stevobm** [comment]
由于项目里面很多模态框都无法正常进行断言等操作，目前测试受到这个bug的影响较为严重。

不过我最近分析了一下这个问题，原因已经定位了——是由于bootstrap模态框的tabindex属性导致的。临时方案是在打开模态框之前先执行js，清除所有模态框的tabindex属性，保证uirecorder的断言可以正常使用。

希望uirecorder可以参考此方案对进行完善。
