### ISSUE TITLE
After jumping to the specific url, the recorder doesn't capture user operations

### ISSUE THREAD

**Issue by CXHtml** [alibaba/uirecorder#116]
### Version

 v2.5.11

### Steps to reproduce

Everything is fine in the checker browser when I was recording my operations until I 

- click the _Jump to_ button
- enter the url and click ok
- After the new page loaded, when you do some operations,  the recorder didn't capture any of them (which means the checker browser doesn't sync with the recorder browser and no error hints occur).

### What is expected?

After jump to another page, the recorder should capture user operations as usual, and the final generated assertions should not stop at the moment the page jump to the specific url.

### What is actually happening?

The recorder doesn't work and checker browser doesn't sync with the recorder browser

**Comment by CXHtml** [comment]
I found that if you use _Add Hover_ or _Add sleep_ for several seconds or any tool button below, the recorder is back to normal. Like each time When I jump to a url, I need to add sleep for a while...

um~ this is so verbose. Is there any explanation why this happens? or is it a bug ?

**Comment by yaniswang** [comment]
我试了下，跳转后，还是正常的啊。

你跳转的目标地址是什么？

**Comment by CXHtml** [comment]
嗯，我发现是因为我这个是单页应用网站，内部的url经过路由的跳转之后，脚本貌似录制不了

**Comment by yaniswang** [comment]
url地址发出来看下，你jump前和jump后的url分别是什么？

**Comment by CXHtml** [comment]
c.163.com, 需要用网易邮箱帐号登录下进入后台
jump 前 url: https://c.163.com/dashboard#/m/overview/
jump 后 url: https://c.163.com/dashboard#/m/win/

**Comment by yaniswang** [comment]
jump命令后，校验浏览器的url有变化吗？

**Comment by CXHtml** [comment]
有的，和录制浏览器保持一致，但之后校验浏览器就不同步了，手动添加 sleep 后就又恢复正常

**Comment by yaniswang** [comment]
你试试从www.baidu.com跳转到www.taobao.com
看看能不能重现？

**Comment by CXHtml** [comment]
这个我试过，不能重现我的问题

**Comment by yaniswang** [comment]
你有测试账号吗？我用你的场景测试下

**Comment by CXHtml** [comment]
直接用网易邮箱就可以登录进入我提到的场景

**Comment by yaniswang** [comment]
升级下2.5.12版本，已经修复了这个问题

**Comment by yaniswang** [comment]
结果怎么样？问题修复了吗？

**Comment by CXHtml** [comment]
Good~ 已经修复
