### ISSUE TITLE
添加travis ci

### ISSUE THREAD

**Issue by xudafeng** [alibaba/uirecorder#118]
cli命令行的基本功能保证100%可用

参考 https://github.com/macacajs/macaca-cli/blob/master/test/macaca-cli.test.js

**Comment by yaniswang** [comment]
uirecorder的命令行功能很简单，感觉没测试的意义，从之前的问题来看，这方面从来没出现过

**Comment by xudafeng** [comment]
@yaniswang ci是有必要的，再简单的东西也需要回归覆盖啊
