### ISSUE TITLE
Errors occur when expecting the value after js eval in async mode

### ISSUE THREAD

**Issue by CXHtml** [alibaba/uirecorder#119]
### Version

 v2.5.15

### Steps to reproduce

1. `Add Expect`, select type `jscode`
2. async mode:

        function(done){
            setTimeout(function(){
                done(123);
            }, 100);
        }

It does work in recording the scripts, but fails in running stage.
### What is expected?

Should work as normal when running the test

### What is actually happening?

![image](https://user-images.githubusercontent.com/6263570/28002572-00dce526-6569-11e7-842a-8a427dc100fa.png)

**Comment by yaniswang** [comment]
我用你的代码测试了下，结果正确的

![image](https://user-images.githubusercontent.com/970390/28568322-fca82b40-7167-11e7-970d-c8d91fca0f46.png)

UIRecordr v2.5.19版本

**Comment by CXHtml** [comment]
升级到 v2.5.19 还是会报同样的错误：
跑录制好的脚本时报的错
![image](https://user-images.githubusercontent.com/6263570/28570216-cd18fda2-716f-11e7-94d2-ead43043309d.png)

**Comment by yaniswang** [comment]
`cnpm i uirecorder@beta -g`

试试安装这个版本，然后重新录一下。

**Comment by CXHtml** [comment]
这个是没问题的，是什么原因？

**Comment by yaniswang** [comment]
chromedriver默认的异步超时是0秒，导致无法使用异步模式

![image](https://user-images.githubusercontent.com/970390/28571069-b2415d18-7173-11e7-84e6-3fc22dd3245d.png)
