### ISSUE TITLE
运行 test.spec.js报错

### ISSUE THREAD

**Issue by Gebiuncle** [alibaba/uirecorder#12]
运行 mocha test.spec.js 报错

test.spec : chrome       before
C:\Users\Smart>mocha test.spec.js

  test.spec : chrome
    1) "before all" hook

  test.spec : ie 11
    2) "before all" hook

  0 passing (42s)
  2 failing

  1) test.spec : chrome "before all" hook:
     Error: connect ETIMEDOUT 123.57.55.5:4444
      at Object.exports._errnoException (util.js:873:11)
      at exports._exceptionWithHostPort (util.js:896:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

  2) test.spec : ie 11 "before all" hook:
     Error: connect ETIMEDOUT 123.57.55.5:4444
      at Object.exports._errnoException (util.js:873:11)
      at exports._exceptionWithHostPort (util.js:896:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by yaniswang** [comment]
你的WebDriver Server没正确部署啊

https://github.com/alibaba/uirecorder#how-to-deploy-webdriver-server

**Comment by angel8899421110** [comment]
ok 我去试试 不过之前的文档里确实是没有这块说明的

**Comment by yaniswang** [comment]
但是初始化的时候，已经提示输入webdriver域名或IP

**Comment by Gebiuncle** [comment]
WebDriver Server部署的时候怎么操作，  Run selenium server: java -jar selenium-server-standalone-x.xx.x.jar   这个操作完接下来怎么搞

**Comment by yaniswang** [comment]
然后你本地就在127.0.0.1 4444这位端口上开了WebDriver服务

**Comment by yyl2016** [comment]
@yaniswang 你好，部署了selenium server后，执行.js文件还是出现最开始的问题--连接超时，是什么问题啊，是否可以给出一个部署文档啊？

**Comment by yaniswang** [comment]
连接就是为了连上WebDriver，既然你连接超时，那就说明WebDriver没部署好
