### ISSUE TITLE
启动uirecorder报错：Internal Server Error

### ISSUE THREAD

**Issue by wuxisanhuo** [alibaba/uirecorder#121]
![image](https://user-images.githubusercontent.com/30311698/28406186-10ee5ebc-6d62-11e7-98ed-a67d72ecced1.png)

![image](https://user-images.githubusercontent.com/30311698/28411129-726c4e5a-6d72-11e7-9e6c-eb06ff557908.png)

macaca报错

![image](https://user-images.githubusercontent.com/30311698/28406199-19c2564c-6d62-11e7-9b00-4b8a62d0d508.png)

页面

**Comment by yaniswang** [comment]
类似这样的问题，一般情况都是macaca层面的问题
