### ISSUE TITLE
关于使用代理时uirecorder init无法联网的问题

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#124]
由于公司网络安全的原因，所有应用需要使用代理才能联网。

npm可以通过设置代理正常安装nodejs包，但是通过npm安装完cnpm后，cnpm却无法安装uirecorder。如果直接用npm装uirecorder，没问题，但是装完uirecorder再执行uirecorder init时，又出现无法下载的情况。

希望uirecorder init的时候可以支持指定http代理。

**Comment by yaniswang** [comment]
目前uirecorder init强行指定是从淘宝的源安装的，因为这样安装更快，而且不会被墙。

你们公司这种用代理才能上网，太奇葩了……

用nat上网，就没办法控制安全了？

**Comment by stevobm** [comment]
呵呵，代理这个事情我也没有办法。uirecorder之前用默认源的时候也是这样，与源本身没啥关系。
只不过作为自动化测试工具，一般都是在公司用，而公司用代理来管控上网行为的，其实并不在少数（Intel等公司也是这样）。希望可以考虑支持一下代理支持，不然我只能在家里玩啦，有些无奈～

**Comment by yaniswang** [comment]
https://www.npmjs.com/package/npminstall

我们用的是这个组件进行安装依赖，看了下，这个组件本身并不支持proxy功能。

或者uirecorder init实在不行，就只负责目录的初始化，依赖的安装，你自己另外执行cnpm install来完成吧。

**Comment by yaniswang** [comment]
我找npminstall的作者问问看，看看能否让npminstall直接复用npm的proxy参数

**Comment by stevobm** [comment]
uirecorder init报的错其实就是代理用不了的症状，具体内容如下：
```
\ [0/7] Installing selenium-standalone@6.x.x[npminstall:get] retry GET https://r
egistry.npm.taobao.org/chai/3.5.0 after 100ms, retry left 4, error: RequestError
: connect ETIMEDOUT 114.55.80.225:443 (req "error"), GET https://registry.npm.ta
obao.org/chai/3.5.0 -1 (connected: false, keepalive socket: false, agent status:
 {"createSocketCount":7,"createSocketErrorCount":0,"closeSocketCount":0,"errorSo
cketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":
{"registry.npm.taobao.org:443:::::::::":7},"requests":{}})
headers: {}
```
另外，cnpm好像也是一样的问题，报错内容如下：
```
Get /binary-mirror-config/latest from http://registry.npm.taobao.org error: Conn
ectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/b
inary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent
status: {"createSocketCount":3,"createSocketErrorCount":0,"closeSocketCount":3,"
errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"so
ckets":{},"requests":{}})
headers: {}
    at Timeout._onTimeout (C:\Users\vo\AppData\Roaming\npm\node_modules\cnpm\nod
e_modules\urllib\lib\urllib.js:720:15)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```
也是需要支持代理，看能顺便反馈一下不？

**Comment by stevobm** [comment]
如果上游能够解决，那就更好了O(∩_∩)O~

**Comment by fengmk2** [comment]
urllib 还在 wip 中 https://github.com/node-modules/urllib/pull/226

**Comment by yaniswang** [comment]
v2.5.23已经支持自动从cnpm读取proxy参数了，试试

@stevobm

**Comment by yaniswang** [comment]
@stevobm  有空测试下

**Comment by stevobm** [comment]
uirecorder更新了2.5.23，cnpm也设置了proxy代理，但是还是提示超时。

**Comment by yaniswang** [comment]
cnpm也更新下试试

**Comment by yaniswang** [comment]
uirecorder init的日志发出来看下

**Comment by stevobm** [comment]
cnpm更新到了5.1.1，但是cnpm设置proxy代理后好像无法下载包。用npm则是正常的。

**Comment by stevobm** [comment]
目前的情况是，cnpm更新到了5.1.1，设置代理后可以下载包，但会卡很久，直接用npm则很快下完。uirecorder init报超时。

**Comment by yaniswang** [comment]
cnpm config get proxy

看看返回内容是什么

**Comment by stevobm** [comment]
返回的是我设置的代理。这个没有问题的。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanis Wang <notifications@github.com>
发送时间: 2017年8月9日 09:36
收件人: alibaba/uirecorder <uirecorder@noreply.github.com>
抄送: stevobm <stevobm@outlook.com>, Mention <mention@noreply.github.com>
主题: 回复：[alibaba/uirecorder] 关于使用代理时uirecorder init无法联网的问题 (#124)


cnpm config get proxy

看看返回内容是什么

**Comment by yaniswang** [comment]
你的代理格式正确吗？是http://x.x.x.x:1080 类似这样的格式吗？

**Comment by stevobm** [comment]
是的，npm也是一样的代理，可以用。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanis Wang <notifications@github.com>
发送时间: 2017年8月9日 09:46
收件人: alibaba/uirecorder <uirecorder@noreply.github.com>
抄送: stevobm <stevobm@outlook.com>, Mention <mention@noreply.github.com>
主题: 回复：[alibaba/uirecorder] 关于使用代理时uirecorder init无法联网的问题 (#124)


你的代理格式正确吗？是http://x.x.x.x:1080 类似这样的格式吗？

**Comment by yaniswang** [comment]
cnpm的错误日志发出来看下

**Comment by stevobm** [comment]
经最新测试发现，可能是我这边环境不太稳定，cnpm下载是正常的，偶尔会卡住比较久。但是uirecorder init始终是报超时，内容如下：(前后省略)
```
Start install project dependencies...
--------------------------------------------

\ [0/7] Installing selenium-standalone@6.x.x[npminstall:get] retry GET https://r
egistry.npm.taobao.org/selenium-standalone after 100ms, retry left 4, error: Req
uestError: connect ETIMEDOUT 114.55.80.225:443 (req "error"), GET https://regist
ry.npm.taobao.org/selenium-standalone -1 (connected: false, keepalive socket: fa
lse, agent status: {"createSocketCount":7,"createSocketErrorCount":0,"closeSocke
tCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSock
ets":{},"sockets":{"registry.npm.taobao.org:443:::::::::":7},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/mochawesome-uirecorde
r after 100ms, retry left 4, error: RequestError: connect ETIMEDOUT 114.55.80.22
5:443 (req "error"), GET https://registry.npm.taobao.org/mochawesome-uirecorder
-1 (connected: false, keepalive socket: false, agent status: {"createSocketCount
":7,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeou
tSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taoba
o.org:443:::::::::":7},"requests":{}})
headers: {}
```

**Comment by yaniswang** [comment]
你的uirecorder更新到最新版了吗？

如果正常的话，应该会显示这样：

![image](https://user-images.githubusercontent.com/970390/29112644-13607f62-7d21-11e7-9d78-7cdaa56bfca3.png)

会从cnpm中读取proxy配置，然后显示：`Find proxy from cnpm: http://127.0.0.1:2080/`

从你的日志上来看，没有这句话，要么是你的uirecorder是旧版本，要么cnpm没有配置代理

**Comment by stevobm** [comment]
感觉很奇怪，cnpm config get proxy 得到的是正确的代理，格式也没错，同时uirecorder init显示出来的版本号是2.5.23，但是没有出现那句“Find proxy from cnpm”。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanis Wang <notifications@github.com>
发送时间: 2017年8月9日 16:38
收件人: alibaba/uirecorder <uirecorder@noreply.github.com>
抄送: stevobm <stevobm@outlook.com>, Mention <mention@noreply.github.com>
主题: 回复：[alibaba/uirecorder] 关于使用代理时uirecorder init无法联网的问题 (#124)


你的uirecorder更新到最新版了吗？

如果正常的话，应该会显示这样：

[image]<https://user-images.githubusercontent.com/970390/29112644-13607f62-7d21-11e7-9d78-7cdaa56bfca3.png>

会从cnpm中读取proxy配置，然后显示：Find proxy from cnpm: http://127.0.0.1:2080/

从你的日志上来看，没有这句话，要么是你的uirecorder是旧版本，要么cnpm没有配置代理

**Comment by yaniswang** [comment]
cnpm config get proxy这个命令你截个图我看下

**Comment by stevobm** [comment]
![20170811090854](https://user-images.githubusercontent.com/5198256/29199885-2b89aef2-7e83-11e7-9ae6-c1b1e48ac175.jpg)

**Comment by yaniswang** [comment]
你把:80后面的斜杠去掉试试，这个是proxy的地址，并不是URL

**Comment by yaniswang** [comment]
我在windows下重现出来了，的确没读到cnpm的配置，我今天解决下。

**Comment by yaniswang** [comment]
问题已经修复了，你安装下v2.5.25版本，应该可以了.
windows下面也测试过了。

**Comment by stevobm** [comment]
验证通过，OK了。O(∩_∩)O

**Comment by yaniswang** [comment]
好的，那我close掉了

**Comment by stevobm** [comment]
又碰到一个问题了，Windows下的，麻烦看一下：
![error](https://user-images.githubusercontent.com/5198256/32713850-08118a1a-c886-11e7-9c38-7c54948ea0a9.png)

**Comment by yaniswang** [comment]
从错误信息上来看，是网络方面的问题，`114.55.80.225:443`无法连接

你自己排查下，看看是什么原因引起的。

**Comment by stevobm** [comment]
114.55.80.225:443当前确实无法访问，即便是在手机上也是。

**Comment by stevobm** [comment]
换了几个代理都不行，手机上也始终访问不了，应该不是我这边的网络问题。晚上回家再试一下。

**Comment by stevobm** [comment]
虽然家里直接访问114.55.80.225:443也不可以，但是执行uirecorder init没问题。看来应该还是被这边的网络屏蔽了，原因比较隐蔽，不好排查。

目前方案只能是做成离线压缩包部署。

**Comment by yaniswang** [comment]
uirecorder init是强行指定了访问cnpm的国内源
