### ISSUE TITLE
希望uirecorder可以完善对拖拽操作的支持

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#125]
最近使用uirecorder时，发现其对部分网页控件的拖拽支持不太好。例如：

1. 对高德地图(http://ditu.amap.com/) 进行拖拽时操作时，会出现“稍微拖一下会甩出很远”的问题；
2. 对gojs流程图(http://gojs.net/latest/samples/stateChart.html) 进行拖拽时，录制正常，但同步浏览器无法同步回放操作；
3. 对百度地图(http://map.baidu.com/) 进行拖拽操作时，所有拖拽操作都会录制成点击操作，同样无法正常回放。

我们自己在录制用例过程中中也出现了类似的拖拽异常问题，希望uirecorder可以完善拖拽功能，适用于更多测试场景。

注：测试版本 uirecorder2.4.6

**Comment by yaniswang** [comment]
v2.5.21修复了个issue，现在可以支持百度地图了

但是高德地图由于有加速度，而我们录制时并没有考虑时间因素，因此，对高德地图来讲，我们的拖拽都是瞬间完成的，所以就会导致回放的时候甩出很远。对于这个问题，好像没有什么好的解决方案。

对于gojs流程图，我看录制出来的脚本是正确的，但是比较奇怪gojs组件并没有正确响应拖拽操作，有可能中间少了一些步骤，或者也可能是时间因素上的原因。

**Comment by stevobm** [comment]
顺便补充几个，一起分析一下：
zrender(http://ecomfe.github.io/zrender/doc/example/demo.html) 的问题与gojs类似，Qunee(http://demo.qunee.com/#Hello Qunee) 会出现mouseup录制漏掉，jsplumb(https://jsplumbtoolkit.com/) 会出现拖拽位置出现略微偏差，录制几步之后“跟不上”了的问题。

**Comment by stevobm** [comment]
对于高德那个问题，我感觉某些操作是不是可以保留一下用户操作的时间间隔(比如拖拽的mousedown到mouseup的时间)。比如提供一个选项，用户勾选之后就会记录操作间隔。因为用户的某些操作的时间间隔是有意义的（比如某些元素要特效完成后才能点击到），如果间隔没有记录，可能会导致无法正常回放。

**Comment by yaniswang** [comment]
2.5.22修复了一个重要bug，现在这个场景的拖动已经没有问题了：https://jsplumbtoolkit.com/

至于上面大部分场景，有几种情况暂时没办法兼容：

1. 事件被页面吃掉的，就没办法实现录制
2. 触发事件条件比较复杂的，暂时也不会去兼容

我们眼下还是解决主流场景为主，不太可能真做到完美的拖动录制，以真实案例驱动，来一个解决一个。

**Comment by yaniswang** [comment]
@stevobm 你现在公司的拖动场景已经可以支持了吗？你是哪个公司的？

**Comment by stevobm** [comment]
我们之前的拓扑图是基于jtopo的（有不少，需要测试），现在准备逐渐过渡到cytoscape（这个倒是没有问题）。如果可以的话，可以看看jtopo那个的问题。

**Comment by yaniswang** [comment]
jtopo这个可能会比较麻烦，因为是canvas整体进行坐标定位的，坐标稍微有点偏移，就无法操作了。

**Comment by stevobm** [comment]
cytoscape也是基于canvas的，但是却支持得不错。我感觉应该是jtopo的事件机制做得不太规范。如果觉得支持有些麻烦的话就先放着吧，先考虑那些更有价值的功能。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanis Wang <notifications@github.com>
发送时间: 2017年7月31日 11:34
收件人: alibaba/uirecorder <uirecorder@noreply.github.com>
抄送: stevobm <stevobm@outlook.com>, Mention <mention@noreply.github.com>
主题: 回复：[alibaba/uirecorder] 希望uirecorder可以完善对拖拽操作的支持 (#125)


jtopo这个可能会比较麻烦，因为是canvas整体进行坐标定位的，坐标稍微有点偏移，就无法操作了。
