### ISSUE TITLE
Uirecorder对多重frame的元素貌似定位不到

### ISSUE THREAD

**Issue by Invoker2** [alibaba/uirecorder#126]
比如嵌套了两层iframe， 可以定位第一重元素， 但是定位第二重frame里面的元素无法定位到， 用rf可以定位到的

**Comment by yaniswang** [comment]
是的，暂时不会支持多层iframe嵌套，目前只支持一层iframe嵌套。

从目前的场景比例来看，多层iframe嵌套的场景还是非常少的。

如果要支持多层嵌套的话，整个录制框架要进行大规模的重构，成本太高，所以一直没有做这个事。

**Comment by Invoker2** [comment]
很不幸， 我们的产品很多多层frame的场景，那我还是用rf吧。

**Comment by yaniswang** [comment]
rf是什么？

**Comment by Invoker2** [comment]
robotframework

**Comment by wenzhaoxian** [comment]
目前还是没有支撑多层iframe嵌入吧？
