### ISSUE TITLE
关于百度搜索列表页面，无法断言的问题

### ISSUE THREAD

**Issue by guchenhui** [alibaba/uirecorder#127]
输入“baidu.com”
随便输入搜索内容
点击“搜索”

然后这个页面里面怎么断言都不能成功

**Comment by yaniswang** [comment]
![image](https://user-images.githubusercontent.com/970390/29008899-9b21d5e0-7b50-11e7-9bb1-eb2d32a87e29.png)

我试了下，可以断言啊，百度是我开发过程中测试最多的一个站点，不太可能不兼容的。

你的录制日志发出来看下。

**Comment by guchenhui** [comment]
__  ______   ____                           __         
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /    
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.22

Official Site: http://uirecorder.com
------------------------------------------------------------------

? 测试脚本文件名: sample/test.spec.js
? 文件已存在，加载并继续录制吗？ (y/N) ? 文件已存在，加载并继续录制吗？ (y/N) n? 文件已存在，加载并继续录制吗？ No
? 打开同步校验浏览器？ (Y/n) ? 打开同步校验浏览器？ (Y/n) y? 打开同步校验浏览器？ Yes
? 浏览器大小 (格式：1024 x 768): (maximize) ? 浏览器大小 (格式：1024 x 768): maximize

录制服务器监听在端口: 9765
校验浏览器已开启

------------------------------------------------------------------

录制浏览器已开启
  url: http://baidu.com
   √ 执行成功
  waitBody: 
   √ 执行成功
  click: wd ( div[id="wrapper"]:nth-child(4) > div[id="head"]:nth-child(1) > div.head_wrapper > div.s_form > div.s_form_wrapper > form[id="form"][name="f"].fm > span.s_ipt_wr > input[id="kw"][name="wd"].s_ipt, 61, 11, 0 )
   × 执行失败 Wait element displayed timeout: div[id="wrapper"]:nth-child(4) > div[id="head"]:nth-child(1) > div.head_wrapper > div.s_form > div.s_form_wrapper > form[id="form"][name="f"].fm > span.s_ipt_wr > input[id="kw"][name="wd"].s_ipt ,10000ms
  sendKeys: 五月天
   √ 执行成功
  click: 百度一下 ( div[id="wrapper"]:nth-child(4) > div[id="head"]:nth-child(1) > div.head_wrapper > div.s_form > div.s_form_wrapper > form[id="form"][name="f"].fm > span.s_btn_wr > input[id="su"][type="submit"].s_btn, 49, 13, 0 )
   × 执行失败 Wait element displayed timeout: div[id="wrapper"]:nth-child(4) > div[id="head"]:nth-child(1) > div.head_wrapper > div.s_form > div.s_form_wrapper > form[id="form"][name="f"].fm > span.s_btn_wr > input[id="su"][type="submit"].s_btn ,10000ms
  waitBody: 
   √ 执行成功
  expect: text, #con-ar div > div.cr-content > div.opr-recommends-merge-content > div.opr-recommends-merge-mbGap > div:nth-child(1) > div:nth-child(1) > div.c-gap-top-small > a, equal, 李健
   × 执行失败 Wait element displayed timeout: #con-ar div > div.cr-content > div.opr-recommends-merge-content > div.opr-recommends-merge-mbGap > div:nth-child(1) > div:nth-child(1) > div.c-gap-top-small > a ,10000ms

------------------------------------------------------------------

共录制7个步骤，其中校验通过: 4个，校验失败: 3个
录制脚本已保存: sample/test.spec.js

录制服务器已关闭
录制浏览器已关闭
校验浏览器已关闭

**Comment by yaniswang** [comment]
你的config.json截上图看下

**Comment by guchenhui** [comment]
![qq 20170807142409](https://user-images.githubusercontent.com/24437650/29014558-3162bb02-7b7c-11e7-8cfa-95949a8a3120.png)

**Comment by yaniswang** [comment]
你录出来的PATH严重有问题啊，怎么会是：wd ( div[id="wrapper"]:nth-child(4) > div[id="head"]:nth-child(1) > div.head_wrapper > div.s_form > div.s_form_wrapper > form[id="form"][name="f"].fm > span.s_ipt_wr > input[id="kw"][name="wd"].s_ipt

正确的应该是：#kw

**Comment by guchenhui** [comment]
我找到问题原因了，因为在输入url时，如果是https的网站，现在chrome都强制需要你打https，不然提示“您与此网站之间建立的连接不安全”，那这个时候，就会出现dom元素路径获取不正确。所以只要像百度的url加上https就好了

**Comment by yaniswang** [comment]
好的，那这个issue就关闭了
