### ISSUE TITLE
“校验浏览器”有几率跟“操作浏览器”不同步

### ISSUE THREAD

**Issue by guchenhui** [alibaba/uirecorder#128]
我试了一下，点击，滚屏都能很好的同步。唯独搜索，比较容易出现校验浏览器跟操作浏览器不同步的情况。我试了百度搜索，不同步的几率很大。

**Comment by yaniswang** [comment]
把不同步时的，错误日志发出来看下

**Comment by guchenhui** [comment]
找到问题原因了，是我搜狗狗输入法版本太低，更新到最新版本就没问题了

**Comment by yaniswang** [comment]
好的，解决了就好
