### ISSUE TITLE
页面元素只有class，没有Id和name定位元素失败

### ISSUE THREAD

**Issue by fuershuai** [alibaba/uirecorder#129]
div class="f-cb"
span class="ux-btn th-bk-main ux-btn- ux-btn- u-btn w100 f-fl createBtn"
    你好
    /span
span class="ux-btn-export-polling f-fl ml20 ux-center-course_export"
    
怎么定位“你好”，这个标签

**Comment by yaniswang** [comment]
uirecorder生成 的PATH是什么？无法定位吗？

**Comment by fuershuai** [comment]
![18](https://user-images.githubusercontent.com/8315683/29102050-0ec80606-7ce9-11e7-9823-48e4672a037f.png)

**Comment by fuershuai** [comment]
好奇怪，今天第一次录制时报这个错，但脚本回放时没有错但是没有执行，第二次又继续录制时在第一次基础上，竟然录制成功了，感觉比较奇怪，怀疑有些元素定位不稳定

**Comment by yaniswang** [comment]
a.f-fs14

这个14是不是脚本动态生成的？有没有可能每次都不一样？

**Comment by fuershuai** [comment]
这个是固定的，都一样的

**Comment by fuershuai** [comment]
![11](https://user-images.githubusercontent.com/8315683/29102299-b2077224-7cea-11e7-8790-cc5c2ebec2e6.png)
课程列表这个录制时报错了，但是回放时成功了，还有就是“自建课程”第一次失败，第二次成功，红框中的数字也不一样，是什么原因。

**Comment by yaniswang** [comment]
那个是相对坐标，一般情况下不会有影响的。

你这样，跑失败的时候，临时把脚本强制退出，然后在那个页面中，用那个PATH自己定位下，看能不能定位的到，如果定位不到，找找原因。

**Comment by fuershuai** [comment]
再请教下可以向录制好的脚本中添加断言和图片对比功能吗？如果可以，怎么添加呢，直接在录制脚本中添加还是在原来基础上继续录制

**Comment by yaniswang** [comment]
继续录制
