### ISSUE TITLE
录制脚本回访问题

### ISSUE THREAD

**Issue by angel8899421110** [alibaba/uirecorder#13]
录制脚本在chrome浏览器下，执行测试脚本分别在chrome 和ie8 但是ie8浏览器由于界面的收藏栏显示导致界面的单击事件位置错误，从而使脚本无法继续，是否有此类问题的解决方案

**Comment by yyl2016** [comment]
@angel8899421110 你好，你的可以执行.js文件吗？

**Comment by yaniswang** [comment]
那你在录制的时候，可以保持录制机和执行机在同一个屏幕范围内。
如果是后面几屏，建议鼠标可以片下多滚动一点，那样就不会出现找不到DOM的情况。
