### ISSUE TITLE
支持哪些浏览器?

### ISSUE THREAD

**Issue by pandalanlam** [alibaba/uirecorder#130]
问题如下:
1.uirecorder默认支持哪些浏览器?
2.能否通过未支持浏览器的webdriver配置到uirecorder内使用?如何配置?
3.uirecorder init时需要输入浏览器列表,可以输入哪些? 怎样的格式? 可否在文案中给出提示?

使用过后还是比selenium ide好用太多,点个赞

**Comment by yaniswang** [comment]
1. 支持所有webdriver协议有的浏览器，目前基本上就包括：chrome, firefox, ie系列
2. uirecorder仅仅是生成脚本，最终还是会把浏览器名称提交给selenium，或者selenium grid来执行，所以支持哪些浏览器，取决于selenium支持哪些
3. 浏览器名称，就是selenium中自己配置的名称，如果是使用的f2etest，那就是f2etest webdriver云上的名称

**Comment by pandalanlam** [comment]
明白了
