### ISSUE TITLE
建议uirecorder在录制无线APP的时候，不要直接根据app下载地址的后缀名做解析来判断是android还是ios包，因为有的下载地址是经过处理没有后缀名的

### ISSUE THREAD

**Issue by logan62334** [alibaba/uirecorder#132]

**Comment by yaniswang** [comment]
判断仅仅是辅助的，如果判断不出来，会要求用户自己选择一个操作系统。

**Comment by logan62334** [comment]
@yaniswang  目前的话判断不出来 会不停的清空要求用户重新输入app地址

**Comment by yaniswang** [comment]
不会吧，你输入的APP地址是什么样的？

**Comment by logan62334** [comment]
@yaniswang  嗯 对的 输入的是远程地址

**Comment by yaniswang** [comment]
目前的确是对扩展名进行了限制：
![image](https://user-images.githubusercontent.com/970390/29161794-281831f6-7dea-11e7-959c-c4cd03003139.png)

你们目前的URL格式是什么样的？

**Comment by logan62334** [comment]
@yaniswang  http://xxx/android_e52b4fff33a9c0421e064cf8dca36758-rewrite 是这样的

**Comment by yaniswang** [comment]
好的，我发个新版本，对于远程的URL就不限制扩展名了

**Comment by yaniswang** [comment]
v2.5.25已经取消了远程的扩展名限制。
