### ISSUE TITLE
多个测试脚本如何执行

### ISSUE THREAD

**Issue by dongyuhua** [alibaba/uirecorder#14]
我将多个测试脚本放到test文件夹下 执行`mocha` ，在第二个文件报错，如果只有一个测试脚本文件是正常的，请问如何处理，报错信息如下：

> D:\00test\01uirecorder\test\SY_002.js:48
>     browsers = browsers.replace(/^\s+|\s+$/g, '');
>                        ^
> 
> TypeError: Cannot read property 'replace' of undefined
>     at runThisSpec (D:\00test\01uirecorder\test\SY_002.js:48:24)
>     at Object.<anonymous> (D:\00test\01uirecorder\test\SY_002.js:32:5)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at C:\Users\Dongyuhua\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:220:27
>     at Array.forEach (native)
>     at Mocha.loadFiles (C:\Users\Dongyuhua\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:217:14)
>     at Mocha.run (C:\Users\Dongyuhua\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:485:10)
>     at Object.<anonymous> (C:\Users\Dongyuhua\AppData\Roaming\npm\node_modules\mocha\bin_mocha:403:18)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Function.Module.runMain (module.js:467:10)
>     at startup (node.js:136:18)

**Comment by yyl2016** [comment]
@dongyuhua 你好，你是怎么配置的，然后就可以执行.js文件了，我自测的时候是好的，执行生成的脚本文件，就总报连接超时。

**Comment by dongyuhua** [comment]
@yyl2016  你的webdriver启动了么？

**Comment by yyl2016** [comment]
@dongyuhua 你说的webdriver启动是指的怎么启动啊？

**Comment by dongyuhua** [comment]
@yyl2016  google 下 selenium webdriver吧，我也是迷迷糊糊装的。

**Comment by yyl2016** [comment]
@dongyuhua 这个已经安装了，你刚才说的启动是执行那个jar包吧？

**Comment by yyl2016** [comment]
java -jar selenium-server-standalone-2.53.1.jar？

**Comment by dongyuhua** [comment]
@yyl2016  你在uirecorder里默认是启动哪个浏览器的？如果是chrome和ie 你需要配置path和下载对应的Driver的。仔细看看大神写的那些文档。github上 uirecorder下也有写的。

**Comment by yyl2016** [comment]
@dongyuhua 
我的是运行 mocha test.spec.js 时报错

test.spec : chrome before
C:\Users\Smart>mocha test.spec.js

test.spec : chrome
1) "before all" hook

test.spec : ie 11
2) "before all" hook

0 passing (42s)
2 failing

1) test.spec : chrome "before all" hook:
Error: connect ETIMEDOUT 123.57.55.5:4444
at Object.exports._errnoException (util.js:873:11)
at exports._exceptionWithHostPort (util.js:896:20)
at TCPConnectWrap.afterConnect as oncomplete

2) test.spec : ie 11 "before all" hook:
Error: connect ETIMEDOUT 123.57.55.5:4444
at Object.exports._errnoException (util.js:873:11)
at exports._exceptionWithHostPort (util.js:896:20)
at TCPConnectWrap.afterConnect as oncomplete

**Comment by yyl2016** [comment]
@dongyuhua 你说的浏览器驱动和给驱动配环境变量我都做了，但还是出现这个错误，郁闷，所以想问一问你的安装和部署过程

**Comment by yyl2016** [comment]
@dongyuhua 你可以帮写一下你的安装部署过程吗？

**Comment by dongyuhua** [comment]
@yyl2016 那我也没有办法了  我是看这个然后部署上的。
https://github.com/alibaba/uirecorder

**Comment by dongyuhua** [comment]
@yaniswang 大神能告诉我怎么运行多个测试脚本么？

**Comment by yyl2016** [comment]
@dongyuhua 哦哦，你是做的以下这几步吗？
Install NodeJs

https://nodejs.org/
Install UI Recorder

npm install uirecorder -g
Init config

uirecorder init
Start recorder test case

uirecorder start
Run test case

npm install mocha -g

npm install jwebdriver expect.js mocha-generators faker --save-dev

mocha *.spec.js
How to deploy WebDriver Server

Selenium standalone server:

Download Selenium Server & IEDriverServer: http://selenium-release.storage.googleapis.com/index.html

Download ChromeDriver: http://chromedriver.storage.googleapis.com/index.html

Add the driver path to environment variable: PATH

Run selenium server: java -jar selenium-server-standalone-x.xx.x.jar

其他的还有吗？

**Comment by dongyuhua** [comment]
@yyl2016  你在浏览器里输入你的服务配置出现什么？如果是下面的，就应该启动了。如果是其它，证明你还没启动webDriver服务。

> HTTP ERROR: 404
> 
> Problem accessing /. Reason:
> 
>     Not Found
> Powered by Jetty://

**Comment by yyl2016** [comment]
@dongyuhua 你部署的时候用到过selenium-server-2.53.0.zip吗？

**Comment by yyl2016** [comment]
@dongyuhua 你部署的时候用到过selenium-server-2.53.0.zip吗？

**Comment by yyl2016** [comment]
@dongyuhua 上面提到的在浏览器上看，我也看了，有那东西，但好像还是执行不了....

**Comment by yaniswang** [comment]
mocha *.spec.js就可以运行多个用例

**Comment by dongyuhua** [comment]
@yaniswang  ok了，必须在录制脚本的时候起名要是XXX .spec.js格式才可以，我刚才重新录制了一遍，然后就好了，谢谢大神，另外我还想问一下测试结果可以生成测试报告么？我想自动跑测试然后自动发送邮件。不知道有没有生成报告的接口？

**Comment by yaniswang** [comment]
当然，你也可以是别的文件名啊，例如你的文件名是：aaa.test.js
那就执行命令：`mocha *.test.js`

**Comment by dongyuhua** [comment]
@yaniswang 可能是我昨天录制脚本的问题，确实如你所说跟文件名没关系。谢谢大神。
另外我想知道我如何将测试结果导出来？还请大神指教下。

**Comment by yaniswang** [comment]
要导哪去？

**Comment by dongyuhua** [comment]
@yaniswang 我想每天自动运行，然后自动发送邮件。将测试结果整理成测试报告发出来。

**Comment by Gebiuncle** [comment]
@yaniswang   我想同时运行两个driver，一个chrome，一个ie，应该怎样搞
 java -jar selenium-server-standalone-2.40.0.jar -Dwebdriver.chrome.driver=chrome.exe

**Comment by yaniswang** [comment]
@dongyuhua 这个你就要依赖别的持续集成平台了，例如jenkins,gitab-ci等等，这类平台非常多。

**Comment by yaniswang** [comment]
@Gebiuncle  java -jar selenium-server-standalone-2.40.0.jar 本身就支持各种浏览器

**Comment by yyl2016** [comment]
@yaniswang 你好，执行java -jar selenium-server-standalone-x.xx.x.jar然后，谷歌浏览器就可以正常执行，在IE11只就出现：
 1) aa.spec : ie 11 "before all" hook:
    Error: done() invoked with non-Error: The process has not exited yet theref
re no result is available ...
     at C:\Users\yyl\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:366:21
     at process._tickCallback (internal/process/next_tick.js:103:7)
这是怎么回事啊？

**Comment by yaniswang** [comment]
IEDriver下载了没有？

**Comment by yyl2016** [comment]
@yaniswang 下载了啊

**Comment by yaniswang** [comment]
能不能提供详细信息，问题肯定出在WebDriver或者浏览器没配置好

看下selenium-server-standalone界面上的错误日志是什么

**Comment by zhangrundi** [comment]
多个js 执行sh run.sh *.js为什么只执行了两个js
