### ISSUE TITLE
有没有提供切换webdriver内机器的hosts的方法?

### ISSUE THREAD

**Issue by pandalanlam** [alibaba/uirecorder#140]
对于开发或测试而言，必定有很多测试环境或开发环境。在录制脚本后重放时需要切换webdriver内节点的hosts，uirecorder和f2etest有没有提供在回放用例前切换hosts的方法？
或者说有没有什么推荐的解决方案？

**Comment by yaniswang** [comment]
直接修改工程目录下的hosts文件，就可以生效

**Comment by pandalanlam** [comment]
uirecorder安装目录下的hosts文件吗? 执行回放的时候并没有替换webdriver节点的hosts哦

**Comment by yaniswang** [comment]
并不需要替换，因为是用代理服务器实现的hosts

**Comment by yaniswang** [comment]
怎么样？hosts绑定生效了吗？

**Comment by xinlai3698** [comment]
直接修改工程目录下的hosts文件,没有作用呀，还是回放local环境
