### ISSUE TITLE
How do you set custom the headers?

### ISSUE THREAD

**Issue by vicpara** [alibaba/uirecorder#142]
Hi,
How do you set custom headers for each request?
I didn't find any support for headers in the api. I did find for cookies but that is not sufficient for my application?
Thanks,
Victor

**Comment by yaniswang** [comment]
No support for set custom headers.

**Comment by vicpara** [comment]
Is there a workaround this? At least for the initial request or a one time off request ? I've seen the Browser.js is able to add cookies. Headers will be about the same thing ?
Some suggestions to work around this issues will be more than welcomed.
