### ISSUE TITLE
Set cookie at test start

### ISSUE THREAD

**Issue by vicpara** [alibaba/uirecorder#144]
Hi,
Is there a way to set a cookie to a value before the test starts?
What about setting the cookie at the beginning of the recording session ?

Appreciate your answer!

**Comment by yaniswang** [comment]
You can use `Run Js`

**Comment by vicpara** [comment]
Does it work as we webdriver or how do you suggest to run uidriver with it ? I'm not that experienced with the node/npm ecosystem.
