### ISSUE TITLE
录制下拉框时，点击下拉框内的值，无法定位成功

### ISSUE THREAD

**Issue by landou1107** [alibaba/uirecorder#145]
✓ click: 变更16 ( #web-content div.navigation > div > div:nth-child(1) > div.text-left > div:nth-child(6), 53, 16, 0 ) (682ms)
    ✓ scrollTo: 0, 3424
    1) × mouseMove: 投资(3) ( //span[text()="投资(3)"], 36, 16 )
    2) × click: 投资(3) ( //span[text()="投资(3)"], 36, 16, 0 )
  10 passing (1m)
  2 failing
  1) 2 : chrome × mouseMove: 投资(3) ( //span[text()="投资(3)"], 36, 16 ):
     Error: the string "Wait element displayed timeout: //span[text()=\"投资(3)\"] ,30000ms" was thrown, throw an Error :)

**Comment by daotoulangzi** [comment]
我也遇到了这个问题，这个是一个 bug 吧，感觉和 #165 问题一样。

**Comment by yaniswang** [comment]
文本等于：投资(3)

这个无法定位到，页面中当时就没有这个文本吧？
