### ISSUE TITLE
根据it语句执行结果，执行不同的代码

### ISSUE THREAD

**Issue by luoxlgh** [alibaba/uirecorder#149]
是否有if/else的功能，可以根据执行结果指定不同的执行文件
比如：
if( it('实例创建成功') ){
    callSpec('detail.js'); // 查看实例详情
} else {
    callSpec('create.js'); // 重新创建实例
}

**Comment by yaniswang** [comment]
实现不了，因为it是静态执行时的定义语句
而你的需求是希望根据动态执行的结果来决定执行不同的it，所以这个功能在mocha框架下是无法实现的。
