### ISSUE TITLE
使用多浏览器测试时，firefox时常不成功，ie非常慢

### ISSUE THREAD

**Issue by gleams** [alibaba/uirecorder#15]
配置使用ie,chrome,firefox时，有以下问题
1.ie非常慢
2.firefox测试时有时能自动跑起来有时会报以下错误

``` js
"before all" hook

1) test.spec : firefox "before all" hook:
     Error: done() invoked with non-Error: this.getChromeWindowFromDocumentWindow(...) is undefined
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'test-PC', ip: '192.168.1.92', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: unknown
```

请问这是什么问题呢？

不过重复启动几次会有一次成功。

**Comment by yaniswang** [comment]
IE慢是正常的，据我所知目前好像没办法。
不过将来可以将多浏览器改为并发执行，这样一个浏览器慢也不至于影响太大。

firefox出错的是什么样的代码？

**Comment by yaniswang** [comment]
https://github.com/angular/protractor/issues/3049

firefox的问题可以参考这个，说是要把firefox升级到最新版本

**Comment by gleams** [comment]
谢谢，

**Comment by yaniswang** [comment]
楼上解决了吗？

**Comment by dongyuhua** [comment]
@yaniswang  我的脚本在多浏览器测试时，ie和chrome验证通过，firefox的点击事件总是失败 报如下错，请教大神怎么处理？

>  1) click: 登录 ( #unLogin li:nth-child(1) > a, 27.5, 14, 0 )
>     2) click: × ( #user_login a.close, 9.265625, 14.5, 0 )
>     3) × click: 数据查询 ( #common_tab li.open > a.dropdown-toggle, 42.5, 16, 0 )
>     √ scrollTo: 0, 778 (125ms)
>     4) click: dl:nth-child(1) > a > dd.search_img > img.center-block, 88, 70, 0
>     √ waitBody:  (547ms)
>     5) click: 北京 ( #district li:nth-child(1), 28, 11, 0 )
>     6) "after all" hook


>  Error: done() invoked with non-Error: Error communicating with the remote browser. It may have died.
> Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
> System info: host: 'DESKTOP-0KRF64E', ip: '192.168.2.165', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_101'
> Driver info: driver.version: EventFiringWebDriver
> Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, hosts=, appBuildId=20160823121617, version=48.0.2, platform=XP, proxy={}, command_id=1, specificationLevel=0, ie.ensureCleanSession=true, acceptSslCerts=false, browserVersion=48.0.2, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
> Session ID: 1bdcd1d9-4415-4afa-a4a4-e6adbebe9257

**Comment by yaniswang** [comment]
具体看下，是什么原因导致这个DOM找不到？
 #common_tab li.open > a.dropdown-toggle
