### ISSUE TITLE
init时浏览器选择firefox，但是run的时候还是启动的 chrome？

### ISSUE THREAD

**Issue by linjian128** [alibaba/uirecorder#150]
uirecorder init 选择浏览器的时候，  我试了2种情况：
      1.  选择默认的（chrome, ie 11）
      2. 自己输入firefox

 录完脚本，重放的时候，上面1,2 里面3个浏览器都是启动的 chrome。 

ps: chrome, ie 和firefox 都已加到环境变量，可以命令行启动

**Comment by yaniswang** [comment]
init的时候代表要执行的浏览器，而录制只能基于chrome实现。

你重放是用什么命令重放的？

**Comment by yaniswang** [comment]
是的，可以init的时候设置，也可以直接修改config.json

**Comment by linjian128** [comment]
好的，还是那个问题， config.json 里面设置任何浏览器， 我这边重放的时候都是启动的chrome

**Comment by yaniswang** [comment]
你的webdriver是怎么启动的？命令行截个图看下

**Comment by linjian128** [comment]
![image](https://user-images.githubusercontent.com/9270332/31371254-725f80e0-adc2-11e7-9d5f-f957a79c4a43.png)

**Comment by linjian128** [comment]
npm run server 之前是这么启动的，刚开始起不来， 后来发现 java版本号不对，之前是1.7.x 后来改成了1.8.x  再次用这条命令，就起来了

上图 应该是 启动后的，刚又运行了一次 npm run server

**Comment by yaniswang** [comment]
从你的截图来看，应该是启动失败了，端口号重复了

**Comment by linjian128** [comment]
目前是启动着的，所以运行这个 npm run server 会显示 in use吧？  

现在 回放正常，就是浏览器 不对，都是启动的chrome

**Comment by yaniswang** [comment]
你的config.json截个图看下

**Comment by linjian128** [comment]
![image](https://user-images.githubusercontent.com/9270332/31371442-5d26ecda-adc3-11e7-814e-6a6c612a5dfa.png)

能正常重放完，log显示 也是firefox，但是实际上启动的是chrome。

**Comment by linjian128** [comment]
![image](https://user-images.githubusercontent.com/9270332/31371479-a159f67c-adc3-11e7-89f3-c2509b33de59.png)

**Comment by yaniswang** [comment]
你直接用WINDOWS的命令行试试，不要用模拟的

还有，你可以关注下sel的命令行界面，当脚本跑的时候，肯定会有相关的日志信息

**Comment by crazyjam** [comment]
我也发现类似问题，已尝试使用windows命令行执行npm run server，还是只能拉起chrome来做测试

**Comment by linjian128** [comment]
是的，暂时windows上面，回放时，除了chrome，其他浏览器还没 启动起来过

**Comment by duckscofield** [comment]
我也无法启动其他浏览器

**Comment by duckscofield** [comment]
geckodriver.exe 已设定 OS 环境变数，测试时，shell 静止，连 CHROME 也没跳出，过几秒后报出这个错误，请问有人知道要怎么解吗

```
> D:\tmp>run.bat
> uirecorderTest@1.0.0 paralleltest D:\tmp
> mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5 --bail
 
[mochawesome] Generating report files...
 
  sample/test.spec : firefox
    1) "before all" hook
 
  0 passing (7s)
  1 failing
 
  1) sample/test.spec : firefox "before all" hook:
     Error: getaddrinfo ENOTFOUND d d:4444
      at errnoException (dns.js:53:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
 
 
[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml
 
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 paralleltest: `mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5 --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 paralleltest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\duck\AppData\Roaming\npm-cache\_logs\2017-10-30T08_10_56_132Z-debug.log
```

**Comment by yaniswang** [comment]
楼上你发下config.json，明显你的IP配置成`d`了，要填正确的IP

**Comment by duckscofield** [comment]
config.json 都没有改，只改了 browsers 的值，从 chrome 变成 firefox。 这 config.json 需要配合 firefox 做一些调整吗

```
{
    "webdriver": {
        "host": "127.0.0.1",
        "port": "4444",
        "browsers": "firefox"
    },
    "vars": {},
    "recorder": {
        "pathAttrs": "data-id,data-name,type,data-type,role,data-role,data-value",
        "attrValueBlack": "",
        "classValueBlack": "",
        "hideBeforeExpect": ""
    }
}
```

**Comment by arcsun** [comment]
同样遇到了这个问题，关注一下

**Comment by tuobabing** [comment]
同样遇到了这个问题，关注一下

**Comment by shaoronglei** [comment]
同样遇到了这个问题，关注一下

**Comment by natsuc** [comment]
同样遇到了这个问题，关注一下

**Comment by Explorer1092** [comment]
同样遇到了这个问题，关注一下

**Comment by wikeyi** [comment]
我也遇到这个问题，关注一下；

**Comment by qwIvan** [comment]
还没解决吗？

**Comment by javaguy0726** [comment]
> ![image](https://user-images.githubusercontent.com/9270332/31371442-5d26ecda-adc3-11e7-814e-6a6c612a5dfa.png)
> 
> 能正常重放完，log显示 也是firefox，但是实际上启动的是chrome。

我也是一样的问题

**Comment by qingranfjj** [comment]
同样的问题，怎么解决啊

**Comment by Stngle** [comment]
更新至最新版本，重新录制。或者删除已录制脚本的 chromeOptions 字段。
