### ISSUE TITLE
Ubuntu 只有chromium，没有chrome，能录制吗？

### ISSUE THREAD

**Issue by linjian128** [alibaba/uirecorder#153]

**Comment by linjian128** [comment]
![image](https://user-images.githubusercontent.com/9270332/31530502-82f1ad36-b013-11e7-8a68-2cdcaf21d931.png)

**Comment by linjian128** [comment]
![image](https://user-images.githubusercontent.com/9270332/31530519-ab6757e8-b013-11e7-8b60-d2c82a9ef80d.png)

**Comment by yaniswang** [comment]
没在linux下测试过chromium，你安装个chrome测试下

**Comment by linjian128** [comment]
linux下没有chrome，只有chromium-browser

**Comment by linjian128** [comment]
在哪里可以修改 录制时候启用的浏览器呢

**Comment by Stngle** [comment]
录制功能目前只支持 chrome
