### ISSUE TITLE
执行录制的脚本 ，出现错误

### ISSUE THREAD

**Issue by ailily** [alibaba/uirecorder#154]
D:\ui\sample>mocha test.spec.js

  sample/test.spec : chrome
    1) "before all" hook
    2) "after all" hook

  sample/test.spec : ie 11
    3) "before all" hook
    4) "after all" hook

  0 passing (216ms)
  4 failing

  1) sample/test.spec : chrome
       "before all" hook:
     Error: the string "Unable to create new service: ChromeDriverService\nBuild info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'\nSystem info: host: 'DESKTOP-CN99MIT', ip: '192.168.0.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'\nDriver info: driver.version: unknown" was thrown, throw an Error :)

**Comment by tangxingjun** [comment]
这个就是没有启动server：双击这个文件 selenium-server-standalone-3.4.0.jar或者cmd里面输入selenium-server-standalone-3.4.0.jar

**Comment by duckscofield** [comment]
请问这个文件是要自行下载吗？或者在uirecorder里的哪个资料夹里？

**Comment by ailily** [comment]
不是的，我selenium的服务是开启了的

**Comment by yaniswang** [comment]
从报错信息上来看，就是selenium出问题了，这块大家自行深度解决吧，网上有大量的文章介绍selenium相关的。

**Comment by duckscofield** [comment]
@ailily 试着执行`npm run server`，看是否有反应，如果没有，检查一下`package.json`，查看`server` scripts 做的事情有没有正确被执行起来，没有就这个资料夹移掉，重建(`uirecorder init`)

**Comment by nature1995** [comment]
@yaniswang 由于mac平台上面没有ie，所以创建项目的时候请选择chrome。如果是win则可以默认。希望可以修复一下默认选择，改成只有chrome。
![image](https://user-images.githubusercontent.com/25950998/68332377-b20c2b80-00a4-11ea-8f89-0264af3aabc2.png)

**Comment by Stngle** [comment]
好的

**Comment by xiazemin** [comment]
404 'http://npm.taobao.org/mirrors/chromedriver/91.0.4472.101/chromedriver_mac64.zip'
