### ISSUE TITLE
执行uirecorder sample/test.spec.js报错 Chrome打开失败！

### ISSUE THREAD

**Issue by hyj0903** [alibaba/uirecorder#157]
录制服务器监听在端口: 9765
Chrome打开失败！
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }

**Comment by mour471464900** [comment]
我跟你报了一样的错误，好烦啊

**Comment by mour471464900** [comment]
cnpm install uirecorder mocha -g  终于解决了

**Comment by duckscofield** [comment]
有不另外安装 npm 的方法吗

**Comment by yaniswang** [comment]
官网的npm在国内会被墙，必需要用cnpm

**Comment by duckscofield** [comment]
如果要使用这专案， 指令安装 ： 国外朋友请使用 NPM，国内使用 CNPM？

**Comment by litingjun2015** [comment]
您好： 我执行了  npm install uirecorder mocha -g 依旧报 “**录制服务器监听在端口: 9765
Chrome打开失败！**“的错，请帮忙看下，谢谢。

```
c:\bizapp3\sturdy\BizAppV3\tests\macaca\john (master) (uirecorderTest@1.0.0)
$ npm install uirecorder mocha -g
C:\Users\Administrator\AppData\Roaming\npm\mocha -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\mocha\bin\mocha
C:\Users\Administrator\AppData\Roaming\npm\_mocha -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\mocha\bin\_mocha
C:\Users\Administrator\AppData\Roaming\npm\uirecorder -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\uirecorder\bin\uirecorder
C:\Users\Administrator\AppData\Roaming\npm
+-- mocha@4.0.1
`-- uirecorder@2.5.34
```


c:\bizapp3\sturdy\BizAppV3\tests\macaca\john (master) (uirecorderTest@1.0.0)
$ uirecorder --mobile sample/test.spec.js
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.34

Official Site: http://uirecorder.com
------------------------------------------------------------------

? 测试脚本文件名: sample/test.spec.js
? App路径 (扩展名: apk, app, zip): massway.apk

```
录制服务器监听在端口: 9765
Chrome打开失败！
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }
```

**Comment by litingjun2015** [comment]
https://github.com/alibaba/uirecorder/issues/151

> 进入到uirecorder的安装目录，找到npm\node_modules\uirecorder\node_modules\chromedriver，按照readme.md重新安装chromedriver之后就可以使用录制了

**Comment by duckscofield** [comment]
请问直接在找到的那个资料路径下直接重新安装吗？还是需回到专案目录？还是使用者的根目录？

**Comment by duckscofield** [comment]
我依照 litingjun2015 的提示，在那個 chromedriver 目录下执行 `npm install chromedriver`，出现权限问题，后来改用 `npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver` 没有错误，再去专案目录下使用，已可以成功启动`chrome`，谢谢帮忙

**Comment by zhoubhin** [comment]
我遇到的问题是运行`source run.sh sample/test.spec.js`命令后，终端提示：

> sample/test.spec : chrome
    1) "before all" hook

> Error: connect ECONNREFUSED 127.0.0.1:4444
不知道有没有遇到这问题的朋友
