### ISSUE TITLE
上传功能报错：cannot read property "replace" of undefined

### ISSUE THREAD

**Issue by tangxingjun** [alibaba/uirecorder#158]
根据你们的方法，修改了下上传的代码，实现一段代码上传多个附件，但是之前明明实现了，最近这段时间就突然报错了，这个问题我还解决不了，不知道是不是版本升级导致的。附上源代码：
it('uploadFile: uploadfiles', async function(){
		var list= [["/uploadfiles/[SQL注入测试安全工具].Pangolin.Professinal.Edition.v3.2.5.1137.incl.Keygen-FFF.zip"],["/uploadfiles/xx.txt"],["/uploadfiles/1.png"]];
		for (var i=0; i<list.length ;i++ )
		{
        await driver.sleep(300).wait('#uploadFileInput', {timeout: 30000, displayed: false})
               .sleep(300).uploadFile(rootPath+list[i]);
		}		
    });
下面是报错信息：
![image](https://user-images.githubusercontent.com/32895309/31707693-a0523c6e-b41f-11e7-8a6d-18b3bdb35d18.png)

**Comment by tangxingjun** [comment]
TypeError: Cannot read property 'replace' of undefined
 at PromiseClass.sendKeys (node_modules\_jwebdriver@2.2.4@jwebdr
s.js:494:20)
 at node_modules\_promiseclass@1.0.3@promiseclass\lib\promisecla

 at Promise (<anonymous>)
 at ChainPromise (node_modules\_promiseclass@1.0.3@promiseclass\
.js:22:28)
 at PromiseClass.wrapFunction [as sendKeys] (node_modules\_promi
omiseclass\lib\promiseclass.js:57:31)
 at Promise.<anonymous> (node_modules\_jwebdriver@2.2.4@jwebdriv
js:658:25)
 at <anonymous>
 at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by mislaydu** [comment]
有没可能因为第一个文件可能还没上传好就去上传第二个，所以出错了

**Comment by tangxingjun** [comment]
找到原因了，是因为上传的附件问题，上面问题的代码不是我出错的代码，出错的原因是因为我的附件中存在一个附件，名称为：[SQL注入测试安全工具].Pangolin.Professinal.Edition.v3.2.5.1137.incl.Keygen-FFF.zip。
可能是文件内容或者名字触发了安全拦截机制，我更换了一个名称的zip文件就可以实现上传了
