### ISSUE TITLE
有没有提供清除浏览器缓存的方法？

### ISSUE THREAD

**Issue by tangxingjun** [alibaba/uirecorder#159]
录制过程中需要清除浏览器缓存，但是貌似uirecoder无法实现？

**Comment by mislaydu** [comment]
API文档不是有写吗

**Comment by tangxingjun** [comment]
请问在哪里看？我没找到

**Comment by yaniswang** [comment]
录制过程中需要清除浏览器缓存？webdriver技术体系没提供这样的功能。

而且我也觉得这样的需求不合理，建议拆分成多个脚本，每个脚本跑都是独立的空白环境，不会相互影响。

**Comment by tangxingjun** [comment]
在Jwebdriver的API文档里找到了清除cookie的方法:driver.clearCookies();附上jwebdriver的API地址：http://jwebdriver.com/api/classes/Browser.html
