### ISSUE TITLE
使用ui recorder的问题，求帮助

### ISSUE THREAD

**Issue by gleams** [alibaba/uirecorder#16]
使用ui recorder有几天了，这几天想多做几个用例来验证是否使用 ui recorder加入到测试小组中，并且加入到产品测试环节中去。在使用过程有以下几个问题比较纠结
1. 录制脚本检验都成功了，但回放的时候失败（其中几个操作步骤失败）。
2. 对原生alert支持不好，有时能检验成功有时不行。
3. 如果使用的插件中包含iframe，检验不成功
4. 跑用例不是很稳定，有时用例能一次跑通，有时不行（一些步骤检验不成功）

如果不稳定的话肯定是没有办法加入到产品测试环节中去的，我的想法是所有的产品必需通过自动化的回归测试。但如果自动化测试用例本身就不稳定，这肯定不行的。
针对以上问题请高手指点一下。谢谢！

**Comment by yaniswang** [comment]
把具体失败的原因抛出来，哪些因素引起不稳定的？

**Comment by yyl2016** [comment]
@yaniswang UIRecorder是否可以自动生成测试报告啊？

**Comment by yaniswang** [comment]
我们目前是基于mocha实现的测试用例，因此基于mocha理论上就可以实现测试报告功能，可以尝试在网上找找看有没有现成的。

还有，你具体是希望生成哪个持续集成平台的报告？
