### ISSUE TITLE
无法录制，元素获取不到

### ISSUE THREAD

**Issue by zhong914** [alibaba/uirecorder#160]
proxy.js:55:14[master] pid:14056 Proxy: /wd/hub/session/:sessionId/source:GET to 
    http://127.0.0.1:9004/wd/hub/session/:sessionId/source:GET with body: null

录制的时候获取不到元素id，一直undefined，看了server端，提示如上，body是null？
uirecorder支持的macaca-cli版本是都支持吗？

环境如下：
  macaca version： 2.0.10
  uirecorder        ： 2.5.33
  macaca-doctor version: 2.0.3
  
Node.js checklist:
  node env: C:\Program Files\nodejs\node.exe
  node version: v8.7.0
  
Android checklist:
  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `E:\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `E:\Android`
  Platforms is set to `E:\Android\platforms\android-26`
  ADB tool is set to `E:\Android\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`
  
Installed driver list:
  android: 2.0.40
  chrome: 1.0.6
  electron: 1.1.11

**Comment by tangxingjun** [comment]
是不是有frame什么的，或者换种定位方式

**Comment by zhong914** [comment]
@tangxingjun 元素都找不到= =，除了绝对坐标还能用

**Comment by tangxingjun** [comment]
目前为止我还没遇到这样的情况，我在录制的时候除了遇到iframe或者动态ID，稍微需要处理下，一般需要手动更改定位方式的错误代码不是很多

**Comment by zhong914** [comment]
@tangxingjun 请问你的环境各版本是怎样的？

**Comment by tangxingjun** [comment]
@zhong914 留下你的邮箱，我把各文件发给你

**Comment by zhong914** [comment]
&#122&#104&#111&#110&#103&#57&#49&#52&#64&#103&#109&#97&#105&#108&#46&#99&#111&#109  Thx！

**Comment by tangxingjun** [comment]
额，你发出来的邮箱地址乱码了，我得邮箱：13951753214@139.com

**Comment by yaniswang** [comment]
楼主说的是无线的录制， @tangxingjun 你说的应该是PC录制吧？

PC和无线录制完全不一样的。

**Comment by tangxingjun** [comment]
@zhong914 @yaniswang 确实我说的不是移动端的....

**Comment by zhong914** [comment]
macaca升级后解决了
