### ISSUE TITLE
Run firefox, but pop chrome

### ISSUE THREAD

**Issue by duckscofield** [alibaba/uirecorder#162]
my config.json

{
    "webdriver": {
        "host": "127.0.0.1",
        "port": "4444",
        "browsers": "firefox,chrome"
    },
    "vars": {},
    "recorder": {
        "pathAttrs": "data-id,data-name,type,data-type,role,data-role,data-value",
        "attrValueBlack": "",
        "classValueBlack": "",
        "hideBeforeExpect": ""
    }
}

1) This project only support Chrome & IE？
2) Selenium-webdriver could run many browser, jWebDriver support too?
3) Other browser value could be what? Is there a list for reference?

**Comment by yaniswang** [comment]
Recorder only support chrome, buy can run with any browsers.

**Comment by NishantMadkikar** [comment]
Is there run with any browsers specially on firefox and IE ,when I run test script on this browser its does not supported on that and by default open chrome browser and run only on chrome. Can u please told me how to I run with firefox and IE .Thank you
