### ISSUE TITLE
What can be done with raw commands? 

### ISSUE THREAD

**Issue by lkende** [alibaba/uirecorder#163]
`uirecorder start --raw`

When you save the raw commands and get a test.spec.json, what can you do with it?  This does not work:

`source run.sh sample/test.spec.json`

I was hoping to be able to run the test back or create a mocha script from the raw json file but I do not see a way to do this. Any ideas?  What value does this file have?

**Comment by yaniswang** [comment]
You can translate `*.json` to `*.java` or `*.py` by your self.

**Comment by lkende** [comment]
Thank you.

A couple of suggestions for potential development:
1. Be able to read in raw json and generate mocha script.
2. Save as Selenium1 ("selenese" html) and/or Selenium2 (Selenium Builder json).

**Comment by lkende** [comment]
One last question.  If I were to create a branch with an option to have something like:

`uirecorder start --raw-selenium2`

that then in lib/start.js in saveTestFile() have a converter that saves the raw commands in [selenium2 json format](https://github.com/SeleniumBuilder/se-builder/wiki/JSON-Format), are you open to this idea?

It would make this tool more compatible with other selenium tools, namely Selenium Builder.

**Comment by lkende** [comment]
As I delve deeper into this tool, I see that actions recorder are coupled with the use of mocha tests and mouse move.  Trying to export the raw commands to selenium2 json is not straight-forward.  Closing this discussion for now.
