### ISSUE TITLE
点击文本框执行失败 Wait element displayed timeout

### ISSUE THREAD

**Issue by YourChoice-Wong** [alibaba/uirecorder#165]
用 uirecorder 进行 iOS 端 demo 录制时，点击了文本框，但不能定位到元素，终端输出：
 tap: //*[@name="demo"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeTextField/XCUIElementTypeTextField
   ✖ 执行失败 Wait element displayed timeout: //*[@name="demo"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeTextField/XCUIElementTypeTextField ,10000ms

UIRecorder 版本：v2.5.34
使用的模拟器：（iPhone 7，iOS 10.3）

macaca version: 2.0.12

Node version: v8.7.0

  iOS checklist:
  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.0.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.25.0

 Installed driver list:
  chrome: 1.0.7
  electron: 1.1.14
  ios: 2.0.27

**Comment by pajk-chenchen** [comment]
碰到了同样的问题。
目测是xpath_lite不正确导致的。
使用app-inspector获取xpath_lite，手动修改test.spec.js了里输入框的xpath_lite，
运行 macaca run -p 4444 -d sample/test.spec.js 跑通了。
问题是总不能每个文本框都要去手动获取xpath_lite吧，有什么方法可以解决。

**Comment by sheeeeep** [comment]
我也遇到了，希望能有解决方案

**Comment by daotoulangzi** [comment]
我的 web 端应用也会出现这个错误，不知道什么原因。求解啊

 `× 执行失败 Wait element displayed timeout: #clickNetworkFunction div ,10000ms`

**Comment by yaniswang** [comment]
楼主的问题是手机上的问题，楼上的问题是网页上的问题，不是同一个问题。
