### ISSUE TITLE
如何在测试代码中发起接口请求？

### ISSUE THREAD

**Issue by BeHappyF** [alibaba/uirecorder#166]
试过通过jscode当中添加代码的方式去发起请求，但业务代码中涉及到比较复杂的参数传递。所以会有一个base.js这样的文件去处理请求的参数处理等，在录制脚本当中通过require的方式引入，但是在jscode当中的eval()方法中无法正常执行。

想咨询下，目前是否有规范的方法去代码中发起请求、或者后续添加相关特性的打算。

**Comment by yaniswang** [comment]
这种场景只能基于录制生成的代码进行二次开发，具体如何写JS代码，需要大家自学下NODEJS

**Comment by BeHappyF** [comment]
还有一个问题：怎样在录制生成的代码当中获取浏览器环境下的数据内，比如：当前登录后的用户cookie信息。

**Comment by yaniswang** [comment]
jwebdriver相关API请参考官网：http://jwebdriver.com/

**Comment by BeHappyF** [comment]
十分感谢呀！我开始一直在uirecorder查询想关的文档。找不到。。。
