### ISSUE TITLE
页面增加一个元素会造成整个脚本跑不通

### ISSUE THREAD

**Issue by luoxlgh** [alibaba/uirecorder#169]
由于mouseMove中写定了鼠标的坐标，因此页面坐标变化时，无法click到指定元素。
而脚本的运行还是 √。

可否将click()函数改为根据元素选择器进行click点击？

**Comment by yaniswang** [comment]
那是相对于控件的相对坐标，一般不会影响。

**Comment by mislaydu** [comment]
@yaniswang 可否将click()函数改为根据元素选择器进行click点击，这样就不用每次click()前mouseMove()了

**Comment by yaniswang** [comment]
为了兼容所有场景，所以我们默认是基于相对坐标进行点击的，仿真用户的真实行为。

根据我们长时间的测试，目前没碰到因为这个问题引起的兼容性问题。

**Comment by kobe1996** [comment]
@luoxlgh @yaniswang 请问一下，有替代的方法么？
