### ISSUE TITLE
如果遇到验证码等怎么解决？

### ISSUE THREAD

**Issue by akhuting** [alibaba/uirecorder#17]
如果录制过程中遇到需要输入验证码、或者手机验证码等流程怎么办

**Comment by yaniswang** [comment]
这个无解，主流手工是将测试账号加入白名单，不要出现验证码或手机。
目前阿里集团全是这样的方式。

**Comment by akhuting** [comment]
好的，谢谢，还有就是刚才我在录制测试的过程中，有个页面是新窗口打开的，导致回放的时候测试用例失败，应该还是在当前页面寻找元素？

**Comment by yaniswang** [comment]
理论上应该不会，新开窗口的时候，自动化也会自动聚集到新窗口上

加QQ群交流：416221937
