### ISSUE TITLE
uirecorder启动报chrome打开失败

### ISSUE THREAD

**Issue by bsnow1220** [alibaba/uirecorder#170]
在windows本机和linux服务器上安装都报一样的错误：
![image](https://user-images.githubusercontent.com/15192943/32261940-a9bab0ae-bf0c-11e7-9fc6-a4f4a2c22d52.png)
操作系统：win7
chrome版本：62.0.3202.75（正式版本） （64 位）
chromedriver：2.9

**Comment by yaniswang** [comment]
你的uirecorder是不是用npm命令安装的？建议换成cnpm来安装，就不会出现被墙的问题。
