### ISSUE TITLE
npm i uirecorder -g 更新后，回放失败

### ISSUE THREAD

**Issue by linjian128** [alibaba/uirecorder#171]
1.  npm i uirecorder -g 更新到v2.5.34
2.  可以录制
3.  npm run server  启动没见异常
4.  无法回放成功（此脚本文件之前是可以成功回放的），不确定是不是因为 更新后导致

![image](https://user-images.githubusercontent.com/9270332/32266054-cb65c4e6-bf20-11e7-891e-a69fb25bb8d6.png)

**Comment by linjian128** [comment]
谢谢，还是不行啊
![image](https://user-images.githubusercontent.com/9270332/32266489-9719f49e-bf22-11e7-985c-49bd724ea140.png)
![image](https://user-images.githubusercontent.com/9270332/32266498-9d1ef9de-bf22-11e7-859c-524e95e3ca7b.png)

**Comment by yaniswang** [comment]
没有生效，你将进程里所有的chromedriver杀掉，再试试。

应该是之前老版本的chromedriver还在进程里

**Comment by linjian128** [comment]
不行啊，新 的chromedriver没有起来
重启了电脑，进程杀了，重新打开 npm run server,  发现还是启动的牢的 chromedriver 啊

![image](https://user-images.githubusercontent.com/9270332/32267281-abc371ce-bf25-11e7-8c07-dd334e79daee.png)

**Comment by yaniswang** [comment]
安装已经成功了吗？uirecorder组件的目录里是不是已经是新版的chromedriver.exe了？

**Comment by linjian128** [comment]
不确定安装有没有成功，但是 安装过程中没有失败的log
安装信息中看到  安装的目录下 chromedriver 是新的
![image](https://user-images.githubusercontent.com/9270332/32267770-5340ee3a-bf27-11e7-8b1c-32255b5be688.png)

但是 我case的工作目录是这个，里面是旧的chromedriver
![image](https://user-images.githubusercontent.com/9270332/32267734-38f4742a-bf27-11e7-962b-73fc8191315d.png)

**Comment by yaniswang** [comment]
从文件名上来看，已经安装成功了

**Comment by yaniswang** [comment]
你的录制应该正常了吧？
跑用例，还要升级selenium-standalone

**Comment by linjian128** [comment]
嗯，录制正常， 跑不行
selenium-standalone 怎么更新啊？ 更新脚本没有做更新吗？ 早知道不更新了。。。

**Comment by linjian128** [comment]
手动更新了下 cnpm i selenium-standalone ，npm run server的时候提示找不到 新的chromedriver

**Comment by linjian128** [comment]
我重新uirecorder  init 了一个目录， 在新的目录里面正常了。  不过版本还是旧的，不管了，能用就行，不想更新了，多谢技术支持！

总结一下：
 1.  录制脚本提示的 npm i uirecorder -g 貌似只更新了uirecorder，当前工作目录中相关的 chromedriver 和 selenium server相关没有更新，导致 回放起不来
 2.  cnpm install uirecorder -g 和  npm i uirecorder -g 不知道有什么区别
 3. 实在不行 就 重新 init一个目录，init时候 会自动下载webdriver和selenium-standalone

**Comment by yaniswang** [comment]
本地里可能要强行升级，用i命令可能不行，要用`cnpm update selenium-standalone`

**Comment by zhangjianpinghik** [comment]
我原来的selenium-standalone是好用的,但是执行 cnpm i selenium-standalone 后 在执行npm run server就报错了
