### ISSUE TITLE
npm ERR! missing script: singletest after sourcing run.sh sample/test.spec.js

### ISSUE THREAD

**Issue by wangjuanmt** [alibaba/uirecorder#172]
$ source run.sh sample/test.spec.js
npm ERR! missing script: singletest
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juan.wang/.npm/_logs/2017-11-01T12_16_30_034Z-debug.log

It looks both singletest and paralleltest not installed, how to install the two packages?
I have installed uirecorder by 'npm i uirecorder -g'.

Thanks!

**Comment by wangjuanmt** [comment]
Thanks @yaniswang for help take a look. Here is package.json under uirecorder project.
`{
  "name": "uirecorder",
  "version": "2.5.35",
  "description": "Tool for record ui test case",
  "main": "./index",
  "bin": {
    "uirecorder": "./bin/uirecorder"
  },
  "dependencies": {
    "async": "2.1.2",
    "chai": "3.5.0",
    "chromedriver": "2.x.x",
    "co": "4.6.0",
    "colors": "1.1.2",
    "commander": "2.9.0",
    "fs-extra": "1.0.0",
    "i18n": "0.8.3",
    "inquirer": "3.0.1",
    "jwebdriver": "2.2.4",
    "latest-version": "2.0.0",
    "npminstall": "3.1.1",
    "os-locale": "1.4.0",
    "semver": "5.3.0",
    "websocket": "1.0.22",
    "resemblejs-node": "1.0.0"
  },
  "devDependencies": {},
  "repository": {
    "type": "git",
    "url": "git@github.com:alibaba/uirecorder.git"
  },
  "bugs": {
    "url": "https://github.com/alibaba/uirecorder/issues"
  },
  "keywords": [
    "uirecorder",
    "webdriver",
    "test",
    "recorder"
  ],
  "author": "Yanis Wang",
  "license": "MIT"
}
`

**Comment by yaniswang** [comment]
Where is your `package.json` after `uirecorder init`?

**Comment by wangjuanmt** [comment]
In a different directory, does it matter?
I do `uirecorder init` under directory `~/workspace`, there `package.json` is
```
{
  "name": "uirecorderTest",
  "version": "1.0.0",
  "description": "",
  "main": "",
  "dependencies": {
    "chai": "3.5.0",
    "jwebdriver": "2.2.4",
    "mocha": "3.1.2",
    "mocha-parallel-tests": "1.2.4",
    "mochawesome-uirecorder": "1.5.22",
    "resemblejs-node": "1.0.0",
    "selenium-standalone": "6.x.x"
  },
  "devDependencies": {
  },
  "scripts": {
    "installdriver": "./node_modules/.bin/selenium-standalone install --drivers.firefox.baseURL=http://npm.taobao.org/mirrors/geckodriver --baseURL=http://npm.taobao.org/mirrors/selenium --drivers.chrome.baseURL=http://npm.taobao.org/mirrors/chromedriver --drivers.ie.baseURL=http://npm.taobao.org/mirrors/selenium",
    "server": "./node_modules/.bin/selenium-standalone start",
    "test": "./node_modules/.bin/mocha \"*/**/*.spec.js\" --reporter mochawesome-uirecorder --bail",
    "singletest": "./node_modules/.bin/mocha --reporter mochawesome-uirecorder --bail",
    "paralleltest": "./node_modules/.bin/mocha-parallel-tests \"*/**/*.spec.js\" --reporter mochawesome-uirecorder --max-parallel 5 --bail"
  },
  "author": ""
}
```
And then  `cd uirecorder`, `uirecorder sample/test.spec.js`. 

Do i need delete my local uirecorder and re-clone, then do these steps under the same uirecorder directory?

**Comment by yaniswang** [comment]
UIRecorder is a tool, you must install it to global path: `npm i uirecorder -g`

then init your test project: `uirecorder init`
