### ISSUE TITLE
请问如何录制拍照脚本？

### ISSUE THREAD

**Issue by SuzutsukiKagami** [alibaba/uirecorder#173]
虚拟机：AS自带，Nexus_S_API_23
uirecorder版本：2.5.35

在录制的时候，点击拍照界面的拍照按钮，提示无法录制

尝试直接在脚本文件加入：
const KEY_MAP = require('webdriver-keycode');
driver.keys(`send keys: ${KEY_MAP.CAMERA}`)
但加入后脚本文件直接读取失败

**Comment by yaniswang** [comment]
这个目前取决于macaca的API中是否支持这个
