### ISSUE TITLE
如何config参数化公共脚本的路径？

### ISSUE THREAD

**Issue by landou1107** [alibaba/uirecorder#177]
config.json已经配置参数 "vipPath": "commons/login.js"

callSpec(_(`{{vipPath}}`));
        it('waitBody: ', async function(){
            console.log('调用脚本路径输出:' + _(`{{vipPath}}`))
            await driver.sleep(500).wait('body', 30000).html().then(function(code){
                isPageError(code).should.be.false;
            });
        });

发生异常: TypeError
TypeError: Cannot read property 'vipPath' of undefined

输出结果报错，无法正常使用，请问应该如何处理调用公共脚本参数化的问题？感谢！！！

**Comment by yaniswang** [comment]
uirecorder里的变量是运行时的变量，无法在it回调之外使用。

如果你要在外部使用，需要自己依赖配置文件。
