### ISSUE TITLE
关于使用uirecorder时准备测试数据的一些疑问

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#178]
某些情况下，当我们要测试一个系统的端到端功能是否打通，比如用户管理中的查看用户的功能，需要自己造一些模拟数据来进行测试。

我们希望可以在执行用例之前先调用脚本或nodejs函数实现添加模拟数据，然后在执行用例之后再用同样的方法把对应的模拟数据删除。

请问目前有没有一个比较好的方法能够把模拟数据的相关操作与uirecorder的测试用例方便的结合起来呢？

**Comment by yaniswang** [comment]
根据阿里内部的经验来看，建议按照以下方案来造数据：

1. 将造数据的接口设计成HTML模式
2. 将造数据的过程也用uirecorder录制，接口生成的数据用变量抓取，以便在后续测试中复用

**Comment by stevobm** [comment]
用到的数据都通过界面来管理应该属于一种比较理想的情况，而且相对来说成本会比较高。

实际测试过程中大部分要用到的数据可能都需要手动（或者写脚本）构造，而目前这些脚本(如shell、python或nodejs)仍无法很好的与uirecorder生成的测试用例集成。

但如果在录制过程中能够支持调用外部命令(类似于傲游的“外部工具”)，那就简单了。比如可以在录制界面上添加“执行外部命令”功能，点击后弹出输入框，用户输入对应脚本（比如sh prepareData.sh）即可。该步骤生成的用例代码类似于：
```
    it('Execute external command: sh prepareData.sh', function(){
        return executeExternalCmd("sh prepareData.sh");
    });
```
这样就可以支持录制过程中的模拟数据操作了，而且操作可以在最终的报表上可见，接口也非常灵活。当然，这只是个简单方案，仅供参考。

**Comment by yaniswang** [comment]
无论如何，必需要保证造数据是用例实例级别的，不能是run.sh级别

比如我开了10个并发跑用例，而且每个用例同时要跑3个浏览器，那么造数据就必需是每个浏览器各自造自己的数据。

所以无论是用脚本调用的方式，还是直接通过HTML访问造数据，都必需是执行实例级别的。

你这种方式也是可以的，NODEJS可以同步的执行外部脚本:http://nodejs.cn/api/child_process.html#child_process_child_process_execsync_command_options 

类似这样： `child_process.execSync('python test.py')`

**Comment by stevobm** [comment]
嗯，上面的方案只是表示一个大意，真正要实现肯定要考虑并发等情况。如果uirecorder能够支持这个功能那就太好了。O(∩_∩)O~

**Comment by yaniswang** [comment]
那这个问题就关闭了
