### ISSUE TITLE
多个用例嵌套执行失败

### ISSUE THREAD

**Issue by ohmydengzi** [alibaba/uirecorder#18]
testcase1是登陆，testcase2是嵌套了testcase1（就是在刚开始就调用testcase1，这步是成功的），现在testcase3想在刚开始就调用testcase2，然后执行失败。

>  -------------- start load test2.spec.js --------------
 url: http://localhost/?r=user/default/login
  × 执行失败  TypeError: Cannot read property 'url' of undefined
 waitBody:
  × 执行失败  TypeError: Cannot read property 'sleep' of undefined
 sendKeys: admin
  × 执行失败  TypeError: Cannot read property 'sendKeys' of undefined
 click: password ( #password, 83, 39, 0 )
  × 执行失败  TypeError: Cannot read property 'sleep' of undefined
 sendKeys: 123456
  × 执行失败  TypeError: Cannot read property 'sendKeys' of undefined
 click: 登 录 ( input[name="loginsubmit"], 111, 8, 0 )
  × 执行失败  TypeError: Cannot read property 'sleep' of undefined
 waitBody:
  × 执行失败  TypeError: Cannot read property 'sleep' of undefined
 mouseUp: #cm_menu li:nth-child(2) > a > div.posr, 40.5, 64, 0
  × 执行失败  Wait elelment displayed timeout: 30000ms
 click: #cm_menu li:nth-child(2) > a > div.posr, 40.5, 64, 0

**Comment by yaniswang** [comment]
你是哪个版本录制的？

早期版本有个BUG，已经修复了，你用最新版本重新录一下试试。

**Comment by ohmydengzi** [comment]
@yaniswang NPM 下来的1.2.1

**Comment by yaniswang** [comment]
你这个是直接在录制过程中就失败了吧？

**Comment by ohmydengzi** [comment]
是的，录制刚开始就放之前的用例。

**Comment by yaniswang** [comment]
uirecorder v1.2.3，已经修复此问题

**Comment by ohmydengzi** [comment]
@yaniswang 解决的方法就是只能嵌套一层？

> [RangeError: Maximum call stack size exceeded]
