### ISSUE TITLE
关于精简优化uirecorder用例代码结构的建议

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#181]
由于uirecorder暂时还不支持图形界面的操作步骤管理，用例录制只能一次成型，因此用户还是时常需要进到生成的用例代码里面去做一些调整，包括合并或分拆部分用例等。而这个过程中，用例代码越整洁，整理起来也就越轻松。

就uirecorder目前生成的用例代码而言，里面包含的与录制步骤无关代码还是比较多的——几乎每个用例的收尾都会有近200行的“通用代码”，同一个测试工程里面几乎所有用例这部分代码都是一样的，而这在用户看来实际上是一种冗余。

建议**对测试代码生成的框架进行一些调整，让用户看到的测试用例代码里面只包含纯净的步骤代码，而公共代码则提取出来放在工程的一个统一的地方**（按经验看甚至可以直接内置到工具里面），这样的结构也更方便后期工具的兼容和扩展。思路仅供参考，谢谢！

**Comment by mislaydu** [comment]
uirecorder 只是录来参考，我都是手写的，要啥写啥

**Comment by wanghaihong200** [comment]
版主的建议说到点上了，录制工具目前只有web可以一用，但毛病也如版主所说，希望能在后续版本中改进吧。至于app的录制，目前来说就是个半成品的玩具，看看就好。
