### ISSUE TITLE
 Failed to install app 'com.xx.xx', please install the app manually. this.device.installUntilReady is not a function

### ISSUE THREAD

**Issue by oosnail** [alibaba/uirecorder#182]
iOS真机使用uirecord 失败，不能安装应用。

uirecord 日志：
`
录制服务器监听在端口: 9765
录制浏览器已开启
手机打开失败，请检查macaca是否配置正确？ Failed to install app 'com.xx.xx', please install the app manually.
`

macaca server 日志：
>> index.js:18:12 [master] pid:45146 webdriver server start with config:
 { port: 4444,
  verbose: true,
  always: true,
  ip: '10.12.54.132',
  host: 'zhangtianchendeMacBook-Pro.local',
  loaded_time: '2017-11-20 14:45:24' }
>> middlewares.js:17:10 [master] pid:45146 base middlewares attached
>> router.js:133:10 [master] pid:45146 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:45146 Recieve HTTP Request from Client[2017-11-20 14:45:44]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","app":"/Users/ztcq/Desktop/ipa/d.zip","udid":"199ce7e631ef60de8b6702******"}}
>> session.js:47:10 [master] pid:45146 Creating session, sessionId: aa0310ab-e463-4699-b097-b58a9ecb827b.
ios-deploy
>> helper.js:162:12 [master] pid:45146 Unzipping local app form /Users/ztcq/Desktop/ipa/d.zip
CFBundleIdentifier is com.xx.xx
Get bundleId com.xx.xx from plist /var/folders/ds/d_bj7pq17q72td0wdkyvg_km0000gn/T/Payload/Info.plist
>> macaca-ios.js:279:12 [master] pid:45146 App 'com.xx.xx' is not installed.
>> macaca-ios.js:284:14 [master] pid:45146 this.device.installUntilReady is not a function
>> responseHandler.js:56:12 [master] pid:45146 Send Error Respone to Client: UnknownError: Failed to install app 'com.xx.xx', please install the app manually.
>> responseHandler.js:62:14 [master] pid:45146 UnknownError: Failed to install app 'com.xx.xx', please install the app manually.
    at IOS.startRealDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:285:13)
    at IOS.startRealDevice.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at <anonymous>

我注意到报错中的一句话：
 this.device.installUntilReady is not a function

**Comment by oosnail** [comment]
查看源码
commits: e73c3e3
replace to installUtilReady
将 yield this.device.install(app); 改为 yield this.device.installUntilReady(app, bundleId);
可是installUntilReady方法 跑不起来
于是我自己改回来，ios真机就能跑起来了。

**Comment by MarkwwLiu** [comment]
感謝 已解決，但卡在下一個地方
會一直重複底下的log

>> responseHandler.js:11:12 [master] pid:2446 Recieve HTTP Request from Client[2018-01-27 18:18:23]: method: GET url: /wd/hub/session/bc976206-21d1-4da3-ad99-b8dfa5b48820/source, jsonBody: {}
>> proxy.js:55:14 [master] pid:2446 Proxy: /wd/hub/session/bc976206-21d1-4da3-ad99-b8dfa5b48820/source:GET to http://localhost:8001/wd/hub/session/26DADAC3-EB9E-403B-8741-BEAB0226BBAD/source:GET with body: {}
>> proxy.js:85:20 [master] pid:2446 Got response with status 200: {"sessionId":"bc976206-21d1-4da3-ad99-b8dfa5b48820","status":0,"value":"{\n  \"label\" : \"PhotoGrid\",\n  \"name\" : \"PhotoGrid\",\n  \"value\" : \"\",\n  \"isEnabled\" : true,\n  \"isVisible\" :...
>> session.js:109:14 [master] pid:2446 Send HTTP Respone to Client[2018-01-27 18:18:25]: {"sessionId":"bc976206-21d1-4da3-ad99-b8dfa5b48820","status":0,"value":"\"{\\n  \\\"label\\\" : \\\"PhotoGrid\\\",\\n  \\\"name\\\" : \\\"PhotoGrid\\\",\\n  \\\"value\\\" : \\\"\\\",\\n  \\\"isEnabled\\\" : true,\\n  \\\"isVisible\\\" : true,\\n  \\\"rect\\\" : {\\n    \\\"height\\\" : 667,\\n    \\\"x\\\" : 0,\\n    \\\"y\\\" : 0,\\n    \\\"width\\\" : 375\\n  },\\n  \\\"type\\\" : \\\"Application\\\",\\n  \\\"frame\\\" : \\\"{{0, 0}, {375, 667}}\\\",\\n  \\\"rawIndentifier\\\" : \\\"\\\",\\n  \\\"children\\\" : [\\n    {\\n      \\\"label\\\" : \\\"\\\",\\n      \\\"nam..."}
>> responseHandler.js:11:12 [master] pid:2446 Recieve HTTP Request from Client[2018-01-27 18:18:25]: method: GET url: /wd/hub/session/bc976206-21d1-4da3-ad99-b8dfa5b48820/screenshot, jsonBody: {}
>> proxy.js:55:14 [master] pid:2446 Proxy: /wd/hub/session/bc976206-21d1-4da3-ad99-b8dfa5b48820/screenshot:GET to http://localhost:8001/wd/hub/session/26DADAC3-EB9E-403B-8741-BEAB0226BBAD/screenshot:GET with body:
>> proxy.js:85:20 [master] pid:2446 Got response with status 200: {"sessionId":"bc976206-21d1-4da3-ad99-b8dfa5b48820","status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAASTqXPKS4QAAEAASURBV...
