### ISSUE TITLE
使用过程中遇到几个问题，想集中问下

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#183]
我在用这个做web 自动化，遇到几个问题想问下：
1.如何等待某个元素出现、或某个元素消失？再做下一步。
2.如何验证一个table 有多少行数据？判断某个table是否显示了
3.能否连接数据库做校验？

**Comment by zhoubhin** [comment]
@luoxi001713 
借楼问下，跑`source run.sh sample/test.spec.js`这条命令，报错：
[mochawesome] Generating report files...



  sample/test.spec : chrome
    1) "before all" hook

  0 passing (138ms)
  1 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1024:11)
      at _exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)




[mochawesome] Report saved to reports/index.html
[mochawesome] Report saved to reports/index.xml


(node:18626) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:18626) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:18626) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Chou/.npm/_logs/2017-12-07T05_45_04_823Z-debug.log

不知你有没有遇到

**Comment by luoxi001713** [comment]
@zhoubhin , 没有启动webdriver，在文件夹下先执行npm run server启动

**Comment by zhoubhin** [comment]
@luoxi001713 多谢，现在能跑起来了。

**Comment by zzuligy** [comment]
@luoxi001713 他们这个不知道。nightwatch 可以自己写你说的等待那个元素出现或消失这样的命令。我就写了一个waitElementClick，同理，这些命令都是js的也都可以写。uirecord的应该一样。

**Comment by MarkwwLiu** [comment]
@luoxi001713 請教一下 npm run server 該怎麼讓他跑起來？

> selenium-standalone start

module.js:540
    throw err;
    ^

Error: Cannot find module 'asynckit'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liuwenwei/node_modules/_form-data@2.1.4@form-data/lib/form_data.js:9:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 server: `selenium-standalone start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

我跑的時候會出現上面的問題

**Comment by zhoubhin** [comment]
@MarkwwLiu  提示未安装 asynckit这个模块，请先试下安装 asynckit这个模块

**Comment by Stngle** [comment]
> @luoxi001713 請教一下 npm run server 該怎麼讓他跑起來？
> 
> > selenium-standalone start
> 
> module.js:540
> throw err;
> ^
> 
> Error: Cannot find module 'asynckit'
> at Function.Module._resolveFilename (module.js:538:15)
> at Function.Module._load (module.js:468:25)
> at Module.require (module.js:587:17)
> at require (internal/module.js:11:18)
> at Object. (/Users/liuwenwei/node_modules/_form-data@2.1.4@form-data/lib/form_data.js:9:16)
> at Module._compile (module.js:643:30)
> at Object.Module._extensions..js (module.js:654:10)
> at Module.load (module.js:556:32)
> at tryModuleLoad (module.js:499:12)
> at Function.Module._load (module.js:491:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! uirecorderTest@1.0.0 server: `selenium-standalone start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the uirecorderTest@1.0.0 server script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 我跑的時候會出現上面的問題

运行 npm install ，再运行 npm run installdriver
