### ISSUE TITLE
关于代理模式下uirecorder无法录制外网用例的问题

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#184]
之前一直用uirecorder在局域网中录制用例，一切正常。

最近准备在外网录制一个用例做试验，发现使用uirecorder start启动起来的chrome浏览器输入外网地址(如百度)却无法打开。查看了一下该浏览器当时的代理，用的就是IE代理，而正常方式启动时是可以访问外网的。

不知道是不是要在哪个地方额外设置一下代理才能解决呢？

注：系统为Win7 64位，uirecorder版本2.5.35。

**Comment by yaniswang** [comment]
不对啊，uirecorder我默认都是设置为direct的啊，按道理应该不会读取IE的代理设置。

**Comment by stevobm** [comment]
额，我们这边是需要代理才能访问外网。
