### ISSUE TITLE
有没有办法多台机器并发执行，最后将报告整合在一起？

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#189]

**Comment by yaniswang** [comment]
不支持，而且也没这个必要。

可以通过部署f2etest webdriver或webdriver官方的 grid服务，将执行机的能力并行的提供给执行机，就可以提供高并发的能力。

至少提供30个并发是没问题的，并发的数量限制取决于CPU的限制。

**Comment by tuobabing** [comment]
这个问题在于合并报告吧，比如我想测试50张网页，报告想汇总一起，而不是去看50张报告
