### ISSUE TITLE
自动在其他浏览器进行测试刚记录的测试文件，失败

### ISSUE THREAD

**Issue by xlili** [alibaba/uirecorder#19]
先记录一小段测试（手动在天猫上面进行测试，自动记录），结束录制，用命令让其在其他的浏览器上自动进行测试（按照刚才的测试记录），失败了（不管是一条测试记录还是多条，0成功），跪求大神告知问题在哪儿，感激不尽！过两天就要进行测试了，出这种最基础的问题，急啊！！

**Comment by xlili** [comment]
看了下别人 的问题，有人有和我一样的问题，大神说WebDriver Server没弄好，但是根据网站下面的提示要下的东西很多啊，而且每一个链接点进去都有很多要下的？？求大神解释，是要全部点进去下下来放在ui recorder软件包里面吗？
How to deploy WebDriver Server

Selenium standalone server:

Download Selenium Server & IEDriverServer: http://selenium-release.storage.googleapis.com/index.html

Download ChromeDriver: http://chromedriver.storage.googleapis.com/index.html

Add the driver path to environment variable: PATH

Run selenium server: java -jar selenium-server-standalone-x.xx.x.jar
Selenium Grid: https://github.com/SeleniumHQ/selenium/wiki/Grid2

F2etest: https://github.com/alibaba/f2etest

**Comment by xlili** [comment]
运行的记录如下：
C:\Users\pc1>uirecorder start
? 测试用例文件名 test.spec.js
? 打开同步校验浏览器？ Yes

录制服务器监听在端口: 9765
校验浏览器已开启
录制浏览器已开启

------------------------------------------------------------------

  url: http://www.tmall.com
   √ 校验成功
  waitBody:
   √ 校验成功
  click: 背带裙 ( #mallSearch li:nth-child(1) > a, 23, 10, 0 )
   √ 校验成功
  mouseUp: 搜索 天猫 商品/品牌/... ( #mq, 93, 25, 0 )
   √ 校验成功
  click: 搜索 天猫 商品/品牌/... ( #mq, 93, 25, 0 )
   √ 校验成功
  sendKeys: dsf
   √ 校验成功
  click: 方向盘套 ( #ks-component919 b, 41, 5, 0 )

------------------------------------------------------------------

共录制6个步骤，其中校验通过: 6个，校验失败: 0个
录制用例已保存: test.spec.js

录制服务器已关闭
录制浏览器已关闭
校验浏览器已关闭

C:\Users\pc1>npm install mocha -g
Error: UNKNOWN: unknown error, mkdir 'D:\Program Files\nodejs\node_global'
    at Error (native)

Error: UNKNOWN: unknown error, mkdir 'D:\Program Files\nodejs\node_global'
    at Error (native)


C:\Users\pc1>mocha *.spec.js


  test.spec : chrome
    1) "before all" hook


  0 passing (1s)
  1 failing

  1) test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 192.168.31.199:80
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by yaniswang** [comment]
192.168.31.199:80

这个必需要保证是个webdriver server服务。具体webdriver server的部署请参考：http://uirecorder.com/
