### ISSUE TITLE
变量的value可以为带时间戳或一个随机数的值吗？如何在config.json中定义？

### ISSUE THREAD

**Issue by xinlai3698** [alibaba/uirecorder#191]
"uiname": "${+new Date()}",
"time": "{{+new Date()}}",

这几种写法都不对呀

**Comment by yaniswang** [comment]
录制过程中，更新变量时，支持写入变量，但是必需要符合JS的模板语法:http://www.infoq.com/cn/articles/es6-in-depth-template-string
