### ISSUE TITLE
升级到2.5.36, 录制选择commons的js文件后，一直在加载，无法录制

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#195]

**Comment by yaniswang** [comment]
![image](https://user-images.githubusercontent.com/970390/34026584-170a2372-e192-11e7-83b6-f7df84376f6d.png)

我试了下加载commons下的文件，正常的啊。

你把你的界面截个图看下。

**Comment by luoxi001713** [comment]
可能是我自己的问题，我卸载了又重新装了下好了。不好意思
