### ISSUE TITLE
想改写录制得到的脚本，可以怎么做，希望有指点

### ISSUE THREAD

**Issue by tuobabing** [alibaba/uirecorder#197]
我在做报表，想通过uirecorder做通用测试脚本，希望会自己改写录制脚本
1/这些it，insertVar async function都是什么函数语法定义在哪里查，想通过查找语法来找如何读写csv文件/比较文本这些功能的通用写法
2/比如说通过控件名去获取特定文本框值而不是通过div:nth-child(5)这样css的不确定度方式，
因为目前的报表格式比较相近，希望一份录制脚本通过改控件名即可通用到其他报表

**Comment by tuobabing** [comment]
css属性选择器可以用

**Comment by yaniswang** [comment]
1. 首先你要自己学会Nodejs语法
2. 其次要学下jwebdriver.com的API

**Comment by tuobabing** [comment]
感谢yaniswang
下面是我自己学习的心得
jwebdriver API
mocha
chai
百度以上3个学习很有收获
其次，百度录制脚本的最开始10行是很可行的思路，初学者摸到门槛了
