### ISSUE TITLE
按照文档安装，发现他停在了下载chrome driver的位置，导致安装不成功，怎么解决？

### ISSUE THREAD

**Issue by huijunhong00** [alibaba/uirecorder#199]
![image](https://user-images.githubusercontent.com/8819986/34333516-a7e1443c-e978-11e7-90a1-58b85edf2428.png)
每次安装都在这个位置停住不动了，导致安装不成功

我是按照说明文档执行的：

    Install NodeJs (version >= v7.x)
    Install chrome
    Install UI Recorder

        npm install uirecorder mocha -g

NodeJs版本：8.9.3
chrome:63.0.3239
现在就是执行到npm install uirecorder mocha -g的时候，他遇到了上面的问题，请问一下，这个我要怎么解决，让我能安装UI Recorder成功

**Comment by yaniswang** [comment]
不要用npm，用cnpm:http://npm.taobao.org/

**Comment by tuobabing** [comment]
手工下载安装这个包
