### ISSUE TITLE
命令：执行多浏览器自动测试，失败

### ISSUE THREAD

**Issue by xlili** [alibaba/uirecorder#20]
输入命令让其自动在多浏览器上测试刚记录的测试用例，失败了。偶尔进行测试的时候，明明是成功的测试但是说失败了，然后说成功了

**Comment by yaniswang** [comment]
能把具体的出错信息展示出来吗？

**Comment by xlili** [comment]
所有的输入、输入和报错信息都在下面了
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\pc1>uirecorder start
? 测试用例文件名 test.spec.js
? 打开同步校验浏览器？ Yes

录制服务器监听在端口: 9765
校验浏览器已开启
录制浏览器已开启

------------------------------------------------------------------

  url: http://www.tmall.com
   √ 校验成功
  waitBody:
   √ 校验成功
  click: 搜索 天猫 商品/品牌/... ( #mq, 57, 6, 0 )
   √ 校验成功
  sendKeys: bai{BACK_SPACE}{BACK_SPACE}{BACK_SPACE}{BACK_SPACE}白酒{ENTER}
   √ 校验成功
  waitBody:
   √ 校验成功
  click: 销量 ( #J_Filter a:nth-child(4), 26.5, 9, 0 )
   √ 校验成功
  waitBody:

------------------------------------------------------------------

共录制6个步骤，其中校验通过: 6个，校验失败: 0个
录制用例已保存: test.spec.js

录制服务器已关闭
录制浏览器已关闭
校验浏览器已关闭

C:\Users\pc1>npm install mocha -g
C:\Users\pc1\AppData\Roaming\npm\mocha -> C:\Users\pc1\AppData\Roaming\npm\node_
modules\mocha\bin\mocha
C:\Users\pc1\AppData\Roaming\npm\_mocha -> C:\Users\pc1\AppData\Roaming\npm\node
_modules\mocha\bin\_mocha
mocha@3.0.2 C:\Users\pc1\AppData\Roaming\npm\node_modules\mocha
├── browser-stdout@1.3.0
├── escape-string-regexp@1.0.5
├── diff@1.4.0
├── growl@1.9.2
├── json3@3.3.2
├── supports-color@3.1.2 (has-flag@1.0.0)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── lodash.create@3.1.1 (lodash._basecreate@3.0.3, lodash._isiterateecall@3.0
.9, lodash._baseassign@3.2.0)
├── debug@2.2.0 (ms@0.7.1)
└── glob@7.0.5 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.3, on
ce@1.4.0, inflight@1.0.5, minimatch@3.0.3)

C:\Users\pc1>npm install jwebdriver expect.js mocha-generators faker --save-dev
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
expect.js@0.3.1 node_modules\expect.js

mocha-generators@1.2.0 node_modules\mocha-generators
├── co@4.6.0
└── is-generator@1.0.3

faker@3.1.0 node_modules\faker

jwebdriver@1.0.13 node_modules\jwebdriver
├── xtend@2.0.3
├── promiseclass@0.9.5 (co@4.6.0)
├── node-zip@1.1.1 (jszip@2.5.0)
└── request@2.65.0 (aws-sign2@0.6.0, oauth-sign@0.8.2, tunnel-agent@0.4.3, fo
rever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-str
ingify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, qs@5.2.1, node-uuid@1.4.7,
combined-stream@1.0.5, mime-types@2.1.11, hawk@3.1.3, bl@1.0.3, http-signature@0
.11.0, har-validator@2.0.6, form-data@1.0.1)

C:\Users\pc1>mocha *.spec.js


  test.spec : chrome
    1) "before all" hook

  test.spec : 360
    2) "before all" hook

  test.spec : ie 11
    3) "before all" hook


  0 passing (34s)
  3 failing

  1) test.spec : chrome "before all" hook:
     Error: connect ETIMEDOUT 192.168.31.105:8080
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

  2) test.spec : 360 "before all" hook:
     Error: connect ECONNREFUSED 192.168.31.105:8080
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

  3) test.spec : ie 11 "before all" hook:
     Error: connect ECONNREFUSED 192.168.31.105:8080
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by yaniswang** [comment]
192.168.31.105:8080

这个服务必需要求是合法的WebDriver Server

部署教程请参考：https://github.com/alibaba/uirecorder#how-to-deploy-webdriver-server
