### ISSUE TITLE
有没有办法自动将失败的case重跑一遍，然后将2次的报告整合到一起

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#200]
这样会稳定一些，没找到太好的办法

**Comment by yaniswang** [comment]
http://mochajs.org/
![image](https://user-images.githubusercontent.com/970390/34348256-6e06d840-ea44-11e7-8031-09ffc61a855f.png)
Mocha有重试功能

**Comment by luoxi001713** [comment]
@yaniswang, 非常感谢，不过发现这个参数好像没用啊, 失败了不会重新执行
`mocha --reporter mochawesome-uirecorder --reporter-options copyShotOnlyFail=true  --retries 2 用例名`

**Comment by yaniswang** [comment]
放在最前面试试？
