### ISSUE TITLE
图片比对断言失败

### ISSUE THREAD

**Issue by xiaolangnani** [alibaba/uirecorder#201]
`acl/permissionHandle33 : chrome
    ✓ url: https://login-test.alibaba-inc.com/ssoLogin.htm?BACK_URL=http%3A%2F%2Facl-test.alibaba-inc.com%2F&APP_NAME=acl&CANCEL_CERT=true (1690ms)
    ✓ waitBody:  (545ms)
    ✓ click: domainAccount ( input[name="domainAccount"], 79, 15, 0 ) (678ms)
    ✓ sendKeys: tianheng.kth{TAB}
    ✓ click: 登 录 ( #App button > span, 21, 5, 0 ) (741ms)
    ✓ waitBody:  (548ms)
    1) expect: imgdiff, #node_j7zujuvh, below, 5

  6 passing (18s)
  1 failing

  1) acl/permissionHandle33 : chrome expect: imgdiff, #node_j7zujuvh, below, 5:
     TypeError: Cannot read property 'toString' of null
      at PromiseClass.<anonymous> (node_modules/_jwebdriver@2.2.3@jwebdriver/lib/browser.js:746:38)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/_co@4.6.0@co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

`

不太明白这个错误是怎么回事

**Comment by yaniswang** [comment]
你没有安装：GraphicsMagick
