### ISSUE TITLE
does uirecorder have brower headless option?

### ISSUE THREAD

**Issue by staekblw** [alibaba/uirecorder#202]
does uirecorder have brower headless option?
if it does, how should I config it?

thanks

**Comment by yaniswang** [comment]
You can run can with phantomjs

**Comment by staekblw** [comment]
thx, phantomjs works fine.

**Comment by rrprrp** [comment]
> You can run with phantomjs

phantomjs is deprecated
i add chromeOptions: { args: ['--enable-automation', '--headless'] } in script, but selenium-standalone get error.

**Comment by stephenwang1011** [comment]
> > You can run with phantomjs
> 
> phantomjs is deprecated
> i add chromeOptions: { args: ['--enable-automation', '--headless'] } in script, but selenium-standalone get error.

Where did you add this script?

**Comment by stephenwang1011** [comment]
> > You can run with phantomjs
> 
> phantomjs is deprecated
> i add chromeOptions: { args: ['--enable-automation', '--headless'] } in script, but selenium-standalone get error.
Worked well by using the below code :
`              let sessionConfig = Object.assign({}, webdriverConfig, {
                    'browserName': browserName,
                    'version': browserVersion,
                    'ie.ensureCleanSession': true,
                    'chromeOptions':{
                        'args': ['--enable-automation','--incognito','headless']
                    }
                }`
