### ISSUE TITLE
模态框中使用变量，获取不到，导致业务中的校验不通过？

### ISSUE THREAD

**Issue by xinlai3698** [alibaba/uirecorder#204]
![](http://7xii1v.com1.z0.glb.clouddn.com/QQ%E5%9B%BE%E7%89%8720180102195919.png)
链接地址： https://cn.vnnox.com/main/#/media  用户名： xinlai  密码：a123456-

**Comment by xinlai3698** [comment]
新建--》网页--》名称中我用已有的变量，录制时校验不通过，跟踪了下代码，拿不到变量的值

**Comment by mislaydu** [comment]
这种弹窗是iframe 你要动态获取才行的

**Comment by mislaydu** [comment]
it('拿好不谢', async function(){
        await driver
        .url('https://cn.vnnox.com/')
        .find('#userNname').val('xinlai')
        .find('#userPassword').val('a123456-')
        .find('//*[@id="myform"]/div[6]/button').sleep(300).click();

        await driver
        .wait('//*[@id="media"]/img').click()
        .wait('//*[@id="creatBtn"]').click()
        .wait('//*[@id="creatMediaBtn"]/ul/li[3]/a').click()
        .wait('#mediaName').val('媒体名')
        .wait('#mediaURL').val('网址dddddddddddddddd')
        .wait('#addWebRss').click();
    });

**Comment by xinlai3698** [comment]
thanks  帮助很大
