### ISSUE TITLE
uirecorder 录制后，再用macaca 回放，出错，求帮助~！~~~！

### ISSUE THREAD

**Issue by danwey** [alibaba/uirecorder#205]
sample/test.spec : chrome
    1) "before all" hook

  0 passing (882ms)
  1 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: the string "Not Found" was thrown, throw an Error :)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Stngle** [comment]
能否提供具体脚本案例和运行效果图？
