### ISSUE TITLE
async函数中使用location.reload()，超时时间与设置的asyncScriptTimeout不同

### ISSUE THREAD

**Issue by luoxlgh** [alibaba/uirecorder#207]
某些页面没有刷新按钮，使用 location.reload() 刷新时没有达到 asyncScriptTimeout 就报 timeout 错误。
有什么好方法解决这种问题呢？

**Comment by weiquzwq** [comment]
async函数可以带await来阻塞挂起，异步方法timeout的起点是函数启动的时候

**Comment by luoxlgh** [comment]
脚本里执行reload是不是会影响脚本的asyncScriptTimeout 设置？
