### ISSUE TITLE
「Mac」uirecorder start命令後沒有生成 test.spec.js

### ISSUE THREAD

**Issue by zhoufan879** [alibaba/uirecorder#21]
執行命令
`uirecorder start`

? 测试用例文件名 test.spec.js
? 打开同步校验浏览器？ Yes

_**目錄下，並沒有生成 test.spec.js 文件**_

求解，謝謝~

**Comment by zhoufan879** [comment]
不好意思，我自己的問題；  應該加  sudo ...

**Comment by yaniswang** [comment]
嗯，MAC和linux由于权限问题，必需要加sudo
