### ISSUE TITLE
UI Recoder 录制完Chrome网页，回放出错。

### ISSUE THREAD

**Issue by kingkong2013** [alibaba/uirecorder#210]
我的Mac开发环境：

macaca-doctor version: 2.0.4

Node.js checklist:

node env: /Users/xxxx/.nvm/versions/node/v9.3.0/bin/node
node version: v9.3.0

iOS checklist:

Xcode Command Line Tools is ready, version: 2347.
xcodebuild version: 9.2
iproxy[usbmuxd] is installed at: /usr/local/bin/iproxy
ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
carthage is installed, version: 0.27.0

Android checklist:

JAVA version is 1.8.0_144
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
ANDROID_HOME is set to /Users/xxxx/Documents/android-sdk-macosx
Platforms is set to /Users/xxxx/Documents/android-sdk-macosx/platforms/android-26
ADB tool is set to /Users/xxxx/Documents/android-sdk-macosx/platform-tools/adb
gradle is installed, version: 4.2

Installed driver list:

android: 2.0.45
electron: 1.1.19
ios: 2.0.30

Chrome版本：Version 63.0.3239.108 (Official Build) (64-bit)

UI Recoder版本：v2.5.36

录制网页成功后，重放报错：

[mochawesome] Generating report files...

  test.spec : chrome
    1) "before all" hook

  0 passing (44ms)
  1 failing

  1) test.spec : chrome "before all" hook:
     Error: the string "Internal Server Error" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at Runner.failHook (node_modules/_mocha@3.1.2@mocha/lib/runner.js:273:8)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:326:16
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at Promise.<anonymous> (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

[mochawesome] Report saved to reports/index.html
[mochawesome] Report saved to reports/index.xml

**Comment by weiquzwq** [comment]
没有启动selenium-standlone吧
![image](https://user-images.githubusercontent.com/17486636/34557354-f03be760-f174-11e7-8e26-77ba4a01b898.png)

**Comment by kingkong2013** [comment]
@weiquzwq, 你是对的，我忘记起服务了，谢谢帮忙。
