### ISSUE TITLE
测试语句的注释

### ISSUE THREAD

**Issue by zzuligy** [alibaba/uirecorder#213]
现在测试用例打印的名字都是自动生成的名字，这些名字和jira对应测试用例的语义不对照。我是在工具条上面加了一个注释的按钮。这样可以达到生成的测试用例更语义化的目的。当用例出错的时候能快速明白这条用例的执行目的。这样是否普遍有意义？

**Comment by mislaydu** [comment]
没听懂

**Comment by zzuligy** [comment]
就是现在自动生成的用例也就是it，前面的名字没有语义。能不能加一个让it更有语义的东西。
例如it('测试登录',function(){}).

**Comment by mislaydu** [comment]
你录完不改脚本的吗？

**Comment by zzuligy** [comment]
这个工具就是越工具化越好。发展的最终目的就是完全的自动化测试，所以对脚本改动越少越好。

**Comment by yaniswang** [comment]
目前的操作是原子化的，所以每个步骤的it标题，就是描述在做什么操作。

你说的：测试登录，这种是封装后的多步操作，显然不太可能通过录制来实现
