### ISSUE TITLE
chromedriver bin file no existed, please reinstall uirecorder again.

### ISSUE THREAD

**Issue by phoenix110** [alibaba/uirecorder#214]
1.执行uirecorder init，初始化文件件。
2.执行uirecorder命令，报错。
`Description = Invalid namespace`
`chromedriver bin file no existed, please reinstall uirecorder again.` 
环境：
npm 5.4.2
chrome 63.0.3239.132（64位）

初步解析：
1.刚开始以为是因为本地chrome是绿色版，所以重新下载最新chrome后，安装。
结果：失败。
2.通过npm install chromedriver安装chromedriver。
结果：失败。

**Comment by yaniswang** [comment]
使用cnpm来安装，国内被墙了

**Comment by zhengcaiyunjob** [comment]
how to solve this problem, I also have this difficulty.

**Comment by mjc224000** [comment]
how to solve this problem, I also have this difficulty.

**Comment by LiPinghai** [comment]
换node8试试
