### ISSUE TITLE
ie 10图片断言失败

### ISSUE THREAD

**Issue by wandm** [alibaba/uirecorder#220]
selenium-server-standalone：2.53.1，uirecorder：2.5.36，ie：10，图片断言失败，chrome63、firefox46成功，错误信息如下：
  1) cases/pic_monitor.spec : ie 10 expect: imgdiff, #monitorArea li:nth-child(1
) > div:nth-child(2), below, 5:
     TypeError: Cannot read property 'toString' of null
      at PromiseClass.<anonymous> (node_modules\_jwebdriver@2.2.4@jwebdriver\lib
\browser.js:760:38)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules\_co@4.6.0@co\index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by yaniswang** [comment]
没有安装依赖GraphicsMagick

**Comment by wandm** [comment]
GraphicsMagick已经安装了，需要做什么配置吗

**Comment by wandm** [comment]
背景：为了支持firefox，将selenium-server-standalone版本降至2.53.1，firefox46
selenium-server-standalone：2.53.1，鼠标悬停在ie10中表现不稳定
将selenium-server-standalone版本改为3.8.1，图片断言就通过了，没有上面的报错，鼠标悬停有改善，但是这样有一个问题就是firefox无法启动，会启动chrome或者执行命令错误
selenium-server-standalone版本低，ie10中脚本执行有问题；版本高了，firefox又执行不了，请教该如果解决？

**Comment by wandm** [comment]
尝试了GraphicsMagick32/64位，Q8/Q16，主要版本是1.3.28，其他版本1.3.27和1.3.12，ie测试中都是如上的错误，命令行node内运行发现是截图失败，但是chrome都是正常的，麻烦大神帮忙

**Comment by yaniswang** [comment]
从报错信息来看，肯定是GraphicsMagick的库没定位到，是不是PATH路径没设置正确？

**Comment by wandm** [comment]
path是安装时自动设定的，命令行中，gm命令是可以的，如果是path问题，那chrome也应该有问题吧
