### ISSUE TITLE
执行录制脚本时，ie 10启动失败，启动了chrome

### ISSUE THREAD

**Issue by wandm** [alibaba/uirecorder#221]
selenium-server-standalone：3.8.1，uirecorder：2.5.36，ie：10
执行脚本时ie10没有启动（安全模式已更改），确启动了chrome
server侧日志如下：可以看出待启动浏览器名为internet explor
er，但同时携带有 chromeOptions参数。
10:40:46.478 INFO - /session: Executing POST on /session (handler: BeginSession)

10:40:46.482 INFO - Capabilities are: Capabilities {browserName: internet explor
er, chromeOptions: {args: [--enable-automation]}, ie.ensureCleanSession: true, v
ersion: 10}
10:40:46.485 INFO - Capabilities {browserName: internet explorer, chromeOptions:
 {args: [--enable-automation]}, ie.ensureCleanSession: true, version: 10} matche
d class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org
.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73) on
port 10026
Only local connections are allowed.
将录制的脚本中，如下代码注释掉，ie10成功启动
//'chromeOptions': {
//    'args': ['--enable-automation']
//}
另外，此问题在selenium-server-standalone版本为2.53.1时没有发生。

**Comment by wikeyi** [comment]
firefox和ie都这么处理的？

**Comment by wikeyi** [comment]
我遇到的问题是只能打开chrome，其他的浏览器都无法打开，不知道怎么解决呢；

**Comment by sunqi513** [comment]
我也是

**Comment by ghostMozi** [comment]
我的也是这个问题，我怀疑除了这个配置是不是有其他的设置啊。
![image](https://user-images.githubusercontent.com/39260448/39995697-9db6ea8e-57af-11e8-8978-d29c427155af.png)
或者browser这块填写浏览器需要标准的名称，和path指向的driver要一致

**Comment by teresa415** [comment]
回放脚本的时候，三次打开的都是谷歌浏览器，但是设置的是谷歌和ie11还有火狐，为什么没有打开ie11和火狐，是哪里设置的不对么？？？
![image](https://user-images.githubusercontent.com/39977555/41706028-5017ccfe-756d-11e8-8b61-7009f60e85a7.png)

**Comment by liushengxian** [comment]
DELETE "Chrome Options" works for me!

**Comment by suuzee** [comment]
selenium-server-standalone-2.53.1 is works for me.

**Comment by Stngle** [comment]
更新至最新版本，重新录制
