### ISSUE TITLE
脚本录制后跑谷歌浏览器报错

### ISSUE THREAD

**Issue by zhangjianpinghik** [alibaba/uirecorder#222]
我是用npm run installdriver安装的驱动, 然后npm run server启动驱动 ,录制测试chrome的脚本后 执行脚本报错:
[mochawesome] Generating report files...

  sample/test.spec : chrome
    1) "before all" hook

  0 passing (12s)
  1 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: the string "unknown error: cannot get automation extension\nfrom unk
nown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapna
hmbfebeb/_generated_background_page.html\n  (Session info: chrome=64.0.3282.119)
\n  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2
cfd9),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not prov
ide any stacktrace information)\nCommand duration or timeout: 10.03 seconds\nBui
ld info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'\nSy
stem info: host: 'PC1-ZJPYFCS1', ip: '192.168.56.1', os.name: 'Windows 7', os.ar
ch: 'amd64', os.version: '6.1', java.version: '1.7.0_80'\nSession ID: 2cd728fd7c
eaebb89d111db4812a2cc9\nDriver info: org.openqa.selenium.chrome.ChromeDriver\nCa
pabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserNa
me=chrome, chrome={userDataDir=C:\\Users\\ZHANGJ~1\\AppData\\Local\\Temp\\scoped
_dir15284_25223, chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb3
07f7d2cfd9)}, networkConnectionEnabled=false, unexpectedAlertBehaviour=, rotatab
le=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=64.
0.3282.119, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled
=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false
, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCa
cheEnabled=false, takesScreenshot=true}]" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at Runner.failHook (node_modules\_mocha@3.1.2@mocha\lib\runner.js:273:8)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:326:16
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at Promise.<anonymous> (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:35
4:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 paralleltest: `mocha-parallel-tests "*/**/*.spec.j
s" --reporter mochawesome-uirecorder --max-parallel 5 --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 paralleltest script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by Stngle** [comment]
从报错日志看应该是 chrome-extension 加载不到导致的，估计是安装过程的问题。
环境搭建参考文档：https://www.yuque.com/artist/uirecorder/zslbnp
