### ISSUE TITLE
测试用例回放时，报chrome "before all" hook异常

### ISSUE THREAD

**Issue by iez1784** [alibaba/uirecorder#226]
windows 10 环境

 sample/test.spec : chrome
    1) "before all" hook

  0 passing (14s)
  1 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: the string "unknown error: cannot get automation extension\nfrom unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html\n  (Session info: chrome=64.0.3282.167)\n  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.10586 x86_64)" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at Runner.failHook (node_modules\_mocha@3.1.2@mocha\lib\runner.js:273:8)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:326:16
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at Promise.<anonymous> (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml

(node:3324) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample\test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yaniswang** [comment]
你的chromedriver版本太旧了，更新下：https://chromedriver.storage.googleapis.com/2.35/notes.txt

**Comment by iez1784** [comment]
感谢感谢。升级最新版本后可以了。 谢谢
