### ISSUE TITLE
Mobile open failed, please check macaca config. Internal Server Error

### ISSUE THREAD

**Issue by syberkitten** [alibaba/uirecorder#227]
Hi

Getting error everytime I try to start with am APK (OSX and Android) running:
```
uirecorder start --mobile
```
getting this output:

? Test spec file name: sample/test.spec.js
? App Path (extensions: apk, app, zip): /Users/test/home/test.apk

Recorder server listen on: 57621
Mobile open failed, please check macaca config. Internal Server Error

server gives this error (was started macaca server --port 4444)
```
 Error: Command failed: /Users/me/Library/Android/sdk/platform-tools/adb -s 5H12GQ3LDQDLCIU8 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing
```

macaca doctor report:

```
macaca-doctor version: 2.0.5


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.6.0 lower than v8.9.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.28.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/liam/Library/Android/sdk`
  Platforms is set to `/Users/liam/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/liam/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.3

  Installed driver list:

  android: 2.0.46
  ios: 2.0.30
```

**Comment by yaniswang** [comment]
The error message is : ` Error: Command failed: /Users/me/Library/Android/sdk/platform-tools/adb -s 5H12GQ3LDQDLCIU8 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing
`

You can push issue here: https://github.com/alibaba/macaca/issues

**Comment by syberkitten** [comment]
@yaniswang Thanks, I've opened a similar issue at [macaca](https://github.com/alibaba/macaca/issues/790#issuecomment-368800860)
