### ISSUE TITLE
chrome浏览器版本和chromedriver不兼容

### ISSUE THREAD

**Issue by nfntt** [alibaba/uirecorder#231]
情况是这样的：
我录制时没有报错，但是执行时报错，报错见截图。
我的chrome版本是版本 65.0.3325.146（正式版本），配套的chromedriver应该是2.36版本，你们默认下载的是2.33版本，然后我自己下载了chromedriver的2.33版本，并放到了D:\xxx\xxx\Roaming\npm\node_modules\uirecorder\node_modules\chromedriver\lib\chromedriver下，请问还需要做什么配置才能起让chromedriver2.36起作用，现在依然报错，报错的chromedriver版本是2.33

![chromedriver](https://user-images.githubusercontent.com/19464077/37275314-ca44257a-2619-11e8-8d93-e4b0c705dca2.png)

**Comment by jack-github** [comment]
哪位大神回答下

**Comment by Stngle** [comment]
最新版本已经没有这个问题
