### ISSUE TITLE
2.5.40 chrome 浏览器加载不出APP录制控件

### ISSUE THREAD

**Issue by jack-github** [alibaba/uirecorder#236]
Google Chrome 已是最新版本
版本 65.0.3325.162（正式版本） （64 位）

chromedriver@2.36.0

  macaca-doctor version: 2.0.10

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.9.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.28.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/jack/Library/Android/sdk`
  Platforms is set to `/Users/jack/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/jack/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.5

  Installed driver list:

  android: 2.0.47
  chrome: 1.0.7
  ios: 2.0.30

**Comment by yaniswang** [comment]
这个问题应该已经修复了，安装新版再试试
