### ISSUE TITLE
PC上录制是否能实现点按拖拽？

### ISSUE THREAD

**Issue by mijiawei** [alibaba/uirecorder#237]

**Comment by yaniswang** [comment]
本来就支持拖拽录制的

**Comment by mijiawei** [comment]
恩，确实看见说明中有说到“拖放”
是一个需要对元素点击长按拖拽释放的行为
看了下`click+悬停+mousemove`无法完成，没找到command.js中有drag & drop的API

能否提点下，如何操作？
> 我用了这个[sample](http://www.zhangxinxu.com/study/201102/html5-drag-and-drop.html)

**Comment by yaniswang** [comment]
其实本身是支持的，只不过因为拖放网页的前端实现细节不一样，会导致目前生成的代码无法兼容所有情况。

你可以试试别的一些拖放，大部分是能兼容的，比如：https://ditu.baidu.com/

**Comment by mijiawei** [comment]
感谢回复。
-------------
属脚本的兼容问题
