### ISSUE TITLE
UIrecorder start时提示chromedriver bin file no existed,

### ISSUE THREAD

**Issue by cxyhappy8** [alibaba/uirecorder#239]
chrome版本为65.0.3325.181（正式版本） （64 位），chromedriver版本为2.37，已放在python2.7目录下，但每次UIrecorder start时都会提示chromedriver bin file no existed, please reinstall uirecorder again.
![image](https://user-images.githubusercontent.com/37832436/37959829-a1d57908-31e6-11e8-853b-c5d6fd078a10.png)

**Comment by yaniswang** [comment]
用cnpm来安装，不要用npm官方的，会被墙掉

**Comment by Victory-Over** [comment]
我也遇到这个问题，有解决办法么

**Comment by LiPinghai** [comment]
@yaniswang 不是这个原因，确实存在安装chromedriver 但启动报错的情况

**Comment by LiPinghai** [comment]
换node8试试

**Comment by yumeili2020** [comment]
My chromedriver was removed by antivirus software,when I recovered,UIRecorder works well.
