### ISSUE TITLE
Cannot read property 'sessionId' of undefined

### ISSUE THREAD

**Issue by akhuting** [alibaba/uirecorder#24]
Cannot read property 'sessionId' of undefined
这个是个什么错误

**Comment by yaniswang** [comment]
你的测试用例是哪个版本的uirecorder生成的？

查看版本方法：uirecorder -V

**Comment by akhuting** [comment]
1.3.0 只有360浏览器有这个问题

**Comment by yaniswang** [comment]
360你是用f2etest部署的？

**Comment by akhuting** [comment]
是的，不管是2003还是2008 360chrome都崩溃，浏览器云能打开，就是jwebdriver打不开

**Comment by yaniswang** [comment]
奇怪，我的环境里，360的这两个浏览器倒是正常的

**Comment by akhuting** [comment]
能否提供下你的驱动版本号？我怀疑是chromedriver问题，有的版本能打开，但是不能自动打开页面，有的版本直接sessionid undefined，有的版本直接崩溃crash

**Comment by akhuting** [comment]
还有，我用的最新的360chrome。。。。。。

**Comment by yaniswang** [comment]
ChromeDriver 2.20.353145

**Comment by yaniswang** [comment]
问题咋样了？解决了吗？
