### ISSUE TITLE
录制脚本后运行提示connectECONNREFUSED 127.0.0.1:4444

### ISSUE THREAD

**Issue by sunqi513** [alibaba/uirecorder#242]
录制脚本后运行提示connectECONNREFUSED 127.0.0.1:4444。然后我npm run server 提示Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/
id/selenium/GridLauncherV3 : Unsupported major.minor version 52.0

**Comment by yaniswang** [comment]
你的java版本太低了，升级下

**Comment by sunqi513** [comment]
你们的群11779932(加入验证：UIRecorder录制) 也没法加入啊，无法搜索群

**Comment by yaniswang** [comment]
可以的啊，很多人加入了
