### ISSUE TITLE
如何处理连击事件

### ISSUE THREAD

**Issue by KatherineFanfan** [alibaba/uirecorder#243]
app中一个按钮要连续点击多次, 可以实现录制吗?

**Comment by yaniswang** [comment]
可以直接双击，就可以录制doubleclick事件

**Comment by yaniswang** [comment]
长按住某个按钮，就可以录制longtouch

**Comment by KatherineFanfan** [comment]
doubleclick好用的,我遇到的场景是: 需要连续多次点击按钮,进入设置界面,这一事件如何录制?谢谢~

**Comment by yaniswang** [comment]
这个目前不支持，你需要的是几次点击？

**Comment by KatherineFanfan** [comment]
连续点击三次以上, 最好可以设置参数.这个feature也可以用于发现隐藏按钮上..
