### ISSUE TITLE
uirecorder安装问题，win10系统：未能加载 Visual C++ 组件“VCBuild.exe

### ISSUE THREAD

**Issue by alvin558** [alibaba/uirecorder#246]
C:\Users\Admin\AppData\Roaming\npm\node_modules\uirecorder\node_modules\websocket>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Stu
dio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [C:\Users\Admin\AppData\Roaming\npm\node_modules\uirecorder\node_modules\we
bsocket\build\binding.sln]
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Stu
dio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [C:\Users\Admin\AppData\Roaming\npm\node_modules\uirecorder\node_modules\we
bsocket\build\binding.sln]
+ uirecorder@2.5.40
added 379 packages in 77.982s

**Comment by alvin558** [comment]
C:\Users\Admin>uirecorder start --mobile
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.40

Official Site: http://uirecorder.com
------------------------------------------------------------------

config.json file search failed, please init first!

**Comment by yaniswang** [comment]
websocket的安装不是那么重要，应该是依赖的依赖，应该并不影响uirecorder功能的使用。
