### ISSUE TITLE
录制安卓脚本，Chrome启动后控制台报错，一直无法启动录制控件

### ISSUE THREAD

**Issue by Felix-DHE** [alibaba/uirecorder#258]
__  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.41

Official Site: http://uirecorder.com
------------------------------------------------------------------

? 测试脚本文件名: sample/test.spec.js
? App路径 (扩展名: apk, app, zip): E:\software\ayh.apk

录制服务器监听在端口: 60116

DevTools listening on ws://127.0.0.1:12779/devtools/browser/09de6d2c-c512-4278-880e-9afa05cd0fae
(node:8968) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PromiseClass.<anonymous> (D:\nodejs\node_global\node_modules\uirecorder\lib\start.js:378:46)
    at done (D:\nodejs\node_global\node_modules\uirecorder\node_modules\promiseclass\lib\promiseclass.js:65:51)
    at Promise.<anonymous> (D:\nodejs\node_global\node_modules\uirecorder\node_modules\jwebdriver\lib\mixpromise.js:71:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:8968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
录制浏览器已开启

**Comment by yaniswang** [comment]
你的config.json不是标准的格式，修改下

**Comment by Felix-DHE** [comment]
@yaniswang  感谢，问题已解决，macaca server 启动的端口号指定错了。
