### ISSUE TITLE
【提问】连接多台真机及模拟器的情况下，录制功能是否支持指定设备进行录制？目前默认的是使用设备列表中的第一台设备。

### ISSUE THREAD

**Issue by Felix-DHE** [alibaba/uirecorder#260]
@yaniswang 烦请抽空看下这个问题，如果可以指定设备，理论上就支持使用远程真机录制了。

**Comment by yaniswang** [comment]
![image](https://user-images.githubusercontent.com/970390/40292209-6d6dd5c0-5cfc-11e8-86d2-b49b15f7980f.png)

**Comment by Felix-DHE** [comment]
@yaniswang 录制的时候这个设置不会生效，依旧选取的设备列表中第一台设备，执行测试的时候设置这个是生效的。那么指定录制设备有其他方法么？
