### ISSUE TITLE
iframe有没有办法通过name等定位，因为我们的iframe id经常会变化

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#264]

**Comment by ciuji** [comment]
可以选择关掉特定属性

**Comment by luoxi001713** [comment]
@ciuji，没明白，什么意思？

**Comment by ciuji** [comment]
@luoxi001713 [如何解决属性值不稳定问题？](https://github.com/alibaba/uirecorder/blob/master/doc/zh-cn/pc-advanced.md#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E5%B1%9E%E6%80%A7%E5%80%BC%E4%B8%8D%E7%A8%B3%E5%AE%9A%E9%97%AE%E9%A2%98)
你说的是这个问题吗
