### ISSUE TITLE
windows环境下uirecorder init后无反应

### ISSUE THREAD

**Issue by ciuji** [alibaba/uirecorder#266]
uirecorder init后就一直卡在Start install project dependencies...的状态
![image](https://user-images.githubusercontent.com/17194547/42199756-c7a2cc20-7ec2-11e8-86a6-d1de4ba8863b.png)
输入uirecorder start后也是处于开着的停滞状态。

请问这是我环境配置的问题吗？还是网络代理的问题？

## 【更新】已解决

node版本问题。我的node版本为v10，降级后就成功了。

**Comment by TerryGee** [comment]
NodeJs换个版本，建议换到NodeJs v9再试试，最新版遇到同样的问题。
同时注意一下，分区是否为FAT32，如果是，也有可能会遇到这样的问题。
