### ISSUE TITLE
run.bat 启动脚本时候报错

### ISSUE THREAD

**Issue by BensonMax** [alibaba/uirecorder#268]
1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:5555
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml

(node:348) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:348) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:348) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample\test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-07-14T02_17_47_968Z-debug.log

**Comment by Stngle** [comment]
是否本地开启 selenium-server
