### ISSUE TITLE
 DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by zhangjian2xxx** [alibaba/uirecorder#272]
![_20180824104114](https://user-images.githubusercontent.com/41861232/44562053-46cd8680-a78a-11e8-8ca8-f6d7c10557ab.png)

**Comment by alicegu2009** [comment]
请问这个问题有解决方案吗？ 我也遇到了这个问题：
![2019-05-16_11-57-24](https://user-images.githubusercontent.com/7711216/57825604-2939c480-77d2-11e9-8a33-27193368ecd9.png)

**Comment by Stngle** [comment]
> 请问这个问题有解决方案吗？ 我也遇到了这个问题：
> ![2019-05-16_11-57-24](https://user-images.githubusercontent.com/7711216/57825604-2939c480-77d2-11e9-8a33-27193368ecd9.png)

chrome 浏览器重新安装，使用默认路径
