### ISSUE TITLE
运行报错。

### ISSUE THREAD

**Issue by zhangjian2xxx** [alibaba/uirecorder#275]
![image](https://user-images.githubusercontent.com/41861232/44628271-01b67980-a96f-11e8-813c-dae4fa47d784.png)

**Comment by kobe1996** [comment]
没有启动Selenium-sever。

**Comment by yaniswang** [comment]
你是基于f2etest跑吗？可能是你没有写apikey等参数

**Comment by kobe1996** [comment]
@yaniswang  run.bat运行脚本时报错，npm ERR! missing script: singletest，重装试过多次未解决，请问是什么原因？谢谢

**Comment by yalishanyi** [comment]
启动Selenium-sever 之后不要关掉
