### ISSUE TITLE
代码里混入了只有MacOS才能打出来的Escape字符

### ISSUE THREAD

**Issue by Deliay** [alibaba/uirecorder#281]
如图
![ss.00015060](https://user-images.githubusercontent.com/5661435/46055775-237a6a80-c180-11e8-9299-54bdc0b58904.png)

see
https://github.com/alibaba/uirecorder/blob/6d4e57966a470a90670c135dc5b0a1f2414eb7dd/bin/uirecorder#L23

MacOS上这个字符可输入但是不可见。
建议你们升级Linux/Windows/FreeBSD/ChromeOS/卡西欧计算器等其他操作系统开发，免受苹果优化的荼毒。

**Comment by miracletan2008** [comment]
这段代码是删除一些特殊字符，这个是有用的 0x1b，ASC码的ESC键
