### ISSUE TITLE
chromeOptions中设置的mobileEmulation无效

### ISSUE THREAD

**Issue by sheeeeep** [alibaba/uirecorder#282]
![image](https://user-images.githubusercontent.com/16912701/46074235-93591700-c1b9-11e8-863c-4c80a0c32ac9.png)

参考[webdriver文档](http://chromedriver.chromium.org/mobile-emulation)设置的mobileEmulation值没有生效

**Comment by sheeeeep** [comment]
这里是我搞错了，这里的设置是在运行脚本的时候执行的，会生效。
所以问题是录制的时候应该在哪里设置userAgent呢？

**Comment by Stngle** [comment]
目前配置文件没有这个配置字段，后边会增加 config.json 配置字段
