### ISSUE TITLE
UI Recrder  跑上传图片测试用例的时候失败是什么原因？？？

### ISSUE THREAD

**Issue by fsc666** [alibaba/uirecorder#285]
![2018-09-29 7 15 20](https://user-images.githubusercontent.com/43699007/46245173-390bc080-c41c-11e8-9779-f1583bdafc60.png)
![2018-09-29 7 15 37](https://user-images.githubusercontent.com/43699007/46245179-445eec00-c41c-11e8-8c37-d56844d1cf0a.png)

**Comment by Stngle** [comment]
先运行 npm run server，再在另一个终端窗口运行 source run.sh
