### ISSUE TITLE
修改了hrome-extension插件的html页面，重新构建，出错被屏蔽了，怎么回事？

### ISSUE THREAD

**Issue by LLLucian** [alibaba/uirecorder#287]
donpflclacamajgbnhgjgkkapnlfahlj 已被屏蔽
对服务器的请求已遭到某个扩展程序的阻止。
尝试停用扩展程序。
ERR_BLOCKED_BY_CLIENT

**Comment by Stngle** [comment]
是否开启了屏蔽广告之类的 chrome extension

**Comment by LLLucian** [comment]
@Stngle 没有啊，原来项目里的uirecorder.crx可以，重新改动一些html的，再用buildcrx.bat构建就出错了

**Comment by yaniswang** [comment]
每次打包，都会生成新的ID

**Comment by csudevinduan** [comment]
请问这个字母序列在哪里查看？我重新编译没有看到这个
