### ISSUE TITLE
无法定位图片，录制脚本失败

### ISSUE THREAD

**Issue by AceHZH** [alibaba/uirecorder#289]
网页正常，但是网页添加脚本的时候，录制过程正常点击，但是校验浏览器无法同步，报超时错误，实际根本没有超时，脚本回放报同样的错误。
![01](https://user-images.githubusercontent.com/43890917/46863286-973b9900-ce49-11e8-8c36-447faafd22d3.png)
![02](https://user-images.githubusercontent.com/43890917/46863291-9a368980-ce49-11e8-8915-42562d4d9055.png)
![03](https://user-images.githubusercontent.com/43890917/46863292-9b67b680-ce49-11e8-85e0-0d783a26f212.png)
![04](https://user-images.githubusercontent.com/43890917/46863293-9c98e380-ce49-11e8-982f-da5b5d43a5d7.png)

**Comment by Stngle** [comment]
脚本回放是基于 selenium-server 提供的 webdriver 服务进行测试的，跟真实浏览器操作会存在差异。这个问题需要运行回放的时候排查，定位 timeout 原因。
