### ISSUE TITLE
修改了config.json里的webdriver为firefox,但是脚本回放依然使用chrome

### ISSUE THREAD

**Issue by AceHZH** [alibaba/uirecorder#293]
![01bug](https://user-images.githubusercontent.com/43890917/47137092-35b37880-d2e8-11e8-8934-3dcfbcba98f1.png)
![02bug](https://user-images.githubusercontent.com/43890917/47137099-3946ff80-d2e8-11e8-9862-bc08e94a6932.png)
![03bug](https://user-images.githubusercontent.com/43890917/47137101-3a782c80-d2e8-11e8-8e1e-325cff850e41.png)

**Comment by Stngle** [comment]
新版本已经 fixed

**Comment by CandyZhai** [comment]
@Stngle ui recorder是3.4.3版本的，还是报错。安装的是最新版。
