### ISSUE TITLE
WIN10中无法安装uirecorder

### ISSUE THREAD

**Issue by shanxueyi** [alibaba/uirecorder#297]
首先必须使用node8！！！（我使用node10版本搞了好久都有问题）
执行npm install uirecorder mocha -g后
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。
安装最新版本build-tools
npm install --global --production windows-build-tools
然后设置msvs_version 为对应版本如 C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
npm config set msvs_version 2017 --global
自己搞了好久才解决 希望优化一下

**Comment by shanxueyi** [comment]
在这里记录下  也给遇到同样问题的伙伴给点解决方案

**Comment by Stngle** [comment]
使用的是 cnpm 还是 npm？

**Comment by shanxueyi** [comment]
> 使用的是 cnpm 还是 npm？

npm
