### ISSUE TITLE
最新版v2.5.45 浏览器默认1024*768, 想改成maximize,输入无效

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#298]

**Comment by Stngle** [comment]
可以先临时将 xxx.spec.js 文件内 .windowSize(1024, 768) 修改为 .maximize()，下个版本将会做输入修改的功能支持

**Comment by luoxi001713** [comment]
> 可以先临时将 xxx.spec.js 文件内 .windowSize(1024, 768) 修改为 .maximize()，下个版本将会做输入修改的功能支持

谢谢。是不是遇到不能最大化的情况，才改成默认分辨率的。我发现我改成maximize会报错，我是chrome, standalone是最新的2.43，chrome浏览器最新的。

**Comment by Stngle** [comment]
> > 可以先临时将 xxx.spec.js 文件内 .windowSize(1024, 768) 修改为 .maximize()，下个版本将会做输入修改的功能支持
> 
> 谢谢。是不是遇到不能最大化的情况，才改成默认分辨率的。我发现我改成maximize会报错，我是chrome, standalone是最新的2.43，chrome浏览器最新的。

是的，新版的standalone发现了兼容问题

**Comment by luoxi001713** [comment]
> > > 可以先临时将 xxx.spec.js 文件内 .windowSize(1024, 768) 修改为 .maximize()，下个版本将会做输入修改的功能支持
> > 
> > 
> > 谢谢。是不是遇到不能最大化的情况，才改成默认分辨率的。我发现我改成maximize会报错，我是chrome, standalone是最新的2.43，chrome浏览器最新的。
> 
> 是的，新版的standalone发现了兼容问题

那是不是只能降低浏览器版本，不升级standalone，才能解决这个问题呢

**Comment by Stngle** [comment]
> > > > 可以先临时将 xxx.spec.js 文件内 .windowSize(1024, 768) 修改为 .maximize()，下个版本将会做输入修改的功能支持
> > > 
> > > 
> > > 谢谢。是不是遇到不能最大化的情况，才改成默认分辨率的。我发现我改成maximize会报错，我是chrome, standalone是最新的2.43，chrome浏览器最新的。
> > 
> > 
> > 是的，新版的standalone发现了兼容问题
> 
> 那是不是只能降低浏览器版本，不升级standalone，才能解决这个问题呢

建议是设置宽度及高度大小解决这个问题，maximize()的兼容问题看issue不少人遇到过这个情况，需要 selenium 修复
