### ISSUE TITLE
当测试为多个时，怎么规定测试的执行顺序？

### ISSUE THREAD

**Issue by llxiao** [alibaba/uirecorder#3]
当测试中有多个业务逻辑，需要创建多个测试，每个测试的执行结果，和测试报告结果，有没有相关的介绍？

**Comment by yaniswang** [comment]
mocha *.spec.js
会批量执行文件夹中所有的测试用例。
测试报告目前没有做。

你所指的测试报告具体是个什么样的形式？

**Comment by llxiao** [comment]
mocha *.spec.js
是会执行所有的测试用例，如果包含多个流程比如：（1）登录（2）登录后修改个人信息
需要规定测试执行顺序
业务流程多了以后，需要分多个模块，这种的需要怎么解决？
报告的话，类似spock测试之类的报告，执行了那些测试，错误测试把错误提示标记出来。

**Comment by llxiao** [comment]
如果需要在一个js中 有多个测试场景，怎么进行？
例如：在spock测试中
```
def "测试1"(){}

def "测试2"(){}
```

这种情况应该怎么处理

**Comment by yaniswang** [comment]
为什么要把多测试场景写在一个JS中？
录成多个用例不能满足需求？

**Comment by llxiao** [comment]
测试场景过多时，不需要每次都打开和关闭浏览器吗？

**Comment by yaniswang** [comment]
目前是这样的，要不就在一次录制中，同时录多个场景。

关于这个问题，你有没有更好的建议？

**Comment by llxiao** [comment]
也没有好的办法 以前用的工具也是在多测试用例时的执行顺序上头疼,只能把测试写成相互独立的测试用例，互不影响，先后执行没有关系

**Comment by llxiao** [comment]
如果在一次录制中，录制多个场景，那么测试完成后怎么确定执行了哪些测试，当有个别测试出错时，怎么办？

**Comment by yaniswang** [comment]
建议还是每个独立吧，每次多打开浏览器，也不会多消耗多少时间。

将来可以把多浏览器做成并发的，就可以极大提升执行效率。

**Comment by llxiao** [comment]
嗯，可以，工具用起来简单容易上手，那就希望尽快把测试报告功能加上就OK了。望越做越好！
