### ISSUE TITLE
想修改源码中timeout大小，但是一直找不到源码所在的地方，求援助

### ISSUE THREAD

**Issue by shirleyxyli** [alibaba/uirecorder#300]
生成的js文件中，关于
pageloadTimeout: 30000, // page onload timeout
                        scriptTimeout: 5000, // sync script timeout
                        asyncScriptTimeout: 10000 // async script timeout
想修改大小，从源码上默认增大，但是找不到哪个文件
![image](https://user-images.githubusercontent.com/19338744/49366772-22882b00-f725-11e8-8026-352c6eb0b107.png)

**Comment by Stngle** [comment]
你好，可以修改全局安装目录下，./uirecorder/template/jwebdriver.js 模版文件
