### ISSUE TITLE
win10 安装uirecorder出错

### ISSUE THREAD

**Issue by LYJ8899** [alibaba/uirecorder#302]
npm install uirecorder mocha -g
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> typechecker@2.0.8 preinstall d:\node_modules\node_modules\uirecorder\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js

> typechecker@2.0.8 preinstall d:\node_modules\node_modules\uirecorder\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

d:\node_modules\_mocha -> d:\node_modules\node_modules\mocha\bin\_mocha
d:\node_modules\mocha -> d:\node_modules\node_modules\mocha\bin\mocha
d:\node_modules\uirecorder -> d:\node_modules\node_modules\uirecorder\bin\uirecorder

> chromedriver@2.45.0 install d:\node_modules\node_modules\uirecorder\node_modules\chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387)

ChromeDriver is already available at 'C:\Users\LYJ\AppData\Local\Temp\chromedriver\chromedriver.exe'.
Copying to target path d:\node_modules\node_modules\uirecorder\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available at d:\node_modules\node_modules\uirecorder\node_modules\chromedriver\lib\chromedriver\chromedriver.exe

> websocket@1.0.22 install d:\node_modules\node_modules\uirecorder\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

d:\node_modules\node_modules\uirecorder\node_modules\websocket>if not defined npm_config_node_gyp (node "D:\develop\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\develop\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  bufferutil.cc
  win_delay_load_hook.cc
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan_maybe_43_inl.h(221): warning C4996: 'v8::Array::CloneEleme
ntAt': 被声明为已否决 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\buffe
rutil.vcxproj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(3518): note: 参见“v8::Array::CloneElementAt”的声明 (编译源文件 ..\src\bufferuti
  l.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanOb
ject::New': 被声明为已否决 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\
bufferutil.vcxproj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(4845): note: 参见“v8::BooleanObject::New”的声明 (编译源文件 ..\src\bufferutil.c
  c)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(590): error C2039: “GCEpilogueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\bufferutil.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(590): error C2065: “GCEpilogueCallback”: 未声明的标识符 (编译源文件
..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(591): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(591): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\bu
fferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(591): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2039: “GCEpilogueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\bufferutil.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2065: “GCEpilogueCallback”: 未声明的标识符 (编译源文件
..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\bu
fferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(601): error C2039: “GCPrologueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\bufferutil.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(601): error C2065: “GCPrologueCallback”: 未声明的标识符 (编译源文件
..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(602): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(602): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\bu
fferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(602): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2039: “GCPrologueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\bufferutil.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2065: “GCPrologueCallback”: 未声明的标识符 (编译源文件
..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\bu
fferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(1927): warning C4996: 'v8::Object::SetAccessor': 被声明为已否决
 (编译源文件 ..\src\bufferutil.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(3192): note: 参见“v8::Object::SetAccessor”的声明 (编译源文件 ..\src\bufferutil.
  cc)
  validation.cc
  win_delay_load_hook.cc
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan_maybe_43_inl.h(221): warning C4996: 'v8::Array::CloneEleme
ntAt': 被声明为已否决 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\valid
ation.vcxproj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(3518): note: 参见“v8::Array::CloneElementAt”的声明 (编译源文件 ..\src\validatio
  n.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanOb
ject::New': 被声明为已否决 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\
validation.vcxproj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(4845): note: 参见“v8::BooleanObject::New”的声明 (编译源文件 ..\src\validation.c
  c)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(590): error C2039: “GCEpilogueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\validation.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(590): error C2065: “GCEpilogueCallback”: 未声明的标识符 (编译源文件
..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(591): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(591): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\va
lidation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(591): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2039: “GCEpilogueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\validation.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2065: “GCEpilogueCallback”: 未声明的标识符 (编译源文件
..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\va
lidation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(596): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(601): error C2039: “GCPrologueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\validation.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(601): error C2065: “GCPrologueCallback”: 未声明的标识符 (编译源文件
..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(602): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(602): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\va
lidation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(602): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2039: “GCPrologueCallback”: 不是“v8::Isolate”
的成员 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxpr
oj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(6732): note: 参见“v8::Isolate”的声明 (编译源文件 ..\src\validation.cc)
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2065: “GCPrologueCallback”: 未声明的标识符 (编译源文件
..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2146: 语法错误: 缺少“)”(在标识符“callback”的前面) (编译源文件
 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 ..\src\va
lidation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(607): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 ..\src
\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
d:\node_modules\node_modules\uirecorder\node_modules\nan\nan.h(1927): warning C4996: 'v8::Object::SetAccessor': 被声明为已否决
 (编译源文件 ..\src\validation.cc) [d:\node_modules\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]
  C:\Users\LYJ\.node-gyp\8.11.3\include\node\v8.h(3192): note: 参见“v8::Object::SetAccessor”的声明 (编译源文件 ..\src\validation.
  cc)
+ uirecorder@2.5.45
+ mocha@5.2.0
added 393 packages and updated 1 package in 24.005s
这是什么问题?求大神指导

**Comment by Stngle** [comment]
node版本？

**Comment by LYJ8899** [comment]
node 版本是8.11.3

**Comment by Stngle** [comment]
应该是安装过程哪里出错了，加钉钉群 11779932 截图交流吧

**Comment by Stngle** [comment]
参考文档：https://www.yuque.com/artist/uirecorder
