### ISSUE TITLE
As i come to know this uirecorder can only work on chrome for recording and execution on any browser.Is there any way to run recorder part on any browser using this uirecorder because some of my websites only supported on IE.

### ISSUE THREAD

**Issue by krunalbhanushali** [alibaba/uirecorder#303]

**Comment by Stngle** [comment]
Hi, thanks for your suggestion. The recorder part is based on chrome-extension, that's why this uirecorder can only work on chrome for recording.As I know,IE browser doesn't support thrid-part extension or plugins.
