### ISSUE TITLE
UI recorder Run chrome but not support IE and firefox for excution script

### ISSUE THREAD

**Issue by NishantMadkikar** [alibaba/uirecorder#306]
As said UI recorder support any browser for run script but its run on chrome but not support ie 11 and firefox its only open browser but not run test script and gives error like
 "before all" hook:
     Error: the string "Invalid timeout type specified: ms\nBuild info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'\nSystem
info: host: 'LATITUDE-PC', ip: '192.168.1.156', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_162'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
same as for firefox after open browser

**Comment by NishantMadkikar** [comment]
IE Browser information:
This is the initial start page for the WebDriver server.

**Comment by Stngle** [comment]
update the lasted version and have a try
