### ISSUE TITLE
变量功能中，可以支持js的模板字符串，比如支持时间戳要怎么写

### ISSUE THREAD

**Issue by WilliamWangZi** [alibaba/uirecorder#307]
"vars": {
        "company":`${new Date().getTime()}`
    }

比如以上，这样写也是错的，可以通过一个例子吗？

**Comment by WilliamWangZi** [comment]
> 这是翻译的问题：
> 
> # 变量函数，可以支持js模板字符串，如何编写时间戳
> “vars”：{ 
>         “公司”：`${new Date().getTime()}`
>     }
> 
> 例如，上面写错了，你能传递一个例子吗？

翻译的问题是指什么

**Comment by WilliamWangZi** [comment]
> 这是翻译的问题评论：@WilliamWangZi
> 
> > 这是一个翻译问题：
> > # 变量函数，可以支持js模板字符串，如何写时间戳
> > “vars”：{ 
> > “公司”：`${new Date().getTime()}`
> > }
> > 例如，以上是错误的，你能通过一个例子吗？
> 
> 翻译有什么问题？

我的意思是变量功能中，想用时间戳怎么写，能请教下您吗

**Comment by Stngle** [comment]
time: "new Date().getTime()"
