### ISSUE TITLE
work only on chrome not run on firefox 

### ISSUE THREAD

**Issue by NishantMadkikar** [alibaba/uirecorder#309]
RootsInnovations-MacBook:uirecorder roots$ mocha sample/test.spec.js

  Documents/khan/UI/uirecorder/sample/test.spec : firefox
    1) "before all" hook
    2) "after all" hook

  0 passing (9s)
  2 failing

  1) Documents/khan/UI/uirecorder/sample/test.spec : firefox
       "before all" hook:
     Error: the string "unknown field `ms`, expected one of `implicit`, `pageLoad`, `script` at line 2 column 6\nBuild info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'\nSystem info: host: 'RootsInnovations-MacBook.local', ip: '192.168.2.236', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_131'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Documents/khan/UI/uirecorder/sample/test.spec : firefox
       "after all" hook:

     Error: the string "unknown field `ms`, expected one of `implicit`, `pageLoad`, `script` at line 2 column 6\nBuild info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'\nSystem info: host: 'RootsInnovations-MacBook.local', ip: '192.168.2.236', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_131'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at <anonymous>

**Comment by Stngle** [comment]
update the lastet version and have a try
