### ISSUE TITLE
如何在mac上测试其他IE的浏览器呢？

### ISSUE THREAD

**Issue by chunchill** [alibaba/uirecorder#312]
我看完了文档之后，想知道如果需要在mac上安装这个工具，其他的浏览器是需要安装吗？
这个有没有云产品使用，云浏览器的产品发布了吗？

**Comment by Stngle** [comment]
webdriver云和浏览器云可以参考 https://f2etest.net/

**Comment by chunchill** [comment]
@Stngle 谢谢，我是说阿里云上有没有现成的产品卖？
也不知道现在这个项目的成熟度现在怎么样，阿里现在有专职团队在研发吗？

**Comment by Stngle** [comment]
> @Stngle 谢谢，我是说阿里云上有没有现成的产品卖？
> 也不知道现在这个项目的成熟度现在怎么样，阿里现在有专职团队在研发吗？

有计划docker化后上云，目前还没有云产品

**Comment by chunchill** [comment]
@Stngle 我们找机会自己安装一下，构建一个云浏览器。祈祷版本足够文档，谢谢阿里强大的技术贡献！
