### ISSUE TITLE
启动浏览器后,一直转圈,加载中..

### ISSUE THREAD

**Issue by gunC** [alibaba/uirecorder#317]
看其他 iusse 说的是,要用 2.5.10的版本..
然后试了下2.5.10 版本, init 也报错..

2.5.46 `init -mobile` 出现一些警告..
![image](https://user-images.githubusercontent.com/1253658/51967316-f2050900-24a9-11e9-8841-e4ae92daf156.png)

2.5.10 `init -mobile` 出现报错
![image](https://user-images.githubusercontent.com/1253658/51967371-1cef5d00-24aa-11e9-9551-ae0af226432b.png)

**Comment by Stngle** [comment]
看报错应该是网络问题，没有成功下载 selenium-standalone

**Comment by gunC** [comment]
35版本能用
