### ISSUE TITLE
imagediff做图片比对

### ISSUE THREAD

**Issue by yanxiaoxuan** [alibaba/uirecorder#320]
用断言中的imagediff做图片比对时发现两个问题：
问题一：uirecorder工具的预期结果图片生成有误
在录制用例时不会保存待比对的图片，只有回放用例时，才会在diffbase目录下生成图片，并以diffbase目录下的图片作为预期结果与回放时的实际图片进行对比。但是真正的预期结果图片应该是录制用例时点击imagediff的图片而不是回放时的图片。
问题二：imagediff比对的结果不清晰
比对结果图片没有明确清楚得标识出两个图片不同之处，只有模糊的红色进行标识，缺少重点。
希望作者看到问题，可以给予回复和帮助，多谢！

**Comment by yaniswang** [comment]
你说的这个问题的确存在，基线图片的确应该在添加的时候就生成，这个今后可以优化。

至于结果不清晰，应该是你的前后两张图片差异不大吧？如果差异大，应该还是可以比较清晰的看出哪些地方变化了。

**Comment by yanxiaoxuan** [comment]
我现在用的是2.5.46版本的uirecorder，这个版本的uirecorder在录制用例打开浏览器时默认只能打开1024×768的，请问下怎么可以把默认大小设置成最大窗口

**Comment by wawIsready** [comment]
你可以更新至 v.2.5.47 试试。
![image](https://user-images.githubusercontent.com/35623033/53327939-db749500-3923-11e9-986c-dea89b4209d2.png)

**Comment by Anhuiwang** [comment]
谢谢楼主，帮助很大

**Comment by Anhuiwang** [comment]
需要对比的图片是不是替换diffbase目录下的录制时生成的图片就可以了，是不是只能替换图片内容，图片的名称需要沿用录制时生成的名称
