### ISSUE TITLE
如何设置新版uirecorder录制窗口最大化问题

### ISSUE THREAD

**Issue by yanxiaoxuan** [alibaba/uirecorder#321]
我现在用的是2.5.46版本的uirecorder，这个版本的uirecorder在录制用例打开浏览器时默认只能打开1024×768的，请问下怎么可以把默认大小设置成最大窗口

**Comment by yaniswang** [comment]
把窗口大小参数改为：maximum

**Comment by yaniswang** [comment]
不对，目前新版好像已经不支持最大化了

**Comment by yanxiaoxuan** [comment]
> 不对，目前新版好像已经不支持最大化了

为啥不支持最大化啊

**Comment by Stngle** [comment]
> > 不对，目前新版好像已经不支持最大化了
> 
> 为啥不支持最大化啊

最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复

**Comment by yanxiaoxuan** [comment]
> > > 不对，目前新版好像已经不支持最大化了
> > 
> > 
> > 为啥不支持最大化啊
> 
> 最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复


> > > 不对，目前新版好像已经不支持最大化了
> > 
> > 
> > 为啥不支持最大化啊
> 
> 最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复

期待。我刚用uirecorder回放了一遍用例，主要用到了图片比对imgdiff，我现在手动在diffbase里放置预期图片，录制时选的imgdiff参数是below，个数是1，回放的结果报告中显示了预期图片和实际图片有三处不同，但是imgdiff的断言结果是正确的，请问这个是我below参数设置的问题吗还是工具的bug啊

**Comment by yaniswang** [comment]
图片对比你设置为1，是指图片差异小于1%，就报错。
明显设置反了，应该设置大于1%才报错。

**Comment by yanxiaoxuan** [comment]
> 图片对比你设置为1，是指图片差异小于1%，就报错。
> 明显设置反了，应该设置大于1%才报错。

我把用例里面的below改成above，个数设置为1，断言结果报错，个数设置为0为什么不报错啊

**Comment by Stngle** [comment]
> > > > 不对，目前新版好像已经不支持最大化了
> > > 
> > > 
> > > 为啥不支持最大化啊
> > 
> > 
> > 最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复
> 
> > > > 不对，目前新版好像已经不支持最大化了
> > > 
> > > 
> > > 为啥不支持最大化啊
> > 
> > 
> > 最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复
> 
> 期待。我刚用uirecorder回放了一遍用例，主要用到了图片比对imgdiff，我现在手动在diffbase里放置预期图片，录制时选的imgdiff参数是below，个数是1，回放的结果报告中显示了预期图片和实际图片有三处不同，但是imgdiff的断言结果是正确的，请问这个是我below参数设置的问题吗还是工具的bug啊

已更新版本 2.5.47 支持 maximize 最大化窗口

**Comment by yanxiaoxuan** [comment]
> > > > > 不对，目前新版好像已经不支持最大化了
> > > > 
> > > > 
> > > > 为啥不支持最大化啊
> > > 
> > > 
> > > 最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复
> > 
> > 
> > > > > 不对，目前新版好像已经不支持最大化了
> > > > 
> > > > 
> > > > 为啥不支持最大化啊
> > > 
> > > 
> > > 最大化在mac下有兼容问题，不过maximize功能会做保留，明天会发布一个新版本修复
> > 
> > 
> > 期待。我刚用uirecorder回放了一遍用例，主要用到了图片比对imgdiff，我现在手动在diffbase里放置预期图片，录制时选的imgdiff参数是below，个数是1，回放的结果报告中显示了预期图片和实际图片有三处不同，但是imgdiff的断言结果是正确的，请问这个是我below参数设置的问题吗还是工具的bug啊
> 
> 已更新版本 2.5.47 支持 maximize 最大化窗口

好的，多谢！
