### ISSUE TITLE
关于公共用例调用问题

### ISSUE THREAD

**Issue by yanxiaoxuan** [alibaba/uirecorder#325]
在录制其他用例时调用我已经录制好的公共用例，等公共用例加载完，报公共用例加载失败，exec timeout，而且再录制其他步骤，后面的步骤也不会写入用例。但是单独执行公共用例是ok的。请问是不是录制公共用例的时间是有限制的，不能超过多少秒？

**Comment by Stngle** [comment]
没有做限制的，公共加载模版代码贴一下？

**Comment by yanxiaoxuan** [comment]
> 没有做限制的，公共加载模版代码贴一下？

我公司的项目是涉密的，不太方便唉，能提供下根据这个报错信息查找的思路吗，我可以自己试着看看

**Comment by Stngle** [comment]
加载公共模版需要等待一会，有报错日志吗
