### ISSUE TITLE
Mobile recorder下Run case，提示ECONNREFUSED。如何执行已有的js

### ISSUE THREAD

**Issue by hannahqing** [alibaba/uirecorder#33]

**Comment by yaniswang** [comment]
macaca server --port 4444是否已经启动？

**Comment by hannahqing** [comment]
已经启动了macaca。报错信息如下：
1) test.spec : 0715f7ca0e363d36 "before all" hook:
     Error: connect ECONNREFUSED 30.96.101.8:4444
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by yaniswang** [comment]
30.96.101.8:4444

这个是macaca服务器吗？

**Comment by hannahqing** [comment]
这个是执行uirecorder init --mobile后用的默认的

**Comment by hannahqing** [comment]
好了，设置ip的时候应该设置本机ip。。。。
