### ISSUE TITLE
imagediff做图片比对比(客户端对比截图尺寸不对)

### ISSUE THREAD

**Issue by zhouhuiping** [alibaba/uirecorder#334]
imagediff做图片比对比(客户端对比截图尺寸不对)，截不到响应画布的值

**Comment by zhouhuiping** [comment]
<img width="188" alt="test2_spec_iPhone_7_ 6B62FC61_D24B_4D7C_BFA8_34BE8291F13B _4" src="https://user-images.githubusercontent.com/15843956/56564163-0d327100-65e0-11e9-80c0-b859d42e06f2.png">

**Comment by Stngle** [comment]
跟设备的分辨率有关
