### ISSUE TITLE
Recorder for Desktop applications

### ISSUE THREAD

**Issue by part140783** [alibaba/uirecorder#338]
Hi,
The UI recorder is a great help for testing web applications. But sometimes a lot of applications depends on recording desktop applications like SAP or Oracle or Microsoft applications.
Just curious whether the desktop recording capabilities are in the pipeline. If yes, is there a timeline. If you are aware of any such open source desktop recording software kindly guide.

Anyways thanks a ton to the entire team.

**Comment by Stngle** [comment]
Hi,
    The UIRecorder capture elements base on chrome-extension, it can record operation when emitting events.Do you have a good elements capture solution for desktop application?
