### ISSUE TITLE
图片对比 断言失败是什么原因

### ISSUE THREAD

**Issue by DyanZhao** [alibaba/uirecorder#339]
错误如下
sample/aa.spec : chrome
    1) "before all" hook
    2) "after all" hook

  0 passing (20ms)
  2 failing

  1) sample/aa.spec : chrome
       "before all" hook:
     Error: getaddrinfo ENOTFOUND selenium-hub selenium-hub:4444
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

  2) sample/aa.spec : chrome
       "after all" hook:
     Error: getaddrinfo ENOTFOUND selenium-hub selenium-hub:4444
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

**Comment by rogerleocz** [comment]
不知道是否正确，初步理解如下：
selenium hub类似于一个中央处理器，错误中提示该处理器未找到，可以理解为该处理器并未启动。
在java的运行环境中，终端下输入java -jar selenium-server-standalone-x.xx.x.jar -role node -参数，比如参数是help，就可以看到一起启动参数了。
相关参考： https://blog.csdn.net/chengly0129/article/details/73195069

**Comment by Stngle** [comment]
看报错应该是 selenium-server 的问题，参考文档：https://www.yuque.com/artist/uirecorder/uozk2g
