### ISSUE TITLE
现在只支持android原生应用吗？是否支持ionic开发的应用

### ISSUE THREAD

**Issue by llxiao** [alibaba/uirecorder#34]
在点击应用过程中，在浏览器点击输入框无反应，ionic开发的应用

**Comment by yaniswang** [comment]
对于最新chrome内核的webview，支持还行。
ionic开发的是什么内核？

**Comment by llxiao** [comment]
Crosswalk

**Comment by yaniswang** [comment]
这个是什么浏览器内核？

**Comment by llxiao** [comment]
Chromium内核

**Comment by yaniswang** [comment]
chrome内核应该是支持的，不过最新版好像会将dom中的id翻译成resource-id，所以生成的xpath就相对比较友好。

**Comment by llxiao** [comment]
好的 多谢了 我再看看
