### ISSUE TITLE
有没有支持node10的计划

### ISSUE THREAD

**Issue by mazhewei** [alibaba/uirecorder#348]
官方LTS已经是node10了

**Comment by Stngle** [comment]
你好，请问是 node10.16.0 版本吗，电脑的操作系统是什么？
我这边使用 mac 和 windows 10 都没有复现这个问题。

**Comment by Stngle** [comment]
目前是支持 node 10 的。https://www.yuque.com/artist/uirecorder/tvgfwo#KdyXC

**Comment by koibi2** [comment]
> 目前是支持node 10的[。https://www.yuque.com/artist/uirecorder/tvgfwo#KdyXC](https://www.yuque.com/artist/uirecorder/tvgfwo#KdyXC)

你好，现在使用 node10 安装依赖、初始化项目仍然不可用。
现在 Node 的LTS版本都12了。希望向上兼容一下。
（操作系统：64位win10，Node版本：10.15.1 ）

### 1、安装依赖错误
已经更换了阿里的源。
![1](https://user-images.githubusercontent.com/34370367/70485694-99bb8080-1b2a-11ea-93c7-a8ab07c10193.png)
![3](https://user-images.githubusercontent.com/34370367/70486205-ea7fa900-1b2b-11ea-99b7-27b23f448fce.png)



### 2、初始化项目错误
我用 `yarn install` 安装依赖后，`uirecorder start` 也卡住了。
如同这个Issues：https://github.com/alibaba/uirecorder/issues/340

![2](https://user-images.githubusercontent.com/34370367/70485702-9e803480-1b2a-11ea-92cf-cc3075d8b3bb.png)

**Comment by Stngle** [comment]
使用 bash 环境运行

**Comment by koibi2** [comment]
> 使用 bash 环境运行

![error](https://user-images.githubusercontent.com/34370367/70633689-e3f84b00-1c6b-11ea-846d-cadbd4c4e1f1.png)
我用 win10 下自带的 Linux bash 试了下，Bash 命令行下也不行。
找不到 chromedriver。
只能老老实实用 node 8 吧。。。

（然而 要测试的项目必须在 node 10下执行。哭。。。）
