### ISSUE TITLE
多移动设备执行脚本时报错

### ISSUE THREAD

**Issue by zwq90216** [alibaba/uirecorder#35]
2个移动设备在执行macha test.spec.js后，2个设备是先后安装app，然后报错，如下：
![qq 20161104165221](https://cloud.githubusercontent.com/assets/23257285/20001562/b5b0c014-a2b7-11e6-94b3-56243dfd2a7f.png)
然后也并没有执行脚本。我在官网看到的需要set devices xxx1,xxx2  不知道这个是在哪填写或者输入，多设备跑脚本时应该是怎样的步骤，求解答

**Comment by yaniswang** [comment]
你单个设备是正常的吗？两个设备就执行失败了？

**Comment by yaniswang** [comment]
set devices是环境变量，如果是linux系的，那就是export命令

**Comment by zwq90216** [comment]
我用的win7  单个设备是正常的，windows需要怎么设置呢

**Comment by yaniswang** [comment]
是ios还是android？

**Comment by yaniswang** [comment]
macaca新版已经修复并发问题
