### ISSUE TITLE
IE11 回放测试用例失败，求具体解决方案

### ISSUE THREAD

**Issue by yangzonn** [alibaba/uirecorder#350]
![キャプチャ](https://user-images.githubusercontent.com/39957223/59336624-df44ef80-8d39-11e9-958c-9475b5e44135.JPG)

**Comment by yangzonn** [comment]
![driver](https://user-images.githubusercontent.com/39957223/59341271-89c11080-8d42-11e9-9668-827b78725747.JPG)
ie 的webdriver应该是正常运行的

**Comment by yangzonn** [comment]
![キャプチャ](https://user-images.githubusercontent.com/39957223/59341319-a1989480-8d42-11e9-93a9-507879198978.JPG)
但是用ie11执行测试用例的时候会出现错误，请问是配置哪里出了问题么？

**Comment by JhoneLee** [comment]
> ![キャプチャ](https://user-images.githubusercontent.com/39957223/59341319-a1989480-8d42-11e9-93a9-507879198978.JPG)
> 但是用ie11执行测试用例的时候会出现错误，请问是配置哪里出了问题么？

我用2.53.0 版本的ie driver 就能启动ie 11 了，如果还不行就多试试其他旧版本，还有网上那些关于ie 安全、注册表 的设置
