### ISSUE TITLE
录制完运行时报错 Error: the string "timeout\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)" was thrown, throw an Error :)

### ISSUE THREAD

**Issue by MLittleMandy** [alibaba/uirecorder#358]
感觉像是chrome 和chromedriver 版本不匹配的问题。。。

**Comment by MLittleMandy** [comment]
之前chrome是75版本，卸载重装的69版本，还是不行，是不是要重装ui -recorder?

**Comment by zquancai** [comment]
检查一下目录里的 chromedriver 和 chrome 的版本是否匹配。
匹配关系表：http://appium.io/docs/en/writing-running-appium/web/chromedriver/#chromedriverchrome-compatibility

**Comment by Stngle** [comment]
最新版本 uirecorder@3.1.2，已更新 chromedriver 至最新版本 76.0.0
