### ISSUE TITLE
加11779932显示团队编号无效

### ISSUE THREAD

**Issue by 736090191** [alibaba/uirecorder#360]
下载了手机版的钉钉，点击加入团队，输入11779932显示团队编号无效

**Comment by Stngle** [comment]
![image](https://user-images.githubusercontent.com/18617837/60635129-278c9480-9e44-11e9-9066-baa110873b22.png)

扫码试试？

**Comment by 736090191** [comment]
二维码吗，在哪里

**Comment by Stngle** [comment]
评论上方
