### ISSUE TITLE
加11779932显示团队编号无效，回复的二维码图片也显示不了

### ISSUE THREAD

**Issue by 736090191** [alibaba/uirecorder#361]
加11779932显示团队编号无效，回复的二维码图片也显示不了。
11779932这个是手机端钉钉的群号吗，希望可以加入，我用uirecorder挺多的，希望可以跟大家交流一下啊

**Comment by Stngle** [comment]
群号：11779932
最新二维码：
![image](https://user-images.githubusercontent.com/18617837/66371226-3cde0580-e9d5-11e9-826a-ed4b55651bc5.png)
