### ISSUE TITLE
使用imagediff断言后，无法在report页面显示失败的对比结果

### ISSUE THREAD

**Issue by aloneblood** [alibaba/uirecorder#371]
Node Version: v8.16.0 (npm v6.4.1)
UI Recorder Version: v3.1.0
已安装graphicsmagick
运行source ./run.sh scripts/test.spec.js --reporter mochawesome-uirecorder --reporter-options copyShotOnlyFail=true
跑完能在/reports/diffbase 发现原始图片，/reports/screenshots 能发现对应的*_diff.png和*_new.png 图片,但是打开index.html无法看到失败这条的图片对比图

![image](https://user-images.githubusercontent.com/4945220/61436560-a10ca280-a96d-11e9-9793-2da10d1700b5.png)

**Comment by aloneblood** [comment]
I try test on linux and mac, image diff can't work fine
but it work fine on windows.

**Comment by Stngle** [comment]
> I try test on linux and mac, image diff can't work fine
> but it work fine on windows.

旧版的报告 mochawesome-uirecorder 依赖技术栈比较旧，存在部分兼容问题，新版的 reporter 已经做了优化，可以参考 UIRecorder 3.x 版本做相关升级。https://www.yuque.com/artist/uirecorder/uqgnhu

目前 imagediff 功能新版的 reporter 展示发现存在兼容问题，已定位清楚，预计这两周发布新版本修复此问题。

**Comment by aloneblood** [comment]
> > I try test on linux and mac, image diff can't work fine
> > but it work fine on windows.
> 
> 旧版的报告 mochawesome-uirecorder 依赖技术栈比较旧，存在部分兼容问题，新版的 reporter 已经做了优化，可以参考 UIRecorder 3.x 版本做相关升级。https://www.yuque.com/artist/uirecorder/uqgnhu
> 
> 目前 imagediff 功能新版的 reporter 展示发现存在兼容问题，已定位清楚，预计这两周发布新版本修复此问题。

谢谢。刚刚降到v3.0.1,发现可以正常工作了

**Comment by Stngle** [comment]
最新版本已支持，更新 npm 依赖即可。
