### ISSUE TITLE
录制的元素路径存在一对多的问题

### ISSUE THREAD

**Issue by 736090191** [alibaba/uirecorder#373]
我用uirecorder工具录制用例时，想获取比如群ID这个元素，工具自动获取路径是//span[text()="群ID"]，但是回放报错了，我看了一下页面通过//span[text()="群ID"]这个路径总共可以找到三个群ID 。希望uirecorder工具在进行元素路径的获取时可以保证元素与获取的路径是一对一的关系。

**Comment by Stngle** [comment]
可以通过属性黑名单控制
https://www.yuque.com/artist/uirecorder/fbxrlz#c61cec7a
