### ISSUE TITLE
在it里添加断言，断言失败后，剩下的用例不执行脚本就中断

### ISSUE THREAD

**Issue by chanzed** [alibaba/uirecorder#379]
![image](https://user-images.githubusercontent.com/41747189/62687678-d733c400-b9f9-11e9-8dcc-33b9e9c13b43.png)
uirecorder v3.1.2

**Comment by MLittleMandy** [comment]
首先，如果一个IT 块执行失败，目前是会跳出整个JS 文档，你这个跟我是一样的问题，建议一个JS文档一个测试用例

**Comment by Stngle** [comment]
v3.1.5 fixed
