### ISSUE TITLE
firefix can't be called

### ISSUE THREAD

**Issue by cs10606** [alibaba/uirecorder#382]
mocha --reporter macaca-reporter --reporter-options reportJSONFilename=index --bail "sample\test.spec.js"

  sample/test.spec : firefox
    1) "before all" hook

  0 passing (11s)
  1 failing

  1) sample/test.spec : firefox
       "before all" hook:
     Error: the string "unknown field `ms`, expected one of `implicit`, `pageLoad`, `script` at line 2 column 6\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'DESKTOP-JT7SRO3', ip: '10.0.1.98', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@5.2.0@mocha\lib\runner.js:235:11)
      at Runner.failHook (node_modules\_mocha@5.2.0@mocha\lib\runner.js:284:8)
      at C:\Users\paul\uirecorder_test\node_modules\_mocha@5.2.0@mocha\lib\runner.js:334:16
      at done (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:319:5)
      at Promise.<anonymous> (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:383:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by Stngle** [comment]
操作系统、Node版本、UIRecorder版本、Firefox浏览器版本

**Comment by Stngle** [comment]
建议采用 F2etets WebDriver 云方案：

https://www.yuque.com/artist/uirecorder/uozk2g
https://www.yuque.com/artist/f2etest/webdriver-cloud-usage

**Comment by micosty** [comment]
本地环境回归验证ie11 / firefox
https://www.yuque.com/artist/uirecorder/qghot5#EYL2p
