### ISSUE TITLE
uirecorder cmd -browser launch issue

### ISSUE THREAD

**Issue by lksece** [alibaba/uirecorder#390]
Have a query w.r.t uirecorder. While running the tool, the cmd shows no progress after below line (Browser size (example: 1024 x 768): maximize). 
Could you please help me to resolve this? I am running it on a windows machine. 

Official Site: http://uirecorder.com
------------------------------------------------------------------

? Test spec file name: sample/test.spec.js
? File existed, load and continue to record? No
? Open checker browser? Yes
? Browser size (example: 1024 x 768): maximize

**Comment by lksece** [comment]
![image](https://user-images.githubusercontent.com/28644973/64596834-4a9e6c00-d3d2-11e9-8ba2-19b964340f78.png)

**Comment by Stngle** [comment]
the lasted verison is 3.1.6

**Comment by lksece** [comment]
we are using the v2.5.42 as it is worked before. Is there any dependency that am i missing. Is it possible to view the debug log?

**Comment by Stngle** [comment]
What is the node version? And what is the OS?

**Comment by lksece** [comment]
node : v10.16.3

npm : 6.9.0

Windows : Windows 2012 R2 datacenter 64-bit

**Comment by Stngle** [comment]
try the node version 8.x

**Comment by lksece** [comment]
Thanks Stngle. It worked !!!
