### ISSUE TITLE
不要使用eval

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/uirecorder#394]
eval()会动态解析字符串内容，如果攻击者提供一个恶意的输入，程序在没有进行合理校验的情况，将可以执行任意代码。
https://github.com/alibaba/uirecorder/blob/8baa189193a5f994ccfe1b7c4a8628671498ef36/chrome-extension/js/foreground.js#L2283
在这个文件的L2441,L2319,L2236,L1922,L2103,L2107,L2110 也存在同样的问题。

https://github.com/alibaba/uirecorder/blob/8baa189193a5f994ccfe1b7c4a8628671498ef36/chrome-extension/js/mobile.js#L337
在这个文件的L341,L344,L262 也有同样的问题
https://github.com/alibaba/uirecorder/blob/8baa189193a5f994ccfe1b7c4a8628671498ef36/chrome-extension/js/start.js#L83

参考：
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval
https://cwe.mitre.org/data/definitions/95.html

**Comment by Stngle** [comment]
输入内容仅限测试开发者自定义，不存在该风险
