### ISSUE TITLE
security:postMessage

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/uirecorder#395]
该文件有两处使用postMessage的安全问题，当您使用postMessage将数据发送到其他窗口时，始终要指定精确的目标origin，而不是*。恶意网站可以拦截postMessage发送的信息。
https://github.com/alibaba/uirecorder/blob/8baa189193a5f994ccfe1b7c4a8628671498ef36/chrome-extension/js/foreground.js#L494
https://github.com/alibaba/uirecorder/blob/8baa189193a5f994ccfe1b7c4a8628671498ef36/chrome-extension/js/foreground.js#L1001
参考：
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/postMessage

**Comment by Stngle** [comment]
仅限录制功能相关信息通信，不存在该风险
