### ISSUE TITLE
使用uirecorder录制过程中，浏览器打开失败

### ISSUE THREAD

**Issue by adjianwen** [alibaba/uirecorder#397]
录制服务器监听在端口：50231
Chrome打开失败
unknown error : Chrome failed to start ：exited abnormally
  <unknown error : DevTooIsActivePort file doesn't exist>
  <The process started from chrome location C:\program Files <x86>\Google\Chrome\Application\chrome..exe is no longer running , so ChromeDriver is assuming that Chrome has crashed.>
  <Driver info : chromedriver=76.0.3809.68 <420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864} , platform=Windows NT 6 .1.7601 SP1 x86_64 >

**Comment by Stngle** [comment]
uirecorder 版本
node 版本
操作系统

**Comment by adjianwen** [comment]
uirecorder：3.16
node：v8.16.1
windows （x64）

**Comment by Stngle** [comment]
更新至 uirecorder 3.1.7，支持最新 chrome 78 版本
