### ISSUE TITLE
driver.eval 不可用

### ISSUE THREAD

**Issue by balzaron** [alibaba/uirecorder#398]
eval函数返回永远是null
比如
![image](https://user-images.githubusercontent.com/9757578/65753101-d5a49380-e140-11e9-8223-26d26d6586af.png)
console调试永远是true，但是使用driver.eval后，返回了null，导致断言失败

**Comment by Stngle** [comment]
方便提供可复现例子？

**Comment by balzaron** [comment]
现有的script是公司内部的，我找一个公网上可以复现的例子

**Comment by balzaron** [comment]
以百度为首页测试
执行到如下代码raise  AssertionError: expected null to equal true
it('expect: jscode, eval(\'document.querySelectorAll(".s_ipt").length == 1\'), equal, true', async function(){
        await driver
            .eval('eval(\'document.querySelectorAll(".s_ipt").length == 1\')')
            .should.not.be.a('error')
            .should.equal(_(true));
    });

这里的逻辑很简单：
![image](https://user-images.githubusercontent.com/9757578/66736252-4961d280-ee9b-11e9-8938-09f31bfdb077.png)
但是uirecorder 不能正确执行eval

**Comment by Stngle** [comment]
示例如下
driver.eval(_('document.title = \'xxxx\''))
