### ISSUE TITLE
【拓展】uirecorder能否增加连接数据库，执行自定义sql的功能

### ISSUE THREAD

**Issue by starrysky-x** [alibaba/uirecorder#401]
我想在录制视频时添加连接数据库执行自定义sql的功能，类似于自定义执行js。
于是我试着为之添加功能，效果如下：
![image](https://user-images.githubusercontent.com/26305251/66446504-6488a880-ea7d-11e9-8d89-e5a78f8c9448.png)
可是在`chrome-extension/js/foreground.js`**无法运行nodejs**，那这功能是否就无法实现了呢？

**Comment by Stngle** [comment]
可以自定义录制模版，https://www.yuque.com/artist/uirecorder/rb242b

通过手工修改录制生成的脚本代码，实现 sql 功能。但是建议不要把数据库操作及 UI 场景回归测试耦合在一起，测试方案进行分层设计会比较合理。

**Comment by starrysky-x** [comment]
@Stngle 手工修改录制生成脚本代码，这是个备用方案。
可遗憾的是测试回归UI场景，往往伴随着数据库查询，如果可以的话，我还是希望能录制即时查询。

**Comment by Stngle** [comment]
chrome extension 是运行在 browser 端的，无法执行 node 代码。如果需要的话，可以是 chrome extension 与 node process 通过 websocket 通信的形式，chrome extension 发送请求至 node process 进行数据库操作。但是这样的实现成本相对来说较高。

**Comment by Stngle** [comment]
能否通过 ui 界面的形式进行数据库操作，这样成本会比较低

**Comment by starrysky-x** [comment]
`chrome extension`与`node process`通过`websocket`通信的形式，从实现成本和维护成本上考虑，这方案难以被接受。
通过ui界面形式进行数据库操作是指什么样的形式呢？

**Comment by Stngle** [comment]
ui可视化界面的形式，进行数据库操作。比如输入框输入 sql 语句，点击按钮完成查询。

**Comment by starrysky-x** [comment]
呃，还没看懂。不知道我理解有没错
①如果这个数据库的可视化和uirecorder是绑定在一起的,那在录制的时候也能被记录操作么，如果是那符合我的需求，类似问题中的截图。
②如果这个可视化的数据库操作是另一个独立的服务，那就没法记录在生成的脚本中。

**Comment by Stngle** [comment]
相当于一个 Web 页面是进行 数据库操作的
一个 Web 页面是进行业务测试的
