### ISSUE TITLE
如何录制悬停后点击二级菜单

### ISSUE THREAD

**Issue by jianchen10** [alibaba/uirecorder#408]
以下是我录制的脚步，回放时悬停正常，点击操作不能执行，请问哪里出了问题
另外想问下这个元素定位是基于什么，想要编辑脚本该怎么写

it('mouseMove: 创建项目 ( //span[text()="创建项目"], 32, 14 )', async function(){
        await driver.sleep(300).wait('//span[text()="创建项目"]', 30000)
               .sleep(300).mouseMove(32, 14);
    });

    it('click: 空白项目 ( #dropdown-menu-6854 li:nth-child(1), 52, 14, 0 )', async function(){
        await driver.sleep(300).wait('#dropdown-menu-6854 li:nth-child(1)', 30000)
               .sleep(300).mouseMove(52, 14).click(0);
    });

**Comment by Stngle** [comment]
定位基于 css seletor 实现，move 动作后两位参数是 x，y 的相对位移
