### ISSUE TITLE
提供个录制教程

### ISSUE THREAD

**Issue by praguepp** [alibaba/uirecorder#41]
目前都是手写代码，看了腾讯的优测，可以录制，期望多个录制功能和教程出来

**Comment by xudafeng** [comment]
@yaniswang 你不是要出视频教程吗

**Comment by yaniswang** [comment]
@xudafeng 想等IOS完善了，再一起录个PC+ANDROID+IOS，3端的视频录制教程。

**Comment by yaniswang** [comment]
@praguepp uirecorder本身就是录制用的啊，目前支持PC和android，ios还有点小问题
你希望的录制功能是指什么？

**Comment by praguepp** [comment]
之前用的macaca是否支持录制了？

**Comment by yaniswang** [comment]
已经支持录制了，android下已经完美了，但是目前由于macaca的ios驱动还有点问题，还有点小缺陷。

**Comment by xiaosongfu** [comment]
? App路径, 扩展名: apk, app ()   在这应该怎么输入呀？怎么都不对

**Comment by yaniswang** [comment]
相对路径，或者绝对路径
比如：test.apk
或者：d:/aaa/test.apk

**Comment by xiaosongfu** [comment]
@yaniswang 谢谢

**Comment by jack-github** [comment]
iOS的缺陷 新版本解决了吗？ 怎么现在还有些控件不支持
