### ISSUE TITLE
Chrome打开失败

### ISSUE THREAD

**Issue by myronBob** [alibaba/uirecorder#412]
![image](https://user-images.githubusercontent.com/23491370/68662864-a626da80-0578-11ea-8f99-d4ae4a5f3dc1.png)
使用cnpm重新安装了模块
浏览器版本78.0.3904.97
windows x64
uirecorder v3.1.7

**Comment by Stngle** [comment]
使用 bash 环境执行命令行，比如 安装 git bash，cmd 的方式有部分兼容问题
