### ISSUE TITLE
linux上运行脚本兼容性

### ISSUE THREAD

**Issue by 3144234615** [alibaba/uirecorder#416]
windows上录制的脚本在linux上使用 --no-sandbox' 本地运行，失败率比windows上本地运行高，同一个脚本，在win本地全部通过，linux上却只能跑成功部分事件。这种情况应该怎么解决或优化？还有有没有具体的在linux非图形化（文字界面）上搭建浏览器环境的教程。--no-sandbox如果没设置运行脚本是会报错的。查了半天才侥幸成功。

**Comment by Stngle** [comment]
建议使用 windows 回放，linux 系统可使用的浏览器主要是 chrome、firefox，而真实的用户场景还是 windows 为主
