### ISSUE TITLE
是否可以在Config文件增加参数（设置为无头浏览器回放），使所有脚本运行时用无头浏览器跑？

### ISSUE THREAD

**Issue by DearMerlin** [alibaba/uirecorder#417]
是否可以在Config文件增加参数（设置为无头浏览器回放），使所有脚本运行时用无头浏览器跑。不用一个个脚本增加，回放时用无头浏览器的参数。
![image](https://user-images.githubusercontent.com/43475632/69926217-8edf6b00-14ee-11ea-8648-30bfea045474.png)

**Comment by Cayla-Xiong** [comment]
可以，设置如图：
![image](https://user-images.githubusercontent.com/59002948/71137530-7b990300-2243-11ea-8a5b-abb734980015.png)

**Comment by DearMerlin** [comment]
@Cayla-Xiong 设置之后没成功呢
![图片](https://user-images.githubusercontent.com/43475632/71145317-20bfd580-225c-11ea-84b0-833ab1c46b11.png)
![图片](https://user-images.githubusercontent.com/43475632/71145335-333a0f00-225c-11ea-9c3c-5166081aa68f.png)

**Comment by Cayla-Xiong** [comment]
> @Cayla-Xiong 设置之后没成功呢
> ![图片](https://user-images.githubusercontent.com/43475632/71145317-20bfd580-225c-11ea-84b0-833ab1c46b11.png)
> ![图片](https://user-images.githubusercontent.com/43475632/71145335-333a0f00-225c-11ea-9c3c-5166081aa68f.png)

少了一个逗号，在"chrome"后面

**Comment by DearMerlin** [comment]
真的可以了，谢谢 @Cayla-Xiong
