### ISSUE TITLE
Error: Cannot find module 'jquery'

### ISSUE THREAD

**Issue by skyknight007** [alibaba/uirecorder#418]
run.bat sample/test3.spec.js 报错

执行日志如下：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'singletest',
1 verbose cli   'sample/test3.spec.js' ]
2 info using npm@6.4.1
3 info using node@v9.11.2
4 verbose run-script [ 'presingletest', 'singletest', 'postsingletest' ]
5 info lifecycle uirecorderTest@1.0.0~presingletest: uirecorderTest@1.0.0
6 info lifecycle uirecorderTest@1.0.0~singletest: uirecorderTest@1.0.0
7 verbose lifecycle uirecorderTest@1.0.0~singletest: unsafe-perm in lifecycle true
8 verbose lifecycle uirecorderTest@1.0.0~singletest: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\source_code\ui_test\node_modules\.bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\Java\jdk1.8.0_66\bin;D:\Program Files (x86)\apache-maven-3.3.9\bin;D:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;d:\Program Files (x86)\Microsoft VS Code\bin;D:\Program Files\nodejs\node_modules\node_global
9 verbose lifecycle uirecorderTest@1.0.0~singletest: CWD: D:\source_code\ui_test
10 silly lifecycle uirecorderTest@1.0.0~singletest: Args: [ '/d /s /c',
10 silly lifecycle   'mocha --reporter mochawesome-uirecorder --bail "sample/test3.spec.js"' ]
11 silly lifecycle uirecorderTest@1.0.0~singletest: Returned: code: 1  signal: null
12 info lifecycle uirecorderTest@1.0.0~singletest: Failed to exec singletest script
13 verbose stack Error: uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test3.spec.js"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid uirecorderTest@1.0.0
15 verbose cwd D:\source_code\ui_test
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "singletest" "sample/test3.spec.js"
18 verbose node v9.11.2
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test3.spec.js"`
22 error Exit status 1
23 error Failed at the uirecorderTest@1.0.0 singletest script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

在脚本中去掉  “const $ = require('jquery');” 后可以开始执行
![image](https://user-images.githubusercontent.com/5241255/70038818-def42580-15f3-11ea-80dc-98664ac09358.png)

**Comment by Stngle** [comment]
更新 uirecorder 至最新版本即可
