### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 77

### ISSUE THREAD

**Issue by balzaron** [alibaba/uirecorder#420]
session not created: This version of ChromeDriver only supports Chrome version 77
  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Mac OS X 10.13.6 x86_64)
但是我已经更新了 npm install Chromedriver@79 -g
还是报错只支持到77

**Comment by PiterYang** [comment]
我的也是，楼主解决了吗

**Comment by Cayla-Xiong** [comment]
将浏览器版本和ChromeDriver版本降级就可以了

Mac历史浏览器版本和ChromeDriver版本
https://www.applex.net/downloads/google-chrome-for-mac.25/history
https://chromedriver.chromium.org/downloads

**Comment by LarkinZero** [comment]
有办法手动升级chromedriver版本么，我发现下载了最新的chromedriver 79替换了77版本，依旧提示``session not created: This version of ChromeDriver only supports Chrome version 77``
是代码里写死了版本了吗

**Comment by Cayla-Xiong** [comment]
> This is the translated issue comment: @LarkinZero
> 
> There a way to manually upgrade chromedriver version of what I found to download the latest version chromedriver 79 replaces the 77, still prompt ` session not created: This version of ChromeDriver only supports Chrome version 77`
> Is a version of the code written dead yet

具体原因我还没弄明白，但是我降到77后就可以了

**Comment by Cayla-Xiong** [comment]
> > This is the translated issue comment: @LarkinZero
> > There a way to manually upgrade chromedriver version of what I found to download the latest version chromedriver 79 replaces the 77, still prompt ` session not created: This version of ChromeDriver only supports Chrome version 77`
> > Is a version of the code written dead yet
> 
> 具体原因我还没弄明白，但是我降到77后就可以了

不知道是不是没有做兼容

**Comment by Cayla-Xiong** [comment]
> 有办法手动升级chromedriver版本么，我发现下载了最新的chromedriver 79替换了77版本，依旧提示`session not created: This version of ChromeDriver only supports Chrome version 77`
> 是代码里写死了版本了吗

确实写死了：https://github.com/alibaba/uirecorder/pull/407/commits/c413ccc989db820558e6c8221015b18b24cf4371

**Comment by qq937654393** [comment]
79版本的driver不是装在全局的，是要装在全局的uirecorder项目下。
输入npm ls chromedriver -g 可以看到你安装的位置。
你要到uirecorder目录下把package.json里面的chromedriver版本修改为79.0.0，然后cnpm install

**Comment by Stngle** [comment]
最新版 uirecorder 版本已更新至支持 chrome 80
