### ISSUE TITLE
uirecorder start的时候提示chrome init failed

### ISSUE THREAD

**Issue by Cayla-Xiong** [alibaba/uirecorder#421]
My Chrome version is 79.0.3945.88, ChromeDriver version is 79.0.3945.36, but the recording is performed in order to use UI Recorder: uirecorder start, prompted me
Chrome init failed!
session not created: This version of ChromeDriver only supports Chrome version 77
  (Driver info: chromedriver = 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs / branch-heads / 3865 @ {# 442}), platform = Mac OS X 10.14.6 x86_64)
Chrome init failed!
{Error: socket hang up
    at createHangUpError (_http_client.js: 342: 15)
    at Socket.socketOnEnd (_http_client.js: 437: 23)
    at emitNone (events.js: 111: 20)
    at Socket.emit (events.js: 208: 7)
    at endReadableNT (_stream_readable.js: 1064: 12)
    at _combinedTickCallback (internal / process / next_tick.js: 139: 11)
    at process._tickCallback (internal / process / next_tick.js: 181: 9) code: 'ECONNRESET'}

**Comment by Stngle** [comment]
> My Chrome version is 79.0.3945.88, ChromeDriver version is 79.0.3945.36, but the recording is performed in order to use UI Recorder: uirecorder start, prompted me
> Chrome init failed!
> session not created: This version of ChromeDriver only supports Chrome version 77
> (Driver info: chromedriver = 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs / branch-heads / 3865 @ {# 442}), platform = Mac OS X 10.14.6 x86_64)
> Chrome init failed!
> {Error: socket hang up
> at createHangUpError (_http_client.js: 342: 15)
> at Socket.socketOnEnd (_http_client.js: 437: 23)
> at emitNone (events.js: 111: 20)
> at Socket.emit (events.js: 208: 7)
> at endReadableNT (_stream_readable.js: 1064: 12)
> at _combinedTickCallback (internal / process / next_tick.js: 139: 11)
> at process._tickCallback (internal / process / next_tick.js: 181: 9) code: 'ECONNRESET'}

update uirecorder to the lastst version
