### ISSUE TITLE
source run.sh sample/test.spec.js 报错

### ISSUE THREAD

**Issue by PiterYang** [alibaba/uirecorder#424]
source run.sh sample/test.spec.js
sample/test.spec : chrome
    1) "before all" hook

  0 passing (30ms)
  1 failing
"before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)

浏览器版本：79 最新

**Comment by Cayla-Xiong** [comment]
> source run.sh sample/test.spec.js
> sample/test.spec : chrome
> 1) "before all" hook
> 
> 0 passing (30ms)
> 1 failing
> "before all" hook:
> Error: connect ECONNREFUSED 127.0.0.1:4444
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
> 
> 浏览器版本：79 最新

没有起本地服务

// 进入工程目录
cd ~/Documents/uirecorder_test
// 启动 webdriver 服务
npm run server

试试看

**Comment by PiterYang** [comment]
恩恩  可以啦  谢谢 @Cayla-Xiong
