### ISSUE TITLE
国外机器上录制时登录谷歌邮箱失败

### ISSUE THREAD

**Issue by MLittleMandy** [alibaba/uirecorder#428]
国外机器环境本身访问谷歌邮箱没问题，录制脚本的时候输入谷歌账号，就弹出对话框：
 
Couldn't sign you in
this browser or app may nobt be secure.
Try using a different browser.If you're already using a supported browser,you can refresh your screen and try again to sign in.

求大佬们帮解决，膝盖奉上！

**Comment by Stngle** [comment]
使用chrome浏览器无痕模式操作试试
