### ISSUE TITLE
Start install project dependencies...卡死

### ISSUE THREAD

**Issue by aidaijinxi** [alibaba/uirecorder#429]
环境：
电脑：windows X64
nodejs版本：v10.16.0
chrome版本： 79.0.3945.88
chromedriver版本：
![image](https://user-images.githubusercontent.com/35913169/71947787-e74e0a80-3208-11ea-8b1c-2b436ac4fca3.png)

问题：
Start install project dependencies...页面长时间无反应
![image](https://user-images.githubusercontent.com/35913169/71947871-28deb580-3209-11ea-8a80-6de9c19260b8.png)

**Comment by Stngle** [comment]
参考文档 F&Q
https://www.yuque.com/artist/uirecorder/tvgfwo#KdyXC
