### ISSUE TITLE
手动定位元素的教程

### ISSUE THREAD

**Issue by gujiangfei1221** [alibaba/uirecorder#43]
您好：
由于我这边的系统较多使用了iframe嵌套，导致自动录制生成的脚本无法成功运行，查看脚本发现定位dom元素的方式比较像xpath（不太确定），请问下有定位元素的demo教程吗，我想手工修改我的脚本，去定位那些无法识别的元素，谢谢！

**Comment by gujiangfei1221** [comment]
应该是webdriver的css选择器方式来定位的，已经找到相关帖子了，谢谢

**Comment by yaniswang** [comment]
什么场景下无法定位？发个问题场景的URL地址，我来测试下。
理论上，应该不太可能出现无法支持的场景。

**Comment by gujiangfei1221** [comment]
![图片1](http://ogbrn31xz.bkt.clouddn.com/github1.png)
![图片2](http://ogbrn31xz.bkt.clouddn.com/github2.png)
![图片3](http://ogbrn31xz.bkt.clouddn.com/github3.png)

**Comment by gujiangfei1221** [comment]
- 没有外网地址，无法提供，不好意思
- 大概原因就是脚本switch frame时候失败了，没有定位到录制生成的iframe
- 尝试过修改这段脚本，手工定位这个iframe，但是没成功（可能我定位策略有问题）

**Comment by yaniswang** [comment]
知道了，问题出在随机值
name="mini-iframe-190"

有两个解决方案：
1. 让开发修改这个name，改为非随机
2. uirecorder init，属性值黑名单中添加正则：/mini-iframe-\d+/

**Comment by gujiangfei1221** [comment]
@yaniswang 
1、看了下，name="mini-iframe-190"不是随机值，是固定值
2、使用属性值黑名单规则后录制脚本也不可以
3、想咨询下类似多个iframe嵌套的情况下，脚本中switchframe是不是要把所有的iframe都遍历一遍还是只要定位当前的iframe

**Comment by yaniswang** [comment]
是iframe套了一个iframe？
这种复杂的iframe嵌套，目前不支持。

**Comment by gujiangfei1221** [comment]
- 我测试了下xpath定位元素是可以实现模拟登录，点击按钮这些操作，但是也无法实现点击嵌套iframe里元素
- 大神如果方便的话，可否支持iframe嵌套这种结构的回放，我们的系统较多使用了iframe嵌套(￣┰￣*)

**Comment by yaniswang** [comment]
iframe嵌套目前真的是无能为力，要大手术了，整个内核要翻天覆地的变化。

目前只支持1层iframe的自动录制。

**Comment by gujiangfei1221** [comment]
- 再和您确认下，是因为jwebdriver无法支持iframe嵌套，导致运行脚本时无法识别嵌套iframe内的元素对吧（因为我感觉uirecorder是能正确录制嵌套iframe的脚本的）
- 目前的蛮好的，加油！

**Comment by yaniswang** [comment]
jwebdriver本身是支持嵌套iframe的，是因为uirecorder目前不支持嵌套iframe，因为嵌套iframe就导致对iframe的定位复杂多了。

原先我们只有两个概念：window, frame

每次操作，都要指定一个window和frame，如果是嵌套iframe，那一个frame参数就无法满足需求了

**Comment by gujiangfei1221** [comment]
```
    callSpec('commons/common.spec.js');
    
    //切换到第一层iframe，用xpath定位没问题
    it('switchFrame: div.mini-panel-body > iframe', function(){
        return driver.switchFrame(null)
               .wait('/html/body/div[5]/div/div[2]/div[2]/iframe', 30000).then(function(element){
                   return this.switchFrame(element).wait('body');
               });
    });

    it('mouseUp: #jianshedanweiguid span.mini-buttonedit-icon, 2.515625, 17, 0', function(){
        return driver.sleep(300).wait('#jianshedanweiguid span.mini-buttonedit-icon', 30000)
               .sleep(300).mouseMove(2.515625, 17).mouseUp(0);
    });

    it('click: #jianshedanweiguid span.mini-buttonedit-icon, 3, 17, 0', function(){
        return driver.sleep(300).wait('#jianshedanweiguid span.mini-buttonedit-icon', 30000)
               .sleep(300).mouseMove(3, 17).click(0);
    });
    
    //切换到第二层iframe，仍然使用xpath定位，则无法找到第二层iframe
    it('switchFrame: div.mini-panel-body > iframe', function(){
        return driver.sleep(5000).switchFrame(null)
               .wait('/html/body/div[5]/div/div[2]/div[2]/iframe/html/body/div[5]/div/div[2]/div[2]/iframe', 30000).then(function(element){
                   return this.switchFrame(element).wait('body');
               });
    });

    it('mouseDown: #datagrid tr:nth-child(2) > td.mini-grid-rightCell > div.mini-grid-cell-nowrap > a.icon-addcirclefilled, 3, 11, 0', function(){
        return driver.sleep(300).wait('#datagrid tr:nth-child(2) > td.mini-grid-rightCell > div.mini-grid-cell-nowrap > a.icon-addcirclefilled', 30000)
               .sleep(300).mouseMove(3, 11).mouseDown(0);
    });

    it('mouseUp: #datagrid table.mini-grid-rowstable > tbody, 863, 18, 0', function(){
        return driver.sleep(300).wait('#datagrid table.mini-grid-rowstable > tbody', 30000)
               .sleep(300).mouseMove(863, 18).mouseUp(0);
    });
```

那理论上我把uirecorder录制好的脚本修改，自己手动定位嵌套iframe，应该可以实现操作嵌套iframe的元素的把，但是我这样改了并没有用

**Comment by yaniswang** [comment]
`/html/body/div[5]/div/div[2]/div[2]/iframe/html/body/div[5]/div/div[2]/div[2]/iframe`

你这种写法有问题，XPATH的定位应该只需要相对当前document的，不需要从最外面document开始定位。

**Comment by gujiangfei1221** [comment]
- 问题解决了，切换到第二层iframe时候，要挨个切换，不能一次切换，同时使用xpath定位，可以解决id随机值的问题，第二次的切换代码：
```
    //先切换到main page
    it('switchFrame: div.mini-panel-body > iframenull', function(){
        return driver.switchFrame(null);
    });
    
    //切换到第一层iframe
    it('switchFrame: div.mini-panel-body > iframe22', function(){
        return driver.wait('/html/body/div[5]/div/div[2]/div[2]/iframe', 30000).then(function(element){
                   return this.switchFrame(element).wait('body');
               });
    });
 
    //切换到第二层iframe
    it('switchFrame: div.mini-panel-body > iframe222', function(){
        return driver.wait('/html/body/div[5]/div/div[2]/div[2]/iframe', 30000).then(function(element){
                   return this.switchFrame(element).wait('body');
               });
    });
```
- 还发现一个问题，鼠标悬停操作，默认的等待时间视300ms，导致我的脚本有时候能成功运行，有时候失败，这边可以把等待时间加长点，这样可以保证每次运行成功，提高稳定性
- 非常感谢大神的热心解答

**Comment by yaniswang** [comment]
为什么悬停300ms还是不够？你的悬停后，会有ajax请求？

**Comment by gujiangfei1221** [comment]
应该是有的，我抓包看了下，悬停后会触发请求，返回的响应里是子菜单数据（子菜单很多），然后页面解析渲染子菜单，显示子菜单

**Comment by aaawhz** [comment]
it('mouseDown: 共享 ( a[name="listMenuBtn"]:nth-child(3), 19, 9, 0 )', async function(){
        await driver.sleep(300).wait('#list_menu_tr_1 > td:nth-child(3) > div > div > div > a:nth-child(3)', 30000)
               .sleep(300).mouseMove(19, 9).mouseDown(0);
    });

    it('mouseUp: 共享 ( #list_menu_tr_1 td > div.listwrap > div > div.sd-hoverbar, 87, 9, 0 )', async function(){
        await driver.sleep(300).wait('#list_menu_tr_1 > td:nth-child(3) > div > div > div > a:nth-child(3)', 30000)
               .sleep(300).mouseMove(87, 9).mouseMove(87, 9).mouseUp(0);
    });

    it('switchFrame: null', async function(){
        await driver.switchFrame(null);
    });

    it('click: searchKey ( #searchKey, 62, 11, 0 )', async function(){
        await driver.sleep(300).wait('#searchKey', 30000)
               .sleep(300).mouseMove(62, 11).click(0);
    });

    it('sendKeys: cicy1', async function(){
        await driver.sendKeys('cicy1');
    });

    it('click: cic.ma... ( #tab_search_div a > span:nth-child(1), 43, 9, 0 )', async function(){
        await driver.sleep(300).wait('#tab_search_div a > span:nth-child(1)', 30000)
               .sleep(300).mouseMove(43, 9).click(0);
    });

**Comment by aaawhz** [comment]
点击共享， 弹窗， #searchKey是弹窗中的一个input, 居然找不到， 弹窗应该是在外层的iframe上。

**Comment by aaawhz** [comment]
为什么弹窗就会执行这句：

 it('switchFrame: null', async function(){
    await driver.switchFrame(null);
});

**Comment by aaawhz** [comment]
![image](https://user-images.githubusercontent.com/6637737/30317628-38e65686-97dd-11e7-847b-80603399602c.png)

**Comment by yaniswang** [comment]
你这个场景是不是有二级iframe？
目前uirecorder只支持一级ifame场景，不支持二级及以上的。

**Comment by aaawhz** [comment]
只有一个iframe啊

**Comment by aaawhz** [comment]
从外层的主页面跳转到里面的iframe是可以检测到， 点击iframe的共享按钮， 会有个弹窗， 这个弹窗位于iframe之外的主页面； 弹窗后， 会switch(null)

**Comment by aaawhz** [comment]
may be i should improve you code by my self , can i commit on this project, 看的懂我说什么。。。

**Comment by yaniswang** [comment]
如果是弹窗位于主页面，那切换switch(null)应该是正确的啊
因为之前是处在iframe里，所以要通过switch(null)切换到主窗口

switch(null)的意思就是切换到非iframe窗口
