### ISSUE TITLE
source run.sh sample/top15.spec.js cese 跑完后报错！

### ISSUE THREAD

**Issue by PiterYang** [alibaba/uirecorder#430]
设备 MacOS 10.14.5
chrome版本： 79.0.3945.88

sample/top15.spec : ie 11
    1) "before all" hook

  31 passing (45s)
  1 failing

  1) sample/top15.spec : ie 11
       "before all" hook:
     Error: the string "Unable to create new service: InternetExplorerDriverService\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'MacBook-Pro.local', ip: 'fe80:0:0:0:1025:e6b8:e73e:941c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_211'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by Stngle** [comment]
mac 系统不存在 ie 浏览器，`config.json` 文件 browser 配置去掉 ie 11 即可
