### ISSUE TITLE
录制回放脚本的时候source run.sh ，生成的报告会覆盖之前的报告

### ISSUE THREAD

**Issue by liyaoyao6342** [alibaba/uirecorder#436]
问题:source run.sh 运行录制的脚本的时候，会在reports文件夹里生成index.html，但是第二次执行会覆盖之前生成的index.html，这个怎么避免呀

**Comment by Stngle** [comment]
3.2.0 版本后，支持自定义报告路径 https://www.yuque.com/artist/uirecorder/qghot5#eRycp

或者每次运行结束后，拷贝报告至其他路径保存，按时间维度区分
