### ISSUE TITLE
【window】 有公共用例时路径好像错了

### ISSUE THREAD

**Issue by ohmydengzi** [alibaba/uirecorder#44]
![image](https://cloud.githubusercontent.com/assets/13642149/20562072/c4ef467c-b1bc-11e6-82dc-c21d43a53d90.png)

存在commons目录，里面也已经放了公共用例了，多层嵌套用例时路径貌似出错了。看那个反斜杠

**Comment by yaniswang** [comment]
试试最新版的v2.1.14

npm i uirecorder@2.1.14 -g

我调整过公共用例的逻辑，修复了之前的问题。

**Comment by yaniswang** [comment]
你这个多层嵌套用例的场景，我测试下

**Comment by yaniswang** [comment]
试了，新版中，多层嵌套也正常

**Comment by ohmydengzi** [comment]
嗯，是可以了
