### ISSUE TITLE
判断元素是否display() 一直报错

### ISSUE THREAD

**Issue by stephenwang1011** [alibaba/uirecorder#445]
录制时候，方法是 根据dom 来判断 是否displayed(),  我可以明确手这个元素是不存在的 ，但是在判时候 提示：
  1) test : chrome
       expect: displayed, #su, equal, true:
     AssertionError: expected [Error: AssertionError: expected [Error: Wait element displayed timeout: #su ,30000ms] not to be an error] to equal true

这是我的判断代码：
`     it('expect: displayed, #su, equal, false', async function(){
        await driver.sleep(300).wait('#su', 30000)
            .displayed()
            .should.not.be.a('error')
            .should.equal(_(false));
    });
`

**Comment by stephenwang1011** [comment]
.displayed()方法不是返回的 true或者false吗？  如果找不到肯定返回的是false， 这个元素肯定是不存在，应该返回false才对，但是 error信息却抛出了 等待元素超时。

**Comment by Stngle** [comment]
displayed() 的前提是元素加载到，渲染的样式 display 为 true/false

**Comment by huibiaoli** [comment]
我用这种写法解决了
`
await driver.sleep(300).wait('#su', {noerror: true}).should.not.be.a('error').should.have.lenghtOf(0);
`

**Comment by stephenwang1011** [comment]
> 我用这种写法解决了
> `await driver.sleep(300).wait('#su', {noerror: true}).should.not.be.a('error').should.have.lenghtOf(0);`

我换了个方法 绕过去了  达到了同样的目的

**Comment by huibiaoli** [comment]
@stephenwang1011 咋绕的？

**Comment by stephenwang1011** [comment]
> @stephenwang1011 咋绕的？

需求可能不一样 绕过去的方式不一样吧。
我是 判断当前的 网页内不包含 这个 我指定的文本 绕过去的，能达到我的需求
