### ISSUE TITLE
npm install uirecord mocha -g 安装到chromedriver时出错

### ISSUE THREAD

**Issue by iez1784** [alibaba/uirecorder#447]
D:\ui_recorder>npm install uirecorder mocha -g

> typechecker@2.0.8 preinstall C:\Users\xx\AppData\Roaming\npm\node_modules\uirecorder\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js

> typechecker@2.0.8 preinstall C:\Users\xx\AppData\Roaming\npm\node_modules\uirecorder\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

C:\Users\xx\AppData\Roaming\npm\mocha -> C:\Users\xx\AppData\Roaming\npm\node_modules\mocha\bin\mocha
C:\Users\xx\AppData\Roaming\npm\_mocha -> C:\Users\xx\AppData\Roaming\npm\node_modules\mocha\bin\_mocha
C:\Users\xx\AppData\Roaming\npm\uirecorder -> C:\Users\xx\AppData\Roaming\npm\node_modules\uirecorder\bin\uirecorder

> chromedriver@80.0.1 install C:\Users\xx\AppData\Roaming\npm\node_modules\uirecorder\node_modules\chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip
Saving to file: C:\Users\xx\AppData\Local\Temp\80.0.3987.16\chromedriver\chromedriver_win32.zip
ChromeDriver installation failed Error: Error with http(s) request: Error: getaddrinfo ENOTFOUND 3128
    at requestBinary (C:\Users\xx\AppData\Roaming\npm\node_modules\uirecorder\node_modules\chromedriver\install.js:254:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules\mocha\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

**npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@80.0.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@80.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.**

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx\AppData\Roaming\npm-cache\_logs\2020-03-25T10_53_13_440Z-debug.log

如果手动下载后放在对应的文件目录，重新再安装，还是会失败
环境:
windows 10
node: V12.16.1
npm:  6.13.4

npm config set proxy =xxx 后安装还是有同样的问题

**Comment by Stngle** [comment]
安装依赖工程目录下执行 

npm install
npm run installdriver

即可

**Comment by iez1784** [comment]
> 安装依赖工程目录下执行
> 
> npm install
> npm run installdriver
> 
> 即可

yes，搞定。但是在UIRecorder  init时又报在淘宝镜像下载selinum-standlone 403，就停掉了
