### ISSUE TITLE
uirecorder init below git bash

### ISSUE THREAD

**Issue by iez1784** [alibaba/uirecorder#448]
在git bash下初始化项目，提示报错无法从淘宝镜像获取selenium-standlone

Start install project dependencies...
--------------------------------------------

(node:6672) UnhandledPromiseRejectionWarning: Error: GET https://registry.npm.taobao.org/selenium-standalone/download/selenium-standalone-6.17.0.tgz response 403 status
    at get (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\uirecorder\node_modules\npminstall\lib\get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\uirecorder\node_modules\co\index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Stngle** [comment]
直接访问 https://registry.npm.taobao.org/selenium-standalone/download/selenium-standalone-6.17.0.tgz 网络能否连通

**Comment by iez1784** [comment]
> 直接访问 https://registry.npm.taobao.org/selenium-standalone/download/selenium-standalone-6.17.0.tgz 网络能否连通

不能，好像被公司网络挡掉了。

**Comment by iez1784** [comment]
> 直接访问 https://registry.npm.taobao.org/selenium-standalone/download/selenium-standalone-6.17.0.tgz 网络能否连通

不能连通，公司it策略。但是有帮把需要的 selenium-standalone-6.17.0.tgz 下载下来，那在UIRecorder init时，可以指定这个文件地址吗？ 如果可以，如何实现呢？ 谢谢

**Comment by Stngle** [comment]
node_modules 目录下

**Comment by iez1784** [comment]
> node_modules 目录下

是解压后放到npm安装的node-mdules下？ 还是init文件里的node_modules里呢？谢谢

**Comment by iez1784** [comment]
> node_modules 目录下

是解压后放到npm安装的node-mdules下？ 还是init文件里的node_modules里呢？谢谢
