### ISSUE TITLE
uirecorder init below git bash, pop exception

### ISSUE THREAD

**Issue by iez1784** [alibaba/uirecorder#450]
windows 10 机器， 在git bash下 作项目初始化，由于公司策略，屏蔽去taobao镜像下载 selenium-standloe，就断开初始化了。文件己经通过人工下载到本机，经过咨询，说是放在node_moudles里，见己关closed issue: https://github.com/alibaba/uirecorder/issues/448

但是我把文件解压放到 npm的uirecorder的node_moudles或是项目中的node_moudles，再作uirecorder init，一样还是要报错，
1. 请问是文件放的路径放错了吗？
2. 有什么办法可以绕过去外网下载安装selenium-standloe吗?

感谢

**Comment by Stngle** [comment]
可以外网下载完拷贝过去
