### ISSUE TITLE
运行uirecorder start 录制脚本的时候， 提示“UI Recorder”崩溃了。点击此信息框，以重新加载该扩展程序。“Chrome Automation Extension” 崩溃了。点击此信息框，以重新加载该扩展程序。

### ISSUE THREAD

**Issue by michangrong** [alibaba/uirecorder#453]
谷歌浏览器版本：79
`-- uirecorder@3.4.0
  `-- chromedriver@79.0.0

日志：
? 测试脚本文件名: sample/test.spec.js
? 打开同步校验浏览器？ Yes
? 浏览器大小 (格式：1024 x 768): 1024x768

录制服务器监听在端口: 60554

DevTools listening on ws://127.0.0.1:60556/devtools/browser/060b761b-ab66-4954-b8f7-911abc9658b5

DevTools listening on ws://127.0.0.1:60565/devtools/browser/2fe1d947-7bd7-4b8f-9593-fbd978e1e7f9
Chrome打开失败！
unknown error: failed to wait for extension background page to load: chrome-extension://njkfhfdkecbpjlnfmminhmdcakopmcnc/_generated_background_page.html
from no such window: window was already closed
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Windows NT 10.0.18362 x86_64)
Chrome打开失败！
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

**Comment by Stngle** [comment]
更新 uirecorder 至最新版本
