### ISSUE TITLE
config.json下vars全局变量 中变量值 不能使用表达式计算而获得吗

### ISSUE THREAD

**Issue by stephenwang1011** [alibaba/uirecorder#459]
如下图s所示，我想把zoneCode2这个变量值，修改成new Date().getTime() 这个表达式去计算，计算完成之后的值赋给 zoneCode2, 但是每次我取这个zoneCode2的值时候，都是没有经过计算的，值的内容是表达式本身。 希望指导一下，config.json下是否支持  变量值，动态赋值
![image](https://user-images.githubusercontent.com/3350356/80474717-60b96680-897a-11ea-9faf-31e8b28f6e3d.png)

**Comment by Stngle** [comment]
只能静态值，动态值需要修改脚本代码
