### ISSUE TITLE
V2.2.7版本录制初始页面，按钮没有名称

### ISSUE THREAD

**Issue by gujiangfei1221** [alibaba/uirecorder#46]
![](http://ogbrn31xz.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161130093411.png)

**Comment by yaniswang** [comment]
每次必现吗？

**Comment by gujiangfei1221** [comment]
- 昨天重装了下系统，今天重建搭建了下环境，现在的版本是2.2.10  ，没有此问题
- 2.2.7版本无法去复现此问题了，关闭此问题
