### ISSUE TITLE
ui Recorder 运行不起来 说打不开chrome 

### ISSUE THREAD

**Issue by AlexJinsin** [alibaba/uirecorder#47]
已经将chromedriver配置到环境变量中 启动macaca  初始化后启动不了
返回错误如下
——————

录制服务器监听在端口: 9765
Chrome打开失败！
unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9e
ed),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by yaniswang** [comment]
你本机有安装chrome吗？是安装在默认路径里？

**Comment by BreakCircle** [comment]
我的也出现这个问题，chrome路径为C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
![image](https://cloud.githubusercontent.com/assets/20987844/22873417/f54540aa-f1fa-11e6-9f9d-8e568749556a.png)

**Comment by yaniswang** [comment]
重启电脑还是出现这个问题吗？

**Comment by AlexJinsin** [comment]
这个问题done了吧 我已经不弄了

发自我的 iPhone
刘金鑫
Tel:18842612302
E-mail:liujinxin33@vip.qq.com
