### ISSUE TITLE
config.json中设置了firefox浏览器，但是执行脚本时一直启动的是chrome

### ISSUE THREAD

**Issue by CandyZhai** [alibaba/uirecorder#479]
1. ui recorder的版本是 3.4.3
2. 使用的是 selenium-standalone server，3.141.59
3. 在config.json中修改了浏览器配置，chrome，firefox， ie 11
执行脚本时候，每次回放都启动的是chrome浏览器，firefox和ie 11没有启动。
请问怎么解决?
查了资料有人说是更新到最新版，我的uirecorder是3.4.3，已经是最新版了。还有人说删掉 config.json中的chromeOption属性，试了一下，删掉后执行会报错。

求大神指点？

**Comment by Stngle** [comment]
更新至最新版本
