### ISSUE TITLE
Default chromeOptions in config.json is in the wrong block place

### ISSUE THREAD

**Issue by dhutsj** [alibaba/uirecorder#480]
The default chromeOptions in config.json is like this

"webdriver": {
        "host": "127.0.0.1",
        "port": "4444",
        "browsers": "chrome, ie 11"
    },
    "vars": {},
    "chromeOptions": {
        "w3c": false
    }

But the correct way shoule be like this
"webdriver": {
        "host": "127.0.0.1",
        "port": "4444",
        "browsers": "chrome, ie 11",
        "chromeOptions": {
            "w3c": false
        }

Windows 10, npm 12, chrome 80

**Comment by Stngle** [comment]
update to latest version

**Comment by dhutsj** [comment]
I installed uirecorder yesterday using cnpm according to [this link](https://www.yuque.com/artist/uirecorder/zslbnp). I checked your latest PR. I can see that you have fixed it. So I was wondering is there any delay between the latest master branch code and cnpm install uirecorder? Thank you.
