### ISSUE TITLE
使用uirecorder start启动，录制浏览器打不开

### ISSUE THREAD

**Issue by csudevinduan** [alibaba/uirecorder#486]
全最新版本 mac 、windows都试过，一样的报错
版本node v12.18.4
chrome 85
uirecorder v3.5.1
<img width="955" alt="image" src="https://user-images.githubusercontent.com/41943331/94364307-ddec3180-00fa-11eb-97a9-f0dcb364d3b5.png">

**Comment by Jouryjc** [comment]
same issue

**Comment by Stngle** [comment]
3.5.2 fixed

**Comment by jzhishu** [comment]
> 3.5.2 fixed

操作系统：win7
node版本：10.15.1
chrome版本： 76.0.3809.87
uirecorder版本：3.5.2
也出现了此问题
![image](https://user-images.githubusercontent.com/39545185/95965844-fd929200-0e3c-11eb-9880-8913128df97d.png)
![image](https://user-images.githubusercontent.com/39545185/95965803-ece21c00-0e3c-11eb-94b1-1ab70b3f4156.png)

**Comment by xudafeng** [comment]
This is the translated issue comment: @jzhishu

<hr/>

> 3.5.2 fixed

Operating System: win7
node version: 10.15.1
chrome version: 76.0.3809.87
uirecorder Version: 3.5.2
This problem also appeared
! [Image] (https://user-images.githubusercontent.com/39545185/95965844-fd929200-0e3c-11eb-9880-8913128df97d.png)
! [Image] (https://user-images.githubusercontent.com/39545185/95965803-ece21c00-0e3c-11eb-94b1-1ab70b3f4156.png)
