### ISSUE TITLE
install uirecorder fail

### ISSUE THREAD

**Issue by gabyliu** [alibaba/uirecorder#487]
npm install uirecorder -g

fail, fail message:
> chromedriver@86.0.0 install /usr/local/lib/node_modules/uirecorder/node_modules/chromedriver
> node install.js

ChromeDriver binary exists. Validating...
(node:5830) ExperimentalWarning: The fs.promises API is experimental
ChromeDriver is already available at '/tmp/86.0.4240.22/chromedriver/chromedriver'.
Copying to target path /usr/local/lib/node_modules/uirecorder/node_modules/chromedriver/lib/chromedriver
ChromeDriver installation failed { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/uirecorder/node_modules/chromedriver/lib/chromedriver'
    at Object.mkdirSync (fs.js:752:3)
    at copyIntoPlace (/usr/local/lib/node_modules/uirecorder/node_modules/chromedriver/install.js:302:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/usr/local/lib/node_modules/uirecorder/node_modules/chromedriver/lib/chromedriver' }

node version
v10.15.3

**Comment by jzhishu** [comment]
npm install uirecorder mocha -g --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
