### ISSUE TITLE
win7下运行报“before all” hook

### ISSUE THREAD

**Issue by angel8899421110** [alibaba/uirecorder#5]
win7下执行mocha *.spec.js提示1）“before all” hook
然后程序自动结束
错误图片链接：http://7rylt4.com1.z0.glb.clouddn.com/1.jpg

**Comment by angel8899421110** [comment]
![Uploading 1.pic.jpg…]()
如上图所示

**Comment by angel8899421110** [comment]
。。。

**Comment by linxu** [comment]
我也是,求解答~

**Comment by kellyping008** [comment]
遇到同样的问题，求解答。。。。

**Comment by yaniswang** [comment]
执行是需要连接webdriver server的。

关于WebDriver Server有以下几个方案：

1. 单机Selenium server
2. Selenium Grid
3. F2etest WebDriver云
