### ISSUE TITLE
Chrome 打开失败

### ISSUE THREAD

**Issue by cjydayang** [alibaba/uirecorder#50]
Chrome打开失败！
unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-3-deepin-amd64 x86_64)

启动uirecorder时失败，请问需要对Chrome进行哪些配置？

**Comment by yaniswang** [comment]
你的chrome版本是什么？

**Comment by cjydayang** [comment]
@yaniswang 54.0.2840.100 (64-bit)

**Comment by yaniswang** [comment]
还有别的错误信息吗？

**Comment by cjydayang** [comment]
@yaniswang 很奇怪，我今天又试了一下发现chrome可以弹出来了，我暂时先close掉，谢谢

**Comment by XuNeal** [comment]
打算测试iOS的使用碰到同样的问题：
![image](https://cloud.githubusercontent.com/assets/10441775/22626504/f14bb284-ebe9-11e6-9115-73ea59c3a5c7.png)

chrome版本55.0.2883.95 (64-bit)
