### ISSUE TITLE
uirecorderV2.2.18版本录制脚本问题

### ISSUE THREAD

**Issue by gujiangfei1221** [alibaba/uirecorder#51]
今天录制脚本发现生成的脚本有点问题，具体看下图，右边是录制后的原版脚本，左边是修改后能跑起来的脚本
![](http://ogbrn31xz.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161208185620.png)

- 问题1：录制的点击动作，生成的脚本为mousedown方法，但是需要改成click方法才行
- 问题2：点击链接打开新窗口后，没有生成switchWindow方法

> 链接地址：https://www.zhihu.com/roundtable/wintersports
> 具体操作为：打开链接地址，点击第一条问题会打开新窗口，然后关闭打开的新窗口，结束录制

请大神确认下是不是版本更新导致uirecorder的录制有点问题，因为之前的版本我可以操作很复杂的步骤，生成的脚本基本不用修改

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/21008888/b4d27246-bd7e-11e6-86e7-aa0601ff42af.png)

我录了一下，是这样的，mouseUp事件，估计是网页引起的

**Comment by yaniswang** [comment]
你的uirecorder是什么版本？

**Comment by gujiangfei1221** [comment]
@yaniswang   2.2.18版本

**Comment by gujiangfei1221** [comment]
今天用同事的老版本（V2.1.11）同样录制了下脚本，截图左边的test3.spec.js
![](http://ogbrn31xz.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161209082031.png)

**Comment by gujiangfei1221** [comment]
- 刚才又试了下另一个同事（V2.2.18）版本，他录制的脚本中有mouseUp事件，但是仍然没有switchWindow事件
- 让他在我本机（V2.2.18）同样操作一遍，生成的脚本只有mouseDown事件，也没有switchWindow事件
- 我卸载了uirecorder，然后重新安装了一遍，仍然无效

**Comment by yaniswang** [comment]
这个网页肯定有特殊性，你试试在这两个页面录一下：

http://news.baidu.com/
https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&SearchText=mp3

还有，你的chrome是什么版本？

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/21034273/828366ba-bdf1-11e6-9776-787c2d048611.png)

找到问题原因了，mouseDown后， class增加了一个，导致鼠标点击前后的样式不一样，从而导致生成的PATH也不一样。

最终导致mouseUp的触发控件变成了父节点。

不过你的mouseUp没录制到是比较奇怪，我这里可以录到，只是无法触发超链接点击，因为没有录成click

**Comment by yaniswang** [comment]
下一个版本，我会把focusin这个关键字加入黑名单，就可以解决这个场景。

**Comment by gujiangfei1221** [comment]
- mouseUp没有录制到应该是chrome版本导致的，原先的是56.XXXX  现在换成54.XXXX就可以录制到mouseUp了
- 但是生成的脚本中还是少了switchWindow的事件

**Comment by yaniswang** [comment]
等我下个版本，你再试下。

**Comment by gujiangfei1221** [comment]
好的

**Comment by yaniswang** [comment]
你是zhihu公司的？

**Comment by gujiangfei1221** [comment]
不是，只是找一个你也可以访问的地址，方便你查原因 :)

**Comment by yaniswang** [comment]
加下我们的QQ群交流吧： 416221937

**Comment by gujiangfei1221** [comment]
- 已经加了，只是觉得有时候群里问一些问题会被刷掉；而且这边登记了后面的人遇到也可以查询了解
- 那我以后群里咨询群主大人

**Comment by yaniswang** [comment]
问题记录issue是个好习惯，方便对问题进行跟踪。

**Comment by gujiangfei1221** [comment]
> uirecorder   V2.2.18版本，chrome 54.XXXX
- 录制的时候如果不开启校验浏览器，录制的步骤显示有switchWindow，但是生成的脚本中没有
- 录制的时候如果校验浏览器，录制的步骤和生成的脚本中都有switchWindow
```
λ uirecorder start
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.2.18

------------------------------------------------------------------

? 配置文件 config.json
? 测试脚本文件名 2.spec.js
? 打开同步校验浏览器？ Yes
? 浏览器大小，格式：1024 x 768 maximize

录制服务器监听在端口: 9765
校验浏览器已开启
录制浏览器已开启

------------------------------------------------------------------

  url: http://www.hfggzy.com/hfzbtb/ztbzx/
   √ 执行成功
  waitBody:
   √ 执行成功
  scrollTo: 0, 0
   √ 执行成功
  click: 关闭 ( #gg0 font, 5, 9, 0 )
   √ 执行成功
  click: 市公管局召开“讲看齐... ( #menutab_1_1 tr:nth-child(1) > td:nth-child(2) > a > font, 249, 10, 0 )
   √ 执行成功
  switchWindow: 1
   √ 执行成功
  waitBody:
   √ 执行成功
  closeWindow:
   √ 执行成功
  switchWindow: 0
   √ 执行成功
  scrollTo: 0, 300
   √ 执行成功

------------------------------------------------------------------

共录制10个步骤，其中校验通过: 10个，校验失败: 0个
录制脚本已保存: 2.spec.js

录制服务器已关闭
录制浏览器已关闭
校验浏览器已关闭

C:\Users\gujiangfei\Desktop\1209  (uirecorderTest@1.0.0)
λ uirecorder start
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.2.18

------------------------------------------------------------------

? 配置文件 config.json
? 测试脚本文件名 3.spec.js
? 打开同步校验浏览器？ No
? 浏览器大小，格式：1024 x 768 maximize

录制服务器监听在端口: 9765
录制浏览器已开启

------------------------------------------------------------------

  url: http://www.hfggzy.com/hfzbtb/ztbzx/
  waitBody:
  scrollTo: 0, 0
  scrollTo: 0, 100
  click: 市公管局召开“讲看齐... ( #menutab_1_1 tr:nth-child(1) > td:nth-child(2) > a > font, 234, 10, 0 )
  switchWindow: 1
  waitBody:
  mouseDown: #TDContent div:nth-child(3) > span:nth-child(2), 499, 39, 0
  scrollTo: 0, 200
  mouseUp: #TDContent div:nth-child(3) > span:nth-child(2), 499, 39, 0
  closeWindow:
  switchWindow: 0
  click: body, 134, 397, 0
  scrollTo: 0, 300

------------------------------------------------------------------

共录制12个步骤 (未经过校验)
录制脚本已保存: 3.spec.js

录制服务器已关闭
录制浏览器已关闭
```

![](http://ogbrn31xz.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161209104258.png)

**Comment by yaniswang** [comment]
关了校验，还真的会少switchWindow

是一个代码上的缺陷，下一个版本修复，感谢反馈

**Comment by gujiangfei1221** [comment]
大神，还有一个问题需要您确认下，开启校验的情况下，如果打开新窗口后，当前浏览器会切换到校验浏览器（没有录制工具栏的浏览器），然后需要人工切回录制的浏览器（有录制工具栏的浏览器），导致有时候误操作了校验浏览器，录制失败

**Comment by yaniswang** [comment]
我这里没出现过这个问题，虽然校验浏览器也会弹出，但是窗口并没有切换过去。

你是mac还是windows？

**Comment by gujiangfei1221** [comment]
win 10系统

**Comment by yaniswang** [comment]
明白你的意思，误操作了引起失败，那是无解的。

下次注意点就好。
