### ISSUE TITLE
设置指定浏览器大小无法运行脚本

### ISSUE THREAD

**Issue by gujiangfei1221** [alibaba/uirecorder#57]
- 录制生成的脚本中，修改了原先设置的`self.driver = driver.session(sessionConfig).maximize();`，改为打开指定大小窗口：`self.driver = driver.session(sessionConfig).size(1366,768);`，但是回放脚本打开chrome后就停止不动了
- 如果是打开全屏，脚本运行没有问题
- 如果是打开指定大小，脚本卡住无法继续运行
- 麻烦大神看下是什么问题导致的，打开百度的例子就可以；uirecorder版本：2.3.27

打开指定大小窗口截图：
![打开指定大小窗口截图](http://ogbrn31xz.bkt.clouddn.com/20170207001.png)
全屏窗口截图：
![全屏窗口截图](http://ogbrn31xz.bkt.clouddn.com/20170207002.png)
代码截图：
![代码截图](http://ogbrn31xz.bkt.clouddn.com/20170207003.png)
卡住截图：
![卡住截图](http://ogbrn31xz.bkt.clouddn.com/20170207004.png)

**Comment by yaniswang** [comment]
命令行的截图发出来看下

**Comment by gujiangfei1221** [comment]
- 命令行就一直显示这样
![](http://ogbrn31xz.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170208105145.jpg)

- 脚本截图：
![](http://ogbrn31xz.bkt.clouddn.com/20170208001.jpg)

**Comment by yaniswang** [comment]
你这个用例代码是哪个版本uirecorder生成的？
最新版的已经不是这个格式了

**Comment by yaniswang** [comment]
变更为.windowSize(x, y)了

**Comment by gujiangfei1221** [comment]
- 我是升级的最新版本（2.3.27）录制的
- 原来的size方法我是看的jwebdriver的api文档写的，所以失败了，改为windowSize方法成功解决问题
- 还有个问题想请教下：如果我回放脚本，我想先让浏览器按下F11，实现全屏化，这个代码我是这样写的：```
it('test',function(){
        return driver.keyDown(driver.Keys.F11);
    });
```
- 提示报错：TypeError: Cannot read property 'F11' of undefined

**Comment by yaniswang** [comment]
windowSize方法是在promise class中，因为api冲突了，才变更的。

按键这个我不太清楚，没尝试过让IE全屏，为什么会有这个需求？

**Comment by gujiangfei1221** [comment]
- 我们想用uirecorder进行一个兼容性测试，但是脚本很长的话，截图文件也相应很多，人工查看比较麻烦
- 所以准备写个python脚本对生成的截图文件做个处理，切割图片并进行像素比对，然后拼接图片，这样我们测试人员只要根据处理后的图片重点关注下，就可以知道兼容性问题在哪

- 但是目前存在一个问题，我们发现uirecorder生成的不同浏览器截图分辨率略微有点差别（不同浏览器标题栏高度不一致导致），这样会影响切割像素对比的准确度，所以我们想了两种方案：1）对于不同浏览器设置不同的大小，保证截图的分辨率一致；2）浏览器先按F11，此时截图的分辨率理论上应该一致

> 参考帖子：http://ftopia.cn/2016/06/14/UI%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95%E2%80%94%E2%80%94%E9%A1%B5%E9%9D%A2%E5%B7%AE%E5%BC%82%E6%A3%80%E6%B5%8B.html

**Comment by yaniswang** [comment]
了解了，那这个issue我关闭了
