### ISSUE TITLE
PC端录制脚本、执行脚本，出现错误

### ISSUE THREAD

**Issue by BreakCircle** [alibaba/uirecorder#59]
在学习使用uirecorder时遇到下面问题，麻烦帮我指点下

![image](https://cloud.githubusercontent.com/assets/20987844/22854948/7ebe24d6-f0b2-11e6-9806-3d01c2d6b615.png)
见上图：
1. edit hosts file，具体编辑为什么样？能否给个例子，如127.0.0.1:4444，是这样吗？
2.Start WebDriver Server，具体是哪一个？是selenium-standalone server？有什么意义？录制过程一直要启动吗？
3.录制完成后，执行脚本的时候需要启动   macaca server --port 4444 ----verbose  吗？
4.执行脚本的时候，使用run.bat运行脚本，报错，见下图

![image](https://cloud.githubusercontent.com/assets/20987844/22855033/f48e2340-f0b3-11e6-81ec-88ab7fc4d1b5.png)
5.执行脚本的时候，macaca run -p 4444 -d test.spec.js --verbose，出现下面错误：
![image](https://cloud.githubusercontent.com/assets/20987844/22855042/263da4ba-f0b4-11e6-9157-dca1937a1a51.png)

**Comment by yaniswang** [comment]
1.  你们公司在开发过程中，不需要修改hosts绑定吗？发布过程中，不需要通过hosts绑定将某个域名指向发布机，然后启动自动化
2. uirecorder是基于webdriver协议实现的一整套自动化解决方案，因此我们需要连接到webdriver server用来控制各种浏览器，具体如何启动server，文档中下方有说明
3. macaca也算是一种webdriver server，如果是基于pc的自动化，我们还是建议使用官方的，macaca更适合用于无线端的自动化
4. 请严格按照手册步骤来操作，你缺少执行了一个重要步骤：npm install
