### ISSUE TITLE
Ubuntu kylin 16.10使用uirecorder 连接安卓手机进行录制时"手机打开失败，请检查macaca是否配置正确？ Internal Server Error"

### ISSUE THREAD

**Issue by BreakCircle** [alibaba/uirecorder#60]
1. 系统为Ubuntu kylin 16.10，数据线连接安卓手机魅族MX4 PRO，手机版本Android5.1.1；如图，uirecorder 连接安卓手机进行录制时，出现下面错误：
![default](https://cloud.githubusercontent.com/assets/20987844/22968185/6f5d844c-f3a4-11e6-8e79-3cd09843283d.png)
2.服务端的信息如下：
![default](https://cloud.githubusercontent.com/assets/20987844/22968298/ce2c3fe0-f3a4-11e6-82e0-66689eb09185.png)
3.macaca doctor环境如下：
![default](https://cloud.githubusercontent.com/assets/20987844/22968350/03979350-f3a5-11e6-8d67-a8362549ad28.png)
4.麻烦帮我看看是哪里出问题了，谢谢。

**Comment by yaniswang** [comment]
macaca内部的问题，我没能力解答。
这个只能在macaca社区进行咨询了。

**Comment by BreakCircle** [comment]
@yaniswang 十分感谢
