### ISSUE TITLE
uirecorder执行录制脚本的时候报错

### ISSUE THREAD

**Issue by BreakCircle** [alibaba/uirecorder#61]
1.ubuntu kylin 16.10,pc录制完脚本后，运行source run.sh sample/test.spec.js执行脚本报错；
2.是不是host文件：127.0.0.1（这个写的对吗）
![default](https://cloud.githubusercontent.com/assets/20987844/22970008/79a3b9ce-f3ab-11e6-9524-64c894fce9dd.png)
![default](https://cloud.githubusercontent.com/assets/20987844/22970029/897bc8f0-f3ab-11e6-8485-74f2088dd210.png)
2.macaca doctor情况如下：
![default](https://cloud.githubusercontent.com/assets/20987844/22970339/c2fdbd3a-f3ac-11e6-88c2-498945a3f9f1.png)

**Comment by yaniswang** [comment]
看看macaca那边的报错日志

**Comment by BreakCircle** [comment]
这个问题是因为我没有启动selenium-standalone导致的。启动之后，脚本可以正确运行；
再请教个问题：如果使用本机进行录制和测试，host文件是不是不用修改？

**Comment by BreakCircle** [comment]
非常感谢你的 指点，谢谢@yaniswang

**Comment by yaniswang** [comment]
hosts要不要修改，取决你有没有hosts修改的需求啊
如果你的自动化是基于线上跑的，那就不用修改。
如果你的自动化是基于线下环境跑的，那就要修改hosts.

**Comment by BreakCircle** [comment]
@yaniswang 明白了 谢谢
