### ISSUE TITLE
脚本通用性问题

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/uirecorder#62]
目前uirecorder录制的脚本，Android与ios录制的脚本是完全不同的，基本基于xpath去录制的，虽说脚本录制的相对正确性，但是与macaca设计的脚本共用性相违背，有没有更好的方式或思路来实现录制的脚本跨系统的通用性？

**Comment by yaniswang** [comment]
android和ios的脚本基本上基本一样的吧？只是生成的path不一样。

如果开发上有办法把两边的id保持一致，甚至可以做到android和ios的测试脚本完全一样。

**Comment by CodeToSurvive1** [comment]
恩 所以如果在一个平台录制的话 还是需要手工替换掉另外一个平台的xpath

所以是否可以提供相关根据通用性的相关配置来生成脚本，比如添加配置文件中的通用性属性参数，添加了之后生成的脚本会根据id或者text或者name这种具有通用性的属性来生成脚本 

或者是在生成的脚本文件中直接默认全部生成所有的根据id，name，text，xpath的脚本，但是id，name，text相关的脚本代码是注释掉的，xpath的代码是解注释的，这样就可以手工去修改下录制的脚本了，而不用去根据inspector去查找id或者name或者text了

**Comment by xudafeng** [comment]
录制两次，维护xpath规则映射是最绿色的方案了。

**Comment by CodeToSurvive1** [comment]
录制两次还是麻烦  但是我的思路也还是可能存在问题  好像也没更好的方案
