### ISSUE TITLE
移动端录制的时候报错 Please connect your mobile,or open emulator first

### ISSUE THREAD

**Issue by thanksdanny** [alibaba/uirecorder#63]
当我输入了 `uirecorder start --mobile sample/test.spec.js`后，提示报错 `Please connect your mobile, or open emulator first.`

我使用 itunes 是能查看到我的设备的，然后运行命令 `ideviceinfo -x ` 也能获取到设备信息，想知道我是什么错误导致的吗？

**Comment by thanksdanny** [comment]
发现启动模拟器是没用问题的，但真机却提示报错

**Comment by yaniswang** [comment]
目前无线录制还不支持ios的真机

**Comment by thanksdanny** [comment]
soga

**Comment by thanksdanny** [comment]
@yaniswang 但是我在 testerhome 参照一位朋友的说法，将设备名字改成 iPhone，然后就可以打开露珠了，但录制到登陆步骤就出现这个错误，[传送门](https://github.com/alibaba/uirecorder/issues/64#issuecomment-282607694)

**Comment by yaniswang** [comment]
目前最新2.4.0版本已经支持ios真机
