### ISSUE TITLE
每次录制到登陆界面就会出现卡死，服务器报错socket hang up 

### ISSUE THREAD

**Issue by thanksdanny** [alibaba/uirecorder#64]
启动 uirecorder 录制都是正常的，步骤都是ok，但每次到登录跳转到登陆成功这一过程，浏览器就会卡死，不会在继续获得下一步。服务器报错 socket hang up

这是 uirecorder 的 log (app的名字跟登陆密码我都打 * 标记掉)

Recorder server listen on: 9765
Recorder browser opened
  click: Allow ( //*[@name="Allow"] )
   ✓ execute succeed
  click: 登录 ( //*[@name="登录"] )
   ✓ execute succeed
  click: //*[@name="比邻"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField
   ✓ execute succeed
  val: 1******
   ✓ execute succeed
  click: //*[@name="****"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSecureTextField
   ✓ execute succeed
  click: //*[@name="****"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField
   ✓ execute succeed
  click: //*[@name=****"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther
   ✓ execute succeed
  click: custom nav back icon ( //*[@name="custom nav back icon"] )
   ✓ execute succeed
  click: 登录 ( //*[@name="登录"] )
   ✓ execute succeed
  click: //*[@name="****"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField
   ✓ execute succeed
  val: 1****
   ✓ execute succeed
  click: //*[@name="****"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSecureTextField
   ✓ execute succeed
  val: *****
   ✓ execute succeed
  click: 登录 ( //*[@name="****"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton )
   ✓ execute succeed

这是 server 的 log

>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.41
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.41

  Error: socket hang up
      at createHangUpError (_http_client.js:253:15)
      at Socket.socketOnEnd (_http_client.js:345:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by yaniswang** [comment]
这个错是macaca报出来的，可能就要在macaca内部找原因了。
