### ISSUE TITLE
在iOS上使用UIRecorder进行录制，刷新很慢，经常刷新失败导致录制中断

### ISSUE THREAD

**Issue by ElesG** [alibaba/uirecorder#65]
1、尝试过在iOS的真机和模拟器上使用，每次进行一个操作之后的刷新都很慢，经常出现刷新不出来的情况，希望能知道原因或者解决方案，就日志上来说没有看到特别的报错，就是刷新不出啦

2、在进行首屏图片的滑动时，提示滑动失败，下面是录制过程的提示

```
 click: Don’t Allow ( //*[@name="Don’t Allow"] )
   ✓ 执行成功
  click: Don’t Allow ( //*[@name="Don’t Allow"] )
   ✓ 执行成功
  swipe: 310, 536, 9, 510, 20
   ✖ 执行失败 Not Found
```
运行相关信息：Xcode 8 ，iOS 10.2的iphone 7模拟器，运行时可以成功安装测试包并且执行操作，但执行完一两步就刷新失败

**Comment by yaniswang** [comment]
由于macaca版本更新，所以目前uirecorder的swipe函数已经无效了
这几天正在更新中，近期会发布个新版。

![image](https://cloud.githubusercontent.com/assets/970390/23498844/7708bbaa-ff64-11e6-8d4d-2023925a6a34.png)

**Comment by yaniswang** [comment]
2.4.0版本已经发布上线

**Comment by arcfree** [comment]
ios安装包 ”.ipa“，uirecorder --mobile Myios.js 回车后安装不上，又遇到过没？
