### ISSUE TITLE
在两个设备上同时跑用例失败

### ISSUE THREAD

**Issue by whitiancai** [alibaba/uirecorder#66]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:$ macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.16 [out-of-date]

* **Operate System**:win7 x64

* **Programming Language**:node

* **UIRecord Version: 2.3.31

@yaniswang 
在A设备上跑录制好的A脚本是正常的。但是一旦开始在B设备上跑B脚本，A就会报错。
>> webdriver sdk launched
>>

>>

>>   uirecorder/b2b.test : 4d00f618684d5051

>> -----------Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","udid":"4d00f618684d5051","app":"D:\\NodeProjects\\AutoMobile/apps/app-release_legu_signed_zipalign.apk"}}
INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1
uiautomator start socket server.

>> socket server ready
>> socket client ready
recive: {"cmd":"wake","args":{}}

return: {"success":true,"data":{"status":0,"value":true}}

>> -----------Recieve HTTP Request from Client: method: POST url: /wd/hub/session/2e4413be-06ee-4cbd-846a-47353005b973/elements, jsonBody: {"using":"xpath","value":"//*[@resource-id=\"cn.com.healthsource.dianpuguanli:id/et_login_phone\"]"}
recive: {"cmd":"find","args":{"strategy":"xpath","selector":"//*[@resource-id=\"cn.com.healthsource.dianpuguanli:id/et_login_phone\"]","multiple":true}}

return: {"success":true,"data":{"status":0,"value":[{"ELEMENT":"1"}]}}

>> -----------Recieve HTTP Request from Client: method: POST url: /wd/hub/session/2e4413be-06ee-4cbd-846a-47353005b973/element/1/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"1"}}

return: {"success":true,"data":{"status":0,"value":true}}

>>     √ click: ?????? ( //*[@resource-id="cn.com.healthsource.dianpuguanli:id/et_login_phone"] ) (3790ms)

>> -----------Recieve HTTP Request from Client: method: POST url: /wd/hub/session/2e4413be-06ee-4cbd-846a-47353005b973/element/1/clear, jsonBody: {}
recive: {"cmd":"clearText","args":{"elementId":"1"}}

return: {"success":true,"data":{"status":0,"value":true}}

>> -----------Recieve HTTP Request from Client: method: POST url: /wd/hub/session/2e4413be-06ee-4cbd-846a-47353005b973/element/1/value, jsonBody: {"value":["1","8","2","7","1","5","5","5","0","2","6"]}
recive: {"cmd":"setText","args":{"elementId":"1","text":"18271555026"}}

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

**Comment by yaniswang** [comment]
两个并行跑吗？

**Comment by whitiancai** [comment]
是啊，而且我指定了不同的port ，udid，和测试用例脚本

**Comment by yaniswang** [comment]
这个你要反馈给macaca，好像目前情况下是无法并行跑的吧？

**Comment by whitiancai** [comment]
上周已经反馈到macaca，还没有回应。
#[https://github.com/alibaba/macaca/issues/472](url)
