### ISSUE TITLE
执行脚本时二级iframe定位超时

### ISSUE THREAD

**Issue by magiccops** [alibaba/uirecorder#68]
iframe 里嵌套 iframe 的话，录制的时候没有问题，但是在执行 脚本的时候，定位超时。

**Comment by yaniswang** [comment]
这个需求暂时没办法满足，如果要满足，UIRecorder整体架构要进行大调整，成本太大。
多级iframe的场景目前比较少碰到。

**Comment by magiccops** [comment]
遇到这种情况，手动修改代码即可。去掉 driver.switchFrame(null) 这个动作，即不切换到主iframe即可。
