### ISSUE TITLE
windows 7 运行失败

### ISSUE THREAD

**Issue by jzhfmm** [alibaba/uirecorder#7]
录制脚本成功,但是运行到IE的时候失败
  test.spec : chrome
    √ url: http://XXXXXXXX/index.html (1816ms)
    √ waitBody:  (574ms)
    √ click: input[type="text"], 81, 25, 0 (692ms)
    √ sendKeys: 13700864141{TAB}123456
    √ click: #check, 7, 6, 0 (708ms)
    √ click: XX ( input.login, 144, 24, 0 ) (700ms)
    √ click: XXXXXX ( #side-menu li.kcb > ul.nav-second-level > li:nth-ch
ild(1) > a, 54, 14, 0 ) (711ms)
    √ click: XXXXXX ( #side-menu li.kcb > ul.nav-second-level > li:nth-child(
2) > a, 32, 16, 0 ) (700ms)
    √ click: XXXXXXX ( #side-menu li.kcb > ul.nav-second-level > li:nth-ch
ild(3) > a, 48, 15, 0 ) (691ms)
    √ click: XXXXXXX ( #side-menu ul.nav-second-level > li:nth-child(4) > a, 4
0, 13, 0 ) (685ms)

  test.spec : ie11
    1) "before all" hook

  10 passing (11s)
  1 failing

  1) test.spec : ie11 "before all" hook:
     Error: done() invoked with non-Error: The best matching driver provider org
.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance fo
r Capabilities [{ie.ensureCleanSession=true, hosts=, browserName=ie11, platform=
ANY}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'PC-20151125WOSC', ip: '192.168.56.1', os.name: 'Windows 7',
os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: driver.version: unknown
      at C:\Users\Administrator\AppData\Roaming\npm\node_modules\mocha\lib\runna
ble.js:366:21
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by yaniswang** [comment]
你本机是不是没有下载iedriver？

**Comment by yyl2016** [comment]
@jzhfmm 你好，你在chrome上是怎么执行成功的啊，我在chrome和IE上都没执行成功。
