### ISSUE TITLE
希望UI Recorder支持截图对比断言

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#70]
目前UI Recorder的断言支持判断一个值是否正确，但是不能判断界面呈现的样式是否正确，比如一个canvas里面呈现的图形是否正确。希望能够支持对某个元素截图与基准图片对比的断言。

**Comment by yaniswang** [comment]
这个功能正在评估中，近期可能会开始开发。

**Comment by xudafeng** [comment]
@yaniswang opencv集成一个吧

**Comment by hufyhang** [comment]
确实如果有截图对比功能的话就方便太多了。

**Comment by yaniswang** [comment]
v2.5.10已经支持了图片对比，大家可以试用一下。

**Comment by stevobm** [comment]
好的
