### ISSUE TITLE
Recorder delayed and sluggish

### ISSUE THREAD

**Issue by gianbasagre** [alibaba/uirecorder#71]
First of all, thank you for this amazing tool. It's perfect for web app testing. 

However, for mobile app (cordova), the recorder is sluggish and sometimes does not reflect what's happening in the simulator. The input text also does not send the keys and the simulator is not updated.

Are there any settings that I can tweak to improve performance?

**Comment by yaniswang** [comment]
Show your error screen shot here.

**Comment by yaniswang** [comment]
Mobile recorder is powered by macaca: http://macacajs.com/

The speed of recorder is depend macaca.
