### ISSUE TITLE
希望增加 一个参数 --reuse

### ISSUE THREAD

**Issue by mengde0077** [alibaba/uirecorder#72]
如果 不带 --reuse 参数： 就默认 安装app

如果带上 --reuse 参数： 就不安装 app 和WebDriver 等 ，直接进行录制；

因为 很多时候录制是断断续续的进行，这个时候app 和 WebDriver 等是之前已经装好了的！

感谢！

**Comment by yaniswang** [comment]
安装过程很快的，这个感觉意义不是非常大
wda也只在第一次的时候安装，如果已经安装好了，并不会重新安装的。
只有app才会每次都安装。

**Comment by yaniswang** [comment]
考虑到增加参数会增加软件使用复杂度，并且这个方案对性能的提升并不会太大，这个问题关闭掉了
