### ISSUE TITLE
mac os 上按住cmd来对hover进行expect设置的功能不管用

### ISSUE THREAD

**Issue by hufyhang** [alibaba/uirecorder#73]
Chrome version:  57.0.2987.133 (64-bit)
Mac OS: 10.10.5

文档中提到的 [How to add expect after hover?](https://github.com/alibaba/uirecorder#how-to-add-expect-after-hover) 的方式貌似不管用。不知是否是bug？

**Comment by hufyhang** [comment]
是的，了解了。谢谢。

另外，请问这里拦截的只是hover事件吗？如果是mouseover之类的事件可否进行拦截呢？

**Comment by yaniswang** [comment]
所有的js事件都冻结了，都不会触发了

**Comment by hufyhang** [comment]
谢谢
