### ISSUE TITLE
ui recorder录制iOS时提示“BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.”

### ISSUE THREAD

**Issue by wynanwong** [alibaba/uirecorder#74]
在用ui recorder录制iOS真机时，提示“BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.”，下面是相关的log:

log:
>> index.js:17:12 [master] pid:5571 webdriver server start with config:
 { port: '4444',
  verbose: true,
  always: true,
  ip: '172.16.10.155',
  host: 'wndeMacBook-Pro.local',
  loaded_time: '2017-04-05 17:47:56' }
>> middlewares.js:17:10 [master] pid:5571 base middlewares attached
>> router.js:127:10 [master] pid:5571 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:5571 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","app":"/Users/wn/abc/***.app","udid":"******"}}
>> session.js:47:10 [master] pid:5571 Creating session, sessionId: 24aeac55-b583-4f37-9661-cb2d14a1ad19.
/usr/local/lib/node_modules/macaca-ios/node_modules/.0.1.4@ios-device/node_modules/ios-deploy/build/Release/ios-deploy
>> helper.js:208:12 [master] pid:5571 Using local app form /Users/wn/abc/***.app
CFBundleIdentifier is ***
Get bundleId *** from plist /Users/wn/abc/****.app/Info.plist
>> macaca-ios.js:260:12 [master] pid:5571 App '***' is not installed.
>> macaca-ios.js:263:14 [master] pid:5571 Install app '***' successfully.
>> xctest-client.js:56:14 [master] pid:5571 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.4@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:150:10 [master] pid:5571 {
	"bundleId": "***",
	"platformName": "iOS"
}
>> macaca-ios.js:154:12 [master] pid:5571 Trying to start wda server...
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:5571 xcode version: 8.1
>> WebDriverAgent version: 1.1.4
>> xctest-client.js:170:14 [master] pid:5571 2017-04-05 17:51:25.754 xcodebuild[5660:137591]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/wn/Library/Developer/Xcode/DerivedData/WebDriverAgent-fsyaqpbwtgjbaobuayxfxxuyljhi/Logs/Test/919FBF51-7B9F-4012-A033-51B76885E9B1/Session-WebDriverAgentRunner-2017-04-05_175125-6o0hR7.log
2017-04-05 17:51:25.754 xcodebuild[5660:137585] [MT] IDETestOperationsObserverDebug: (32C5E624-C861-426F-ADAE-EBF1DB06E583) Beginning test session WebDriverAgentRunner-32C5E624-C861-426F-ADAE-EBF1DB06E583 at 2017-04-05 17:51:25.752 with Xcode 8B62 on target <DVTiOSDevice: 0x7f8234fe9150> {
		deviceSerialNumber:         CCQJKPL2F4JR
		identifier:                 538708cb569deea3f08c60d67c725cf961b554b3
		deviceClass:                iPod
		deviceName:                 iPod
		deviceIdentifier:           538708cb569deea3f08c60d67c725cf961b554b3
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         armv7f
		deviceTotalCapacity:        29255798784
		deviceAvailableCapacity:    20326039552
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f8234fe9480 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:171:14 [master] pid:5571 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.4@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:5571 2017-04-05 17:51:30.741 xcodebuild[5660:137585] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/wn/Library/Developer/Xcode/DerivedData/WebDriverAgent-fsyaqpbwtgjbaobuayxfxxuyljhi/Logs/Test/919FBF51-7B9F-4012-A033-51B76885E9B1/Session-WebDriverAgentRunner-2017-04-05_175125-6o0hR7.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/wn/Library/Developer/Xcode/DerivedData/WebDriverAgent-fsyaqpbwtgjbaobuayxfxxuyljhi/Logs/Test/919FBF51-7B9F-4012-A033-51B76885E9B1/Session-WebDriverAgentRunner-2017-04-05_175125-6o0hR7.log}

>> xctest-client.js:171:14 [master] pid:5571 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.4@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:5571 
Testing failed:

>> xctest-client.js:171:14 [master] pid:5571 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.4@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:5571 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:171:14 [master] pid:5571 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.4@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:265:14 [master] pid:5571 killing deviceLogProc pid: 5657
>> xctest-client.js:270:14 [master] pid:5571 killing runnerProc pid: 5660
>> xctest-client.js:276:14 [master] pid:5571 killing iproxyProc pid: 5659
>> xctest-client.js:181:14 [master] pid:5571 xctest client exit with code: 65, signal: null
>> xctest-client.js:209:14 [master] pid:5571 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:5571 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:257:14 [master] pid:5571 Fail to start xctest: undefined
>> macaca-ios.js:154:12 [master] pid:5571 Trying to start wda server...
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.

**Comment by yaniswang** [comment]
你的macaca已经安装最新版了吗？

**Comment by wynanwong** [comment]
已经是最新版1.2.0

**Comment by yaniswang** [comment]
最新macaca 2.0应该已经修复这些问题了，最底层驱动全新自己实现了
