### ISSUE TITLE
运行之前录制的脚本报cannot get automation错误，新录制脚本则没问题

### ISSUE THREAD

**Issue by ljw1811** [alibaba/uirecorder#75]
提示的错误如下：

2) sample/1024_768/base/login.spec : chrome "after all" hook:
     Error: the string "unknown error: cannot get automation extension\nfrom unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html\n  (Session info: chrome=57.0.2987.133)\n  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 10.09 seconds\nBuild info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'\nSystem info: host: 'MacBook-Pro.local', ip: '192.168.1.193', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_45'\nDriver info: org.openqa.selenium.chrome.ChromeDriver\nCapabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=/var/folders/32/db3l7fx91hv2xrtytcmjz2vm0000gn/T/.org.chromium.Chromium.pfbeDk}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.133, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]\nSession ID: cbb2c4d48c04394f484bcab8edc267e9" was thrown, throw an Error :)

查找后发现安装的chromedriver为2.27版本，升级到2.28以上版本则问题解决。

**Comment by yaniswang** [comment]
之前旧的selenium-standalone版本不支持chrome 57，升级新版就可以了

`"selenium-standalone": "6.1.0"`
