### ISSUE TITLE
运行多个测试时，报错，这个是什么原因

### ISSUE THREAD

**Issue by llxiao** [alibaba/uirecorder#8]
D:\project\uirecord\test\tool.spec.js:159
    browsers = browsers.replace(/^\s+|\s+$/g, '');
                       ^

TypeError: Cannot read property 'replace' of undefined
    at runThisSpec (D:\project\uirecord\test\tool.spec.js:159:24)
    at Object.<anonymous> (D:\project\uirecord\test\tool.spec.js:143:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\lxiao\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\lxiao\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\lxiao\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:485:10)
    at Object.<anonymous> (C:\Users\lxiao\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by yaniswang** [comment]
你写的浏览器列表有问题吧
把你的config.json内容发出来看下

**Comment by llxiao** [comment]
{
    "webdriver": {
        "host": "localhost",
        "port": "4444",
        "browsers": "firefox,chrome"
    },
    "vars": {}
}

**Comment by llxiao** [comment]
单个测试运行时是正常的，新录制后，运行就出现这个错误了

**Comment by yaniswang** [comment]
是不是你的用例不是最新v1.0.0录制的？
之前旧版录的脚本是有问题。

**Comment by llxiao** [comment]
D:\project\uirecord\test>uirecorder  -V
1.0.0

**Comment by yaniswang** [comment]
tool.spec.js代码发出来看下

**Comment by llxiao** [comment]
var expect  = require('expect.js');
var faker  = require('faker');

module.exports = function(browser, testVars){

    before(function(){
        browser = browser || this.browser;
        testVars = testVars || this.testVars;
    });

    callSpec('test.spec.js');

    it('mouseUp: #mianContentDiv, 198, 239, 0', function*(){
        var element = yield browser.sleep(300).wait('#mianContentDiv', 30000);
        yield browser.sleep(300).mouseMove(element, 198, 239).mouseUp(0);
    });
    
    it('click: #mianContentDiv, 198, 239, 0', function*(){
        var element = yield browser.sleep(300).wait('#mianContentDiv', 30000);
        yield browser.sleep(300).mouseMove(element, 198, 239).click(0);
    });
    
    it('mouseMove: 工具 ( #nav-bar ul.list-inline > li:nth-child(5) > a:nth-child(1) )', function*(){
        var element = yield browser.sleep(300).wait('#nav-bar ul.list-inline > li:nth-child(5) > a:nth-child(1)', 30000);
        yield browser.sleep(300).mouseMove(element);
    });
    
    it('click: 离心机对中快手 ( #nav-bar li:nth-child(5) > ul.menu-detail > li:nth-child(5) > a, 44.78125, 9.515625, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#nav-bar li:nth-child(5) > ul.menu-detail > li:nth-child(5) > a', 30000);
        yield browser.sleep(300).mouseMove(element, 44.78125, 9.515625).click(0);
    });
    
    it('waitBody: ', function*(){
        yield browser.sleep(500).wait('body', 30000);
    });
    
    it('scrollTo: 0, 700', function*(){
        yield browser.scrollTo(0, 700);
    });
    
    it('scrollTo: 0, 791', function*(){
        yield browser.scrollTo(0, 791);
    });
    
    it('mouseDown: R1* ( #step2R1, 56.84375, 12.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2R1', 30000);
        yield browser.sleep(300).mouseMove(element, 56.84375, 12.234375).mouseDown(0);
    });
    
    it('mouseUp: R1* ( #step2R1, 111, 17, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2R1', 30000);
        yield browser.sleep(300).mouseMove(element, 111, 17).mouseUp(0);
    });
    
    it('sendKeys: 2', function*(){
        yield browser.sendKeys('2');
    });
    
    it('mouseDown: B1* ( #step2B1, 31.84375, 16.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2B1', 30000);
        yield browser.sleep(300).mouseMove(element, 31.84375, 16.234375).mouseDown(0);
    });
    
    it('mouseUp: B1* ( #step2B1, 111, 17, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2B1', 30000);
        yield browser.sleep(300).mouseMove(element, 111, 17).mouseUp(0);
    });
    
    it('sendKeys: 3', function*(){
        yield browser.sendKeys('3');
    });
    
    it('mouseDown: L1* ( #step2L1, 53.84375, 26.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2L1', 30000);
        yield browser.sleep(300).mouseMove(element, 53.84375, 26.234375).mouseDown(0);
    });
    
    it('mouseUp: L1* ( #step2L1, 111, 17, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2L1', 30000);
        yield browser.sleep(300).mouseMove(element, 111, 17).mouseUp(0);
    });
    
    it('sendKeys: 4', function*(){
        yield browser.sendKeys('4');
    });
    
    it('mouseDown: R2* ( #step2R2, 67.84375, 20.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2R2', 30000);
        yield browser.sleep(300).mouseMove(element, 67.84375, 20.234375).mouseDown(0);
    });
    
    it('mouseUp: R2* ( #step2R2, 111, 17, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2R2', 30000);
        yield browser.sleep(300).mouseMove(element, 111, 17).mouseUp(0);
    });
    
    it('sendKeys: 5', function*(){
        yield browser.sendKeys('5');
    });
    
    it('mouseDown: B2* ( #step2B2, 70.84375, 14.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2B2', 30000);
        yield browser.sleep(300).mouseMove(element, 70.84375, 14.234375).mouseDown(0);
    });
    
    it('mouseUp: B2* ( #step2B2, 111, 17, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2B2', 30000);
        yield browser.sleep(300).mouseMove(element, 111, 17).mouseUp(0);
    });
    
    it('sendKeys: 6', function*(){
        yield browser.sendKeys('6');
    });
    
    it('mouseDown: L2* ( #step2L2, 46.84375, 23.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2L2', 30000);
        yield browser.sleep(300).mouseMove(element, 46.84375, 23.234375).mouseDown(0);
    });
    
    it('mouseUp: L2* ( #step2L2, 111, 17, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#step2L2', 30000);
        yield browser.sleep(300).mouseMove(element, 111, 17).mouseUp(0);
    });
    
    it('sendKeys: 7', function*(){
        yield browser.sendKeys('7');
    });
    
    it('click: 查看检测结果 ( #installedDebugging button, 66.171875, 19.234375, 0 )', function*(){
        var element = yield browser.sleep(300).wait('#installedDebugging button', 30000);
        yield browser.sleep(300).mouseMove(element, 66.171875, 19.234375).click(0);
    });
    
    it('expect: text, ["#advance-search-form div > div:nth-child(1) > h4:nth-child(1) > strong"], equal, 垂直方向结果：不合格', function*(){
        var element = yield browser.sleep(300).wait('#advance-search-form div > div:nth-child(1) > h4:nth-child(1) > strong', 30000);
        var value = yield element.text();
        expect(value).to.equal('垂直方向结果：不合格');
    });
    
};

if(module.parent && /mocha\.js/.test(module.parent.id)){
    runThisSpec();
}

function runThisSpec(){
    var JWebDriver = require('jwebdriver');
    require('mocha-generators').install();
    var fs = require('fs');
    var path = require('path');

    // read config
    var config = require('./config.json');
    var webdriverConfig = config.webdriver;
    var host = webdriverConfig.host;
    var port = webdriverConfig.port || 4444;
    var testVars = config.vars;
    var browsers = webdriverConfig.browsers;
    browsers = browsers.replace(/^\s+|\s+$/g, '');
    delete webdriverConfig['host'];
    delete webdriverConfig['port'];
    delete webdriverConfig['browsers'];

    // read hosts
    var hostsPath = './hosts';
    var hosts = '';
    if(fs.existsSync(hostsPath)){
        hosts = fs.readFileSync(hostsPath).toString();
    }

    var specFilename = path.basename(__filename);

    browsers.split(/\s*,\s*/).forEach(function(browserName){
        var caseName = specFilename.replace(/\.js$/,'') + ' : ' + browserName;

        var browserInfo = browserName.split(' ');
        browserName = browserInfo[0];
        var browserVersion = browserInfo[1];

        describe(caseName, function(){

            this.timeout(600000);

            var browser;
            before(function*(){
                var driver = new JWebDriver({
                    'host': host,
                    'port': port
                });
                var sessionConfig = Object.assign({}, webdriverConfig, {
                    'hosts': hosts,
                    'browserName': browserName,
                    'version': browserVersion,
                    'ie.ensureCleanSession': true
                });
                browser = yield driver.session(sessionConfig);
                yield browser.maximize();
                this.browser = browser;
                this.testVars = testVars;
            });

            module.exports();

            after(function*(){
                if(browser){
                    if(fs.existsSync('screenshots')){
                        var png_base64  = yield browser.getScreenshot();
                        var pngFileName = 'screenshots/' + caseName.replace(/ : /,'_') + '.png';
                        fs.writeFileSync(pngFileName, png_base64, 'base64');
                    }
                    yield browser.close();
                }
            });

        });
    });
}

function callSpec(name){
    try{
        require('./'+name)();
    }
    catch(e){
        console.log(e)
        process.exit(1);
    }
}

**Comment by yaniswang** [comment]
你的nodejs是什么版本？

**Comment by llxiao** [comment]
4.4.4

**Comment by yaniswang** [comment]
browsers = browsers.replace(/^\s+|\s+$/g, '');

是这一行出问题了，但是从你的config.json来看，又是正常的。

是不是你不是在config.json当前路径执行的？

**Comment by llxiao** [comment]
嗯 现在的目录结构是.\uirecorder\test\config.json
然后在test路径下执行macha test\*.spec.js

**Comment by yaniswang** [comment]
把这两个文件打个压缩包，上传一下

**Comment by llxiao** [comment]
上传一直出错，上传百度云了
http://pan.baidu.com/s/1qY1WJaG

**Comment by yaniswang** [comment]
v1.0.1版本已经修复了这个问题

问题出在这3行代码，删除了就可以了：

    delete webdriverConfig['host'];
    delete webdriverConfig['port'];
    delete webdriverConfig['browsers'];

**Comment by llxiao** [comment]
OK 辛苦
