### ISSUE TITLE
录制时Chrome打开异常

### ISSUE THREAD

**Issue by gungnir17** [alibaba/uirecorder#82]
使用uirecorder录制，打开Chrome时异常如下图
![12](https://cloud.githubusercontent.com/assets/28223953/25565153/e016ff94-2df4-11e7-8187-6290d13a4d69.png)
然后Chrome打开失败！
unknown error: failed to wait for extension background page to load: chrome-exte
nsion://njkfhfdkecbpjlnfmminhmdcakopmcnc/_generated_background_page.html
from chrome not reachable
  (Driver info: chromedriver=2.11.298604 (75ea2fdb5c87f133a8e1b8da16f6091fb7d532
1e),platform=Windows NT 6.1 SP1 x86_64)
环境：
操作系统：WIN7-64
Chrome版本 v36.0.1985.125，
chromedriver版本v2.11

**Comment by yaniswang** [comment]
你的uirecorder版本太旧了，使用的chromedriver竟然还是2.11版本的，先更新到最新版本

**Comment by gungnir17** [comment]
uirecorder最新版的Chromedriver版本是2.28，这版只支持Chrome的v55-57，而Chrome的58~60也都出来了，建议Chromedriver版本能自行选择，才能兼容更多的Chrome版本。

**Comment by yaniswang** [comment]
好的，下个版本我们会将版本改为.x版本，这样小版本就会自动升级
