### ISSUE TITLE
建议变量支持数值运算

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#83]
UI Recorder提供了变量功能，可以将界面上的元素的值保存起来，值得一赞。但是我目前遇到一种测试场景，需要将几个变量进行数值运算后对比，好像目前找不到方法可以解决。
比如从界面取值{{a}}=1,{{b}}=2,然后对元素c进行取值并添加断言：{{a}}+{{b}}，希望对比c==a+b，但结果发现UI Recorder是将a和b进行字符串拼接，请问有办法能够支持变量相加等数值运算操作么？

**Comment by yaniswang** [comment]
目前我们也支持js的模板字符串，比如可以这么写：`{$testVar.a+testVars.b}`

**Comment by yaniswang** [comment]
详细参考：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by stevobm** [comment]
模板字符串我之前也尝试过，但是没有成功。我在页面上取了某个元素值定义了变量a，但是在断言中使用${a}的时候却出现“ReferenceError: a is not defined”的提示，好像无法使用。请问是由于版本的问题么？我现在用是2.4.6版。

**Comment by yaniswang** [comment]
不是${a}，而是${testVars.a}

**Comment by stevobm** [comment]
嗯，我刚试了一下，确实可以！但由于之前取的变量值是字符串，所以还需要先分别进行转换，类似于这样：${parseInt(testVars.a)+parseInt(testVars.b)}——OK啦O(∩_∩)O~
不过这样既有testVars又有parseInt，不知道我们的测试妹纸学不学得来哦，后面有没有更加易用的改进方案呢？

**Comment by yaniswang** [comment]
嗯，使用起来的确有点复杂。

不过要转换成数值型，感觉没别的解决办法。
因为从页面中抓过来的肯定是字符串格式的，要进行数值计算，那只能这样了。

我可以把这段写进文档中。

**Comment by stevobm** [comment]
数值转换其实也有好的办法。比如在页面取值的时候(我指的是选择val和text的时候)，如果探测取到的内容为数字，可以呈现一个“当作数值”的勾选框，这样当断言的时候就可以参照这个标记，支持相应的数值运算了。O(∩_∩)O~

**Comment by yaniswang** [comment]
你这个方法可以！很赞！

**Comment by bingxueDU** [comment]
我也遇到一样的问题，但是使用模板字符串是报错的。
后来在相加前使用parseInt先将字符串转换 再去相加就可以了

ps:
testVars.a = parseInt(testVars.a]);
testVars['汇总'] = (testVars.a + testVars.b)
