### ISSUE TITLE
希望支持基于元素内容的定位和定位属性编辑

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#85]
目前的UI Recorder在做页面元素定位的时候，默认是按照元素的相关属性和次序来定位的。但是有时我们需要动态添加一个元素，比如在列表中添加一个名称为testA的列表项，然后希望能够对testA进行点击等后续操作时，好像没有比较好的方法。如果UI Recorder能够**支持按照元素的内容进行定位**，那么这个问题应该就能够迎刃而解。

另外，UI Recorder提供了一系列的自定义属性来辅助元素定位（比如data-id等等），这个设计很不错。不过如果进一步，把原生属性（如id、class）和自定义属性区分开，让用户可以**编辑自定义属性**（像tag一样增删），这样定位机制就可以轻松适配任何网站，达到一个近乎完美的效果了。

**Comment by yaniswang** [comment]
问题1，的确是个很好的建议，我们可以在工具面板上增加个开关。

问题2这个目前本来就是可以编辑的，uirecorder init的时候，就可以修改这些扩展属性。

**Comment by stevobm** [comment]
嗯，问题2其实从用户体验角度出发，最好**在界面上提供自定义属性的编辑**，因为很多自定义标签是到了具体测试的时候才发现的，这个时候再通过uirecorder init改已经不太好改了，所以可以考虑一下。O(∩_∩)O~

**Comment by yaniswang** [comment]
行，问题2也会加入到待开发列表。

**Comment by yaniswang** [comment]
问题1目前已经实现了文本定位功能，对于控件内部单一文本的场景，会用文本进行直接定位。

文本定位功能可以在录制面板上进行临时关闭。

问题2考虑到变更场景不是非常频繁，因此暂时不考虑了，还是继续在uirecorder init里进行编辑。

**Comment by stevobm** [comment]
我看了一下根据文本定位目前的实现，但是发现无法满足当前的测试场景。

试想这样一个场景，我们首先在界面上添加一个用户，列表中多出刚刚添加的用户名，然后我们再点击包含刚刚添加的那个用户名的列表项，对该用户进行进一步操作。这个时候我们当然是希望在点击列表项的时候能够根据该列表项所包含的文本来进行匹配（即便是该列表项可能还包含其他元素的情况下），而其他的操作其实则没有必要根据文本来定位了。

目前定位取文本是按规则自动取的，但是有些想按照文本匹配的地方又不符合规则，导致定位不到。希望还是能够做成开关，让用户根据需要选择。

**Comment by yaniswang** [comment]
text在录制界面上有开关的

**Comment by stevobm** [comment]
找到了，跟其他属性开关在一起，不说还没注意。(～￣▽￣)～
