### ISSUE TITLE
Andriod录制后回放运行报错

### ISSUE THREAD

**Issue by melissalu** [alibaba/uirecorder#87]
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/melissalu/Documents/workspace/UIAutoTest/node_modules/_mocha@3.1.2@mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/melissalu/Documents/workspace/UIAutoTest/node_modules/_mocha@3.1.2@mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/melissalu/Documents/workspace/UIAutoTest/node_modules/_mocha@3.1.2@mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/melissalu/Documents/workspace/UIAutoTest/node_modules/_mocha@3.1.2@mocha/bin/_mocha:458:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter mochawesome-uirecorder "sample/test.spec.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder "sample/test.spec.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/melissalu/.npm/_logs/2017-05-08T07_20_22_747Z-debug.log

**Comment by yaniswang** [comment]
能把你的代码也贴出来吗？

**Comment by yaniswang** [comment]
你的nodejs版本多少？

**Comment by melissalu** [comment]
v7.2.0
![image](https://cloud.githubusercontent.com/assets/13230344/25987381/55bedda4-3726-11e7-8d90-c8bdb32d5a50.png)
var fs = require('fs');
var path = require('path');
var cp = require('child_process');
var chai = require("chai");
var should = chai.should();
var JWebDriver = require('jwebdriver');
chai.use(JWebDriver.chaiSupportChainPromise);

var rootPath = getRootPath();
var appPath = '/Users/melissalu/Documents/workspace/systest/UIAutoTest/weread_android_1.5.6.1017.apk';
var platformName = 'Android';

module.exports = function(){

    var driver, testVars;

    before(function(){
        var self = this;
        driver = self.driver;
        testVars = self.testVars;
    });

    it('tap: 微 信 登 录 ( //*[@resource-id="com.tencent.weread:id/st"] )', async function(){
        await driver.wait('//*[@resource-id="com.tencent.weread:id/st"]', 30000).sendElementActions('tap');
    });

    function _(str){
        if(typeof str === 'string'){
            return str.replace(/\{\{(.+?)\}\}/g, function(all, key){
                return testVars[key] || '';
            });
        }
        else{
            return str;
        }
    }

};

if(module.parent && /mocha\.js/.test(module.parent.id)){
    runThisSpec();
}

function runThisSpec(){
    // read config
    var config = require(rootPath + '/config.json');
    var webdriverConfig = Object.assign({},config.webdriver);
    var host = webdriverConfig.host;
    var port = webdriverConfig.port || 4444;
    var testVars = config.vars;

    var screenshotPath = rootPath + '/screenshots';
    var doScreenshot = fs.existsSync(screenshotPath);

    var specName = path.relative(rootPath, __filename).replace(/\\/g,'/').replace(/\.js$/,'');

    var arrDeviceList = getEnvList() || getDeviceList(platformName);
    if(arrDeviceList.length ===0 ){
        console.log('Search mobile device failed!');
        process.exit(1);
    }

    arrDeviceList.forEach(function(device){
        var caseName = specName + ' : ' + (device.name?device.name+' ['+device.udid+']':device.udid);

        if(doScreenshot){
            mkdirs(path.dirname(screenshotPath + '/' + caseName));
        }

        describe(caseName, function(){

            var stepId = 1;

            this.timeout(600000);
            this.slow(1000);

            before(function(){
                var self = this;
                var driver = new JWebDriver({
                    'host': host,
                    'port': port
                });
                self.driver = driver.session({
                    'platformName': platformName,
                    'udid': device.udid,
                    'app': /^(\/|[a-z]:\\|https?:\/\/)/i.test(appPath) ? appPath : rootPath + '/' + appPath
                });
                self.testVars = testVars;
                return self.driver;
            });

            module.exports();

            afterEach(function(){
                if(doScreenshot){
                    var filepath = screenshotPath + '/' + caseName.replace(/[^\/]+$/, function(all){
                        return all.replace(/\s*[:\.\:\-\s]\s*/g, '_');
                    }) + '_' + (stepId++) + '.png';
                    return this.driver.getScreenshot(filepath).catch(function(){});
                }
            });

            after(function(){
                return this.driver.close();
            });

        });
    });
}

function getRootPath(){
    var rootPath = path.resolve(__dirname);
    while(rootPath){
        if(fs.existsSync(rootPath + '/config.json')){
            break;
        }
        rootPath = rootPath.substring(0, rootPath.lastIndexOf(path.sep));
    }
    return rootPath;
}

function mkdirs(dirname){
    if(fs.existsSync(dirname)){
        return true;
    }else{
        if(mkdirs(path.dirname(dirname))){
            fs.mkdirSync(dirname);
            return true;
        }
    }
}

function callSpec(name){
    try{
        require(rootPath + '/' + name)();
    }
    catch(e){
        console.log(e)
        process.exit(1);
    }
}

function getEnvList(){
    var strEnvList = process.env.devices;
    if(strEnvList){
        return strEnvList.split(/\s*,\s*/).map(function(udid){
            return {udid: udid};
        });
    }
}

function getDeviceList(platformName){
    var arrDeviceList = [];
    var strText, match;
    if(platformName === 'Android')
    {
        // for android
        strText = cp.execSync('adb devices').toString();
        strText.replace(/(.+?)\s+device\r?\n/g, function(all, deviceName){
            arrDeviceList.push({
                udid: deviceName
            });
        });
    }
    else{
        // ios real device
        strText = cp.execSync('idevice_id -l').toString();
        strText.replace(/(.+)\r?\n/g, function(all, udid){
            var deviceName = cp.execSync('idevice_id -d '+udid).toString();
            deviceName = deviceName.replace(/\r?\n/g, '');
            arrDeviceList.push({
                name: deviceName,
                udid: udid
            });
        });
        // ios simulator
        strText = cp.execSync('xcrun simctl list devices').toString();
        strText.replace(/\r?\n\s*(.+?)\s+\((.+?)\) \(Booted\)/g, function(all, deviceName, udid){
            arrDeviceList.push({
                name: deviceName,
                udid: udid
            });
        });
    }
    return arrDeviceList;
}

**Comment by melissalu** [comment]
node版本是v7.2.0

代码我也贴上去了，我只录制了微信登录这一个控件而已

**Comment by yaniswang** [comment]
你装个最新版node v7.10.0试试

**Comment by melissalu** [comment]
我也试过录别的控件也报一样的错误

**Comment by FarAwaytarget** [comment]
我是node v7.110.0，和他同样的报错，录制没问题回放就不行了

**Comment by yaniswang** [comment]
从报错信息来看，肯定是es7 async语法不支持引起的。

原则上来讲，node v7.x应该都是支持es7 async语法的啊。

**Comment by yaniswang** [comment]
上面的代码在我机器上跑了下，可以跑的。
说明肯定是node版本的问题。

**Comment by FarAwaytarget** [comment]
抱歉作者，可能是我没看仔细，我的错误和他的有点差别
    
[mochawesome] Generating report files...



  sample/test.spec : emulator-5554
    1) "before all" hook
    2) "after all" hook


  0 passing (42ms)
  2 failing

  1) sample/test.spec : emulator-5554 "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:9765
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

  2) sample/test.spec : emulator-5554 "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:9765
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)




[mochawesome] Report saved to reports/index.html
[mochawesome] Report saved to reports/index.xml


(node:12222) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:12222) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:12222) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "singletest" "sample/test.spec.js"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "sample/test.spec.js"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter mochawesome-uirecorder "sample/test.spec.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder "sample/test.spec.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Wzd/.npm/_logs/2017-05-24T06_09_50_095Z-debug.log

**Comment by yaniswang** [comment]
你看下config.json里，为啥要把端口号配置成9765？

**Comment by FarAwaytarget** [comment]
自动的配置的端口，我改过来之后好了～～谢谢大大，我以为这个webdriver的端口和手机开启的端口不一样呢。。谢谢

**Comment by bingxueDU** [comment]
[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml


(node:9992) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
(node:9992) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
(node:9992) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecord
er "sample/test.spec.js"`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\uc\AppData\Roaming\npm-cache\_logs\2017-08-10T09_05_06_214
Z-debug.log

**Comment by bingxueDU** [comment]
> mocha --reporter mochawesome-uirecorder "sample/test.spec.js"

[mochawesome] Generating report files...



  sample/test.spec : chrome
    1) "before all" hook
    2) "after all" hook

  sample/test.spec : ie 11
    3) "before all" hook
    4) "after all" hook


  0 passing (2s)
  4 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

  2) sample/test.spec : chrome "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

  3) sample/test.spec : ie 11 "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

  4) sample/test.spec : ie 11 "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)




[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml


(node:9992) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
(node:9992) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
(node:9992) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecord
er "sample/test.spec.js"`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\uc\AppData\Roaming\npm-cache\_logs\2017-08-10T09_05_06_214
Z-debug.log

**Comment by yaniswang** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:4444`

你的webdriver server没有开
