### ISSUE TITLE
除IE外的其他浏览器都打开失败

### ISSUE THREAD

**Issue by dogignorebaozi** [alibaba/uirecorder#88]
![image](https://cloud.githubusercontent.com/assets/26223125/25805800/916614a8-3433-11e7-84af-daf6d50694d2.png)

**Comment by dogignorebaozi** [comment]
请问浏览器的安装位置是否有要求，
chrome的位置是C:\Program Files (x86)\Google\Chrome\Application

**Comment by yaniswang** [comment]
你的chromedriver版本2.27不支持当前的chrome版本号，升级一下就行了。

**Comment by dogignorebaozi** [comment]
我升级到2.29chrome可以打开了，但是360se还是不行

**Comment by dogignorebaozi** [comment]
![image](https://cloud.githubusercontent.com/assets/26223125/25806871/5c7c910a-3437-11e7-8eab-fdbc50233134.png)

**Comment by dogignorebaozi** [comment]
看起来好像也是版本不支持，那么我得安装这个chromedriver支持的其他浏览器是吗？

**Comment by yaniswang** [comment]
你要根据浏览器的chrome内核来选择合适的chromedriver版本，360的内核是比较古老的。

**Comment by zhangjianpinghik** [comment]
@dogignorebaozi  怎么升级chromedriver? 你问题解决了吗? 我遇到了和你一样的问题
