### ISSUE TITLE
windows 10下，测试用百度搜索一个关键字，录制成功，run.bat sample/test.spec.js报错

### ISSUE THREAD

**Issue by philoyang** [alibaba/uirecorder#89]
nodejs： v7.10.0,
uirecorder: 最新版本

![uirecorder issue](https://cloud.githubusercontent.com/assets/1846805/25841693/b59fc314-34d3-11e7-9185-f47013c5d925.png)

**Comment by yaniswang** [comment]
关键错误信息：ECONNREFUSED 127.0.0.1:4444

你的webdriver server没有启动起来。
