### ISSUE TITLE
你好，是否支持火狐ie浏览器

### ISSUE THREAD

**Issue by 317482454** [alibaba/uirecorder#90]
在使用过程中发现ie直接卡死，火狐没有反应，是不是需要额外设置什么？
ie已关闭安全性

**Comment by yaniswang** [comment]
chrome,firefox,ie都支持的。
具体哪些浏览器如何配置，网上可以自行搜索下webdriver相关的配置教程。

UIRecorder只是用来生成普通的webdriver脚本，只要是webdriver支持的浏览器，我们都支持。

**Comment by 317482454** [comment]
好的
