### ISSUE TITLE
macaca-android@2.0.2 之后，录制和回放都出了问题--求解

### ISSUE THREAD

**Issue by mengde0077** [alibaba/uirecorder#92]
前提：
已经正确安装了 macaca-android@2.0.2 
已经可以正常使用 app-inspector
使用macaca doctor 检查已经没有异常！

1.录制
不能像以前那样录制xpath，现在录制出来的都是 坐标！
输入中文会报错！

如：

tap: 653, 128
   ✓ 执行成功
  sendKeys: 瓜子
   ✖ 执行失败 An unknown server-side error occurred while processing the command.
macaca server 运行日志：

>> responseHandler.js:11:12 [master] pid:2384 Recieve HTTP Request from Client[2017-05-12 09:50:22]: method: POST url: /wd/hub/session/eb7e9122-ca9f-4609-b254-e0a63e7ea136/keys, jsonBody: {"value":["瓜","子"]}
>> proxy.js:54:14 [master] pid:2384 Proxy: /wd/hub/session/eb7e9122-ca9f-4609-b254-e0a63e7ea136/keys:POST to http://127.0.0.1:9001/wd/hub/session/eb7e9122-ca9f-4609-b254-e0a63e7ea136/keys:POST with body: {"value":["瓜","子"]}
>> proxy.js:82:20 [master] pid:2384 Got response with status 200: {"status":13,"value":"An unknown server-side error occurred while processing the command.","sessionId":"eb7e9122-ca9f-4609-b254-e0a63e7ea136"}
>> session.js:107:14 [master] pid:2384 Send HTTP Respone to Client[2017-05-12 09:50:22]: {"status":13,"value":"\"An unknown server-side error occurred while processing the command.\"","sessionId":"eb7e9122-ca9f-4609-b254-e0a63e7ea136"}
>> responseHandler.js:11:12 [master] pid:2384 Recieve HTTP Request from Client[2017-05-12 09:50:22]: method: GET url: /wd/hub/session/eb7e9122-ca9f-4609-b254-e0a63e7ea136/screenshot, jsonBody: {}
2.回放
以前使用xpath定位的用例全部报错！

1) commons/commons : f4301fe8 场景合集：基础功能页面遍历 场景集：登录前 场景：定位地址切换 点击: 首页:
     Error: the string "Wait elelment displayed timeout: //*[@text=\"首页\"] ,10000ms" was thrown, throw an Error :)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by yaniswang** [comment]
你的uirecorder什么版本？node什么版本？

**Comment by mengde0077** [comment]
被测 app 没有变！

$ macaca doctor

  macaca-doctor version: 1.1.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.5

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/caolinming/tools/sdk`
  Platforms is set to `/Users/caolinming/tools/sdk/platforms/android-25`
  Android tools is set to `/Users/caolinming/tools/sdk/tools/android`
  ADB tool is set to `/Users/caolinming/tools/sdk/platform-tools/adb`
  Gradle 3.5 is installed at: `/opt/gradle/gradle-3.5/bin/gradle`

  Installed driver list:

  android: 2.0.2
  chrome: 1.0.5
  electron: 1.1.6
  ios: 1.0.67

**Comment by mengde0077** [comment]
uirecorder   v2.5.2

**Comment by mengde0077** [comment]
现在 录制出来的都是坐标 ，没有任何意义！

制服务器监听在端口: 9765
录制浏览器已开启
  tap: 106, 679
   ✓ 执行成功
  tap: 91, 770
   ✓ 执行成功
  tap: 157, 495
   ✓ 执行成功
  tap: 143, 608
   ✓ 执行成功
  tap: 153, 743
   ✓ 执行成功
  tap: 157, 884
   ✓ 执行成功
  tap: 653, 128
   ✓ 执行成功
  sendKeys: 瓜子
   ✖ 执行失败 An unknown server-side error occurred while processing the command.

**Comment by mengde0077** [comment]
我的用例 都是基于  录制脚本的，升级后都跑不了咯！  @yaniswang   大神靠你了！

**Comment by mengde0077** [comment]
我刚才升级到 v2.5.3  录制还是一样的！

录制服务器监听在端口: 9765
录制浏览器已开启
  tap: 123, 1902
   ✓ 执行成功
  tap: 136, 1001
   ✓ 执行成功
  tap: 612, 1166
   ✓ 执行成功
  tap: 732, 115
   ✓ 执行成功
  sendKeys: 瓜子
   ✖ 执行失败 An unknown server-side error occurred while processing the command.

**Comment by yaniswang** [comment]
你试试录一下macaca官方的app？

**Comment by mengde0077** [comment]
官方app 也是一样的！

? 测试脚本文件名: sample/test.and5.js
? App路径 (扩展名: apk, app, zip): /Users/caolinming/Desktop/githubDir/macaca-sample/macaca-java
-biz-sample/app/android-app-bootstrap.zip

录制服务器监听在端口: 9765
录制浏览器已开启
  tap: 296, 1035
   ✓ 执行成功
  sendKeys: admin
   ✖ 执行失败 An unknown server-side error occurred while processing the command.
  tap: 977, 1127
   ✓ 执行成功
  tap: 529, 1492
   ✓ 执行成功
  tap: 535, 1223
   ✓ 执行成功
  tap: 330, 958
   ✓ 执行成功

------------------------------------------------------------------

共录制6个步骤
录制脚本已保存: sample/test.and5.js

录制服务器已关闭
录制浏览器已关闭

**Comment by mengde0077** [comment]
我点击 login、list 等按钮 ，录制的都是坐标！

**Comment by yaniswang** [comment]
的确，我刚试了新版macaca，也出现了这个问题，我马上适配一下新版。

**Comment by xudafeng** [comment]
@zhuyali

**Comment by mengde0077** [comment]
好的 ！ 3Q

**Comment by HeartIsBeat** [comment]
@yaniswang macaca1.1.9   uirecorder2.5.3  android2.0.16 也出现了只录制坐标的问题，能解决么？

**Comment by yaniswang** [comment]
正在适配中，近期很快会发布新版本。

**Comment by yaniswang** [comment]
uirecorder v2.5.5已经修复了所有问题
