### ISSUE TITLE
录制时增加case编号，便于快速定位错误脚本，脚本录制太多

### ISSUE THREAD

**Issue by magiccops** [alibaba/uirecorder#93]
一个 SUITE 下 case 太多，错误行不能立刻定位，希望在录制的时候增加 SUITE 内唯一编号，或序号。

**Comment by yaniswang** [comment]
增加编号，维护起来会比较麻烦，比如中间你想手工增加一个步骤，那后面的序号要全部重新调整了。

错误行定位实际上在报告里就可以直接查看错误的对应代码。
