### ISSUE TITLE
关于多级悬停功能的改进

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#94]
最近在使用UI Recorder的过程中发现，在面对多级菜单等连续悬浮动作场景时，当前的使用流程需要借助额外的快捷键（如Ctrl）进行多次操作才能完成，让人感觉略显复杂。
其实，这类操作的模拟也可以有比较优雅舒适的方法。省去一系列分析过程，这里直接给出我思考之后的结果，希望能给UI Recorder开发团队提供一些思路：

悬停交互改进方案：**悬停模式**

**界面调整**
改“添加悬停”按钮为“悬停模式”（togglebutton形式）

**交互流程**
点击该按钮进入悬停模式后，鼠标悬停在一个地方不动超过一定时间（比如1秒）则视作一个悬停动作，悬停所在元素可高亮，让用户知道悬停动作已生效。基于此方法，即便是需要连续悬浮操作的多级导航菜单，也可以沿路一直悬浮直到用户想要的内容出现。如需退出，只需再次点击该悬停模式按钮。退出后，一切照常，不再采集悬停动作即可。

**方案优势**

1. 使用过程最大程度接近实际操作，整个交互顺畅自然。即便是复杂场景，无需反复操作也能轻松驾驭。
2. 几乎没有学习成本（使用Ctrl键），同时也保证了不会有潜在的副作用（Ctrl键冲突）。
3. 由于鼠标既不需要离开悬停区域，导致可能触发悬浮框关闭的问题，又不需要考虑后续可能引发的断言问题，因此也是一举两得。

**Comment by yaniswang** [comment]
自动悬停功能，我们当初一开始就开发了。

但是当初一开始我们是默认就打开了自动悬停功能，之前是设置在某个区域停留超过多少时间，就会记录成悬停。

但是，在实际使用过程中，发现这个功能会产生非常多的噪音，因此后来这个功能就关闭了。

不过你的建议非常赞，自动悬停功能，可以作为开关进行打开或关闭。

这样用户主动打开的自动悬停功能，就不会有当初的问题场景。

**Comment by stevobm** [comment]
对啊，主要是开启之后用户知道悬停会记录，然后再悬停生效的时候加个样式，这样就很好用了。

**Comment by yaniswang** [comment]
我仔细想了下，自动悬停还是有问题。
不过，我另外想了一个比较好的交互：

悬停模式：

1. 按住ctrl键，点击添加悬停按钮，进入悬停模式
2. 鼠标移动到目标控件，点击鼠标添加悬停（此过程可连续多次操作）
3. 过程中可以添加断言
4. 如果需要退出悬停模式，可以按esc键

旧悬停模式：

1. 按住ctrl键，点击添加悬停按钮，进入多悬停模式
2. 鼠标移动到目标控件，点击鼠标添加悬停（此过程无法多次操作）
3. 过程中可以添加断言
4. 悬停添加后，自动退出悬停模式，无法连续添加

**Comment by yaniswang** [comment]
v2.5.6已经发布，改为了悬停模式切换

**Comment by yaniswang** [comment]
考虑到绝大部分的需求都是单一悬停模式，因此2.5.8版本中又改为默认是单一悬停模式，当需要重复悬停或者添加断言时，按下`Ctrl`键再按`添加悬停`就可以进入持续悬停模式。

阿里集团内部有用户反馈，默认为持续悬停模式，使用起来成本非常高。

**Comment by stevobm** [comment]
好的，我会跟进试用一下改进后的版本。
