### ISSUE TITLE
回放脚本可以打开chrome，但无法打开ie10

### ISSUE THREAD

**Issue by chyzhangxue** [alibaba/uirecorder#96]
你好，我下载了 iedriver（版本：IEDriverServer_x64_2.53.1），然后将iedriver复制到浏览器的安装目录下，再把ie的安装目录添加到系统的path环境变量中。结果每次回放脚本IE都报错
错误 信息如下：
 2) pcLogin : ie 11 "before all" hook:
    Error: done() invoked with non-Error: The path to the driver executable mus
 be set by the webdriver.ie.driver system property; for more information, see h
tps://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest ve
sion can be downloaded from http://selenium-release.storage.googleapis.com/inde
.html
     at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by yaniswang** [comment]
https://github.com/alibaba/uirecorder/blob/master/README_zh-cn.md

请使用uirecorder配套的解决方案： `npm run server`

**Comment by chyzhangxue** [comment]
抱歉哈，我试着用这种方式启动服务还是不行，还是出现上面的错误，能再帮我看下吗？

**Comment by yaniswang** [comment]
你是什么操作系统？mac还是windows？
