### ISSUE TITLE
安卓真机录制出错No such file or directory

### ISSUE THREAD

**Issue by HeartIsBeat** [alibaba/uirecorder#97]
Os is win10.
uirecorder v2.5.3 macaca v1.1.9
when run “uirecorder start --mobile”，it failed
![image](https://cloud.githubusercontent.com/assets/20472976/26134536/f733ac78-3ae1-11e7-8783-2c6fd6668ce9.png)
image
![image](https://cloud.githubusercontent.com/assets/20472976/26134532/f02e9c8a-3ae1-11e7-99e9-1610aabdc824.png)
image
![image](https://cloud.githubusercontent.com/assets/20472976/26134542/ff13c176-3ae1-11e7-941b-4a013323e0e5.png)
大神，我哪里错了？

**Comment by yaniswang** [comment]
你这个是macaca内部有问题，你试试升级到最新版macaca，应该就能解决这个问题了。
之前的macaca2.0还有点问题，现在非常稳定了。
