### ISSUE TITLE
iOS录制后回放总是定位不到元素

### ISSUE THREAD

**Issue by zhugehui9527** [alibaba/uirecorder#98]
node：7.10
UIRecorder：2.5.6
app：https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip
设备：模拟器 10.3
描述：登录前的操作都没有问题，点击login后开始，就定位不到了，回放一直报错，查看服务端日志，sessionId为空。换了app也总是出现定位不到的情况，麻烦查看一下ios-app-bootstrap 是否录制都是OK的？还是只有我有这种情况，Android端正常，就IOS端就没成功完整录制成功过。

**Comment by yaniswang** [comment]
你的macaca是什么版本？是最新的2.0版吗？
把你的macaca doctor截个图看下。

**Comment by zhugehui9527** [comment]
`▶ macaca doctor         

  macaca-doctor version: 2.0.0


  Node.js checklist:

  node env: /Users/zengyuanchen/.nvm/versions/node/v7.7.2/bin/node
  node version: v7.7.2

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_92`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/Android/sdk`
  Platforms is set to `/usr/local/opt/Android/sdk/platforms/android-25`
  ADB tool is set to `/usr/local/opt/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.17 [out-of-date]
  chrome: 1.0.5
  electron: 1.1.6
  ios: 2.0.11



~  master ✗                                                                                          ◒  
▶ macaca -v

  2.0.1`

**Comment by yaniswang** [comment]
从你的信息来看，没看出什么问题来。

用这个app我在本机用模拟器试了下，没出现任何问题，很完美。

**Comment by zhugehui9527** [comment]
这就尴尬了，我换了一台mac pro 10.12.4，也是一样的问题，昨天找了一天的问题，都没找到原因，给你看一下日志` source run.sh sample/boots1.spec.js

> uirecorderTest@1.0.0 singletest /Users/zengyuanchen/Test_Mobile/iOS
> mocha --reporter mochawesome-uirecorder "sample/boots1.spec.js"

[mochawesome] Generating report files...



  sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA
    ✓ tap: //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField (990ms)
    ✓ sendKeys: 13188880001

    ✓ tap: //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSecureTextField (1046ms)
    ✓ sendKeys: test123

    ✓ tap: Login ( //*[@name="Login"] ) (2082ms)
    1) tap: list ( //*[@name="list"] )
    2) tap: Alert ( //*[@name="Alert"] )
    3) acceptAlert: 
    4) tap: Back ( //*[@name="Back"] )
    ✓ drag: 206, 421, 225, 172, 0.30 (1806ms)
    ✓ drag: 225, 151, 206, 348, 0.36 (1296ms)
    5) tap: HOME ( //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeNavigationBar/XCUIElementTypeButton )
    ✓ tap: Webview ( //*[@name="Webview"] ) (1106ms)
    ✓ tap: Baidu ( //*[@name="Baidu"] ) (957ms)
    ✓ tap: PERSONAL ( //*[@name="PERSONAL"] ) (1401ms)
    6) tap: Logout ( //*[@name="Logout"] )


  10 passing (4m)
  6 failing

  1) sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA tap: list ( //*[@name="list"] ):
     Error: the string "Wait element displayed timeout: //*[@name=\"list\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:566:18
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  2) sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA tap: Alert ( //*[@name="Alert"] ):
     Error: the string "Wait element displayed timeout: //*[@name=\"Alert\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:566:18
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  3) sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA acceptAlert: :
     Error: the object {
  "sessionId": "ad5446dc-096f-4686-8919-4f37aefbf728"
  "status": 27
  "value": ""
} was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:566:18
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  4) sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA tap: Back ( //*[@name="Back"] ):
     Error: the string "Wait element displayed timeout: //*[@name=\"Back\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:566:18
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  5) sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA tap: HOME ( //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeNavigationBar/XCUIElementTypeButton ):
     Error: the string "Wait element displayed timeout: //*[@name=\"Bootstrap\"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeNavigationBar/XCUIElementTypeButton ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:566:18
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  6) sample/boots1.spec : 24F505C6-74FF-4CEC-A733-F055EE23FBAA tap: Logout ( //*[@name="Logout"] ):
     Error: the string "Wait element displayed timeout: //*[@name=\"Logout\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@3.1.2@mocha/lib/runner.js:233:11)
      at node_modules/_mocha@3.1.2@mocha/lib/runner.js:566:18
      at done (node_modules/_mocha@3.1.2@mocha/lib/runnable.js:293:5)
      at node_modules/_mocha@3.1.2@mocha/lib/runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)




[mochawesome] Report saved to reports/index.html
[mochawesome] Report saved to reports/index.xml`

**Comment by zhugehui9527** [comment]
这是录制的脚本
`
var fs = require('fs');
var path = require('path');
var cp = require('child_process');
var chai = require("chai");
var should = chai.should();
var JWebDriver = require('jwebdriver');
chai.use(JWebDriver.chaiSupportChainPromise);

var rootPath = getRootPath();
var appPath = 'ios-app-bootstrap.zip';
var platformName = 'iOS';

module.exports = function(){

    var driver, testVars;

    before(function(){
        var self = this;
        driver = self.driver;
        testVars = self.testVars;
    });

    it('tap: //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField', async function(){
        await driver.wait('//*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField', 30000).sendElementActions('tap');
    });

    it('sendKeys: 13188880001\n', async function(){
        await driver.sendKeys(_(`13188880001\n`));
    });

    it('tap: //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSecureTextField', async function(){
        await driver.wait('//*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSecureTextField', 30000).sendElementActions('tap');
    });

    it('sendKeys: test123\n', async function(){
        await driver.sendKeys(_(`test123\n`));
    });

    it('tap: Login ( //*[@name="Login"] )', async function(){
        await driver.wait('//*[@name="Login"]', 30000).sendElementActions('tap');
    });

    it('tap: list ( //*[@name="list"] )', async function(){
        await driver.wait('//*[@name="list"]', 30000).sendElementActions('tap');
    });

    it('tap: Alert ( //*[@name="Alert"] )', async function(){
        await driver.wait('//*[@name="Alert"]', 30000).sendElementActions('tap');
    });

    it('acceptAlert: ', async function(){
        await driver.acceptAlert();
    });

    it('tap: Back ( //*[@name="Back"] )', async function(){
        await driver.wait('//*[@name="Back"]', 30000).sendElementActions('tap');
    });

    it('drag: 206, 421, 225, 172, 0.30', async function(){
        await driver.sendActions('drag', {fromX: 206, fromY:421, toX:225, toY:172, duration: 0.30});
    });

    it('drag: 225, 151, 206, 348, 0.36', async function(){
        await driver.sendActions('drag', {fromX: 225, fromY:151, toX:206, toY:348, duration: 0.36});
    });

    it('tap: HOME ( //*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeNavigationBar/XCUIElementTypeButton )', async function(){
        await driver.wait('//*[@name="Bootstrap"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeNavigationBar/XCUIElementTypeButton', 30000).sendElementActions('tap');
    });

    it('tap: Webview ( //*[@name="Webview"] )', async function(){
        await driver.wait('//*[@name="Webview"]', 30000).sendElementActions('tap');
    });

    it('tap: Baidu ( //*[@name="Baidu"] )', async function(){
        await driver.wait('//*[@name="Baidu"]', 30000).sendElementActions('tap');
    });

    it('tap: PERSONAL ( //*[@name="PERSONAL"] )', async function(){
        await driver.wait('//*[@name="PERSONAL"]', 30000).sendElementActions('tap');
    });

    it('tap: Logout ( //*[@name="Logout"] )', async function(){
        await driver.wait('//*[@name="Logout"]', 30000).sendElementActions('tap');
    });

    function _(str){
        if(typeof str === 'string'){
            return str.replace(/\{\{(.+?)\}\}/g, function(all, key){
                return testVars[key] || '';
            });
        }
        else{
            return str;
        }
    }

};

if(module.parent && /mocha\.js/.test(module.parent.id)){
    runThisSpec();
}

function runThisSpec(){
    // read config
    var config = require(rootPath + '/config.json');
    var webdriverConfig = Object.assign({},config.webdriver);
    var host = webdriverConfig.host;
    var port = webdriverConfig.port || 4444;
    var testVars = config.vars;

    var screenshotPath = rootPath + '/screenshots';
    var doScreenshot = fs.existsSync(screenshotPath);

    var specName = path.relative(rootPath, __filename).replace(/\\/g,'/').replace(/\.js$/,'');

    var arrDeviceList = getEnvList() || getDeviceList(platformName);
    if(arrDeviceList.length ===0 ){
        console.log('Search mobile device failed!');
        process.exit(1);
    }

    arrDeviceList.forEach(function(device){
        var caseName = specName + ' : ' + (device.name?device.name+' ['+device.udid+']':device.udid);

        if(doScreenshot){
            mkdirs(path.dirname(screenshotPath + '/' + caseName));
        }

        describe(caseName, function(){

            var stepId = 1;

            this.timeout(600000);
            this.slow(1000);

            before(function(){
                var self = this;
                var driver = new JWebDriver({
                    'host': host,
                    'port': port
                });
                self.driver = driver.session({
                    'platformName': platformName,
                    'udid': device.udid,
                    'app': /^(\/|[a-z]:\\|https?:\/\/)/i.test(appPath) ? appPath : rootPath + '/' + appPath
                });
                self.testVars = testVars;
                return self.driver;
            });

            module.exports();

            afterEach(function(){
                if(doScreenshot){
                    var filepath = screenshotPath + '/' + caseName.replace(/[^\/]+$/, function(all){
                        return all.replace(/\s*[:\.\:\-\s]\s*/g, '_');
                    }) + '_' + (stepId++) + '.png';
                    return this.driver.getScreenshot(filepath).catch(function(){});
                }
            });

            after(function(){
                return this.driver.close();
            });

        });
    });
}

function getRootPath(){
    var rootPath = path.resolve(__dirname);
    while(rootPath){
        if(fs.existsSync(rootPath + '/config.json')){
            break;
        }
        rootPath = rootPath.substring(0, rootPath.lastIndexOf(path.sep));
    }
    return rootPath;
}

function mkdirs(dirname){
    if(fs.existsSync(dirname)){
        return true;
    }else{
        if(mkdirs(path.dirname(dirname))){
            fs.mkdirSync(dirname);
            return true;
        }
    }
}

function callSpec(name){
    try{
        require(rootPath + '/' + name)();
    }
    catch(e){
        console.log(e)
        process.exit(1);
    }
}

function getEnvList(){
    var strEnvList = process.env.devices;
    if(strEnvList){
        return strEnvList.split(/\s*,\s*/).map(function(udid){
            return {udid: udid};
        });
    }
}

function getDeviceList(platformName){
    var arrDeviceList = [];
    var strText, match;
    if(platformName === 'Android')
    {
        // for android
        strText = cp.execSync('adb devices').toString();
        strText.replace(/(.+?)\s+device\r?\n/g, function(all, deviceName){
            arrDeviceList.push({
                udid: deviceName
            });
        });
    }
    else{
        // ios real device
        strText = cp.execSync('idevice_id -l').toString();
        strText.replace(/(.+)\r?\n/g, function(all, udid){
            var deviceName = cp.execSync('idevice_id -d '+udid).toString();
            deviceName = deviceName.replace(/\r?\n/g, '');
            arrDeviceList.push({
                name: deviceName,
                udid: udid
            });
        });
        // ios simulator
        strText = cp.execSync('xcrun simctl list devices').toString();
        strText.replace(/\r?\n\s*(.+?)\s+\((.+?)\) \(Booted\)/g, function(all, deviceName, udid){
            arrDeviceList.push({
                name: deviceName,
                udid: udid
            });
        });
    }
    return arrDeviceList;
}


`

**Comment by yaniswang** [comment]
你是录制正常的，回放才出问题？

**Comment by zhugehui9527** [comment]
macaca server 端也没报错日志，截取了回放失败的操作日志
` responseHandler.js:11:12 [master] pid:30070 Recieve HTTP Request from Client[2017-06-02 09:04:22]: method: POST url: /wd/hub/session/7a75c0f9-42bb-440b-9477-18339f6942e9/elements, jsonBody: {"using":"xpath","value":"//*[@name=\"list\"]"}
>> proxy.js:55:14 [master] pid:30070 Proxy: /wd/hub/session/7a75c0f9-42bb-440b-9477-18339f6942e9/elements:POST to http://localhost:8002/wd/hub/session/93CC3178-88BF-4848-A74B-5C0012DFBEA3/elements:POST with body: {"using":"xpath","value":"//*[@name=\"list\"]"}
>> proxy.js:83:20 [master] pid:30070 Got response with status 200: {"sessionId":"","status":0,"value":[]}
>> session.js:107:14 [master] pid:30070 Send HTTP Respone to Client[2017-06-02 09:04:22]: {"sessionId":"","status":0,"value":"[]"}
>> responseHandler.js:11:12 [master] pid:30070 Recieve HTTP Request from Client[2017-06-02 09:04:23]: method: POST url: /wd/hub/session/7a75c0f9-42bb-440b-9477-18339f6942e9/elements, jsonBody: {"using":"xpath","value":"//*[@name=\"list\"]"}
>> proxy.js:55:14 [master] pid:30070 Proxy: /wd/hub/session/7a75c0f9-42bb-440b-9477-18339f6942e9/elements:POST to http://localhost:8002/wd/hub/session/93CC3178-88BF-4848-A74B-5C0012DFBEA3/elements:POST with body: {"using":"xpath","value":"//*[@name=\"list\"]"}
>> proxy.js:83:20 [master] pid:30070 Got response with status 200: {"sessionId":"","status":0,"value":[]}
>> session.js:107:14 [master] pid:30070 Send HTTP Respone to Client[2017-06-02 09:04:23]: {"sessionId":"","status":0,"value":"[]"}
>> responseHandler.js:11:12 [master] pid:30070 Recieve HTTP Request from Client[2017-06-02 09:04:23]: method: POST url: /wd/hub/session/7a75c0f9-42bb-440b-9477-18339f6942e9/elements, jsonBody: {"using":"xpath","value":"//*[@name=\"list\"]"}
>> proxy.js:55:14 [master] pid:30070 Proxy: /wd/hub/session/7a75c0f9-42bb-440b-9477-18339f6942e9/elements:POST to http://localhost:8002/wd/hub/session/93CC3178-88BF-4848-A74B-5C0012DFBEA3/elements:POST with body: {"using":"xpath","value":"//*[@name=\"list\"]"}
`

**Comment by zhugehui9527** [comment]
是的，录制正常，就回放出现这种问题

**Comment by yaniswang** [comment]
我本地也重现了，我查下原因

**Comment by yaniswang** [comment]
重装下新版的macaca-ios： cnpm i macaca-ios -g

新版已经修复了这个问题

**Comment by zhugehui9527** [comment]
升级后，可以正常使用了
